Repository openyurtio/openyurt, pull requests merged in 2021-05, with the labels that each got.

#315 add resource and system requirements
  README.md
  README.zh.md
  docs/resource-and-system-requirements-cn.md
  docs/resource-and-system-requirements.md
Labels: approved, lgtm, size/M

#316 [Doc] Add 0.4.0 CHANGELOG
  CHANGELOG.md
  README.md
  README.zh.md
  hack/lib/init.sh
Labels: approved, size/M

#309 Add the Owner configuration
  OWNERS
Labels: size/XS

#318 update tutorial README
  docs/tutorial/README.md
Labels: approved, lgtm, size/XS

#307 change pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/enhancement, lgtm, size/M

#308 perfect issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, lgtm, size/M

#320 change pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/enhancement, lgtm, size/M

#317 fix bugs of yurctl
  pkg/yurtctl/cmd/convert/edgenode.go
  pkg/yurtctl/cmd/revert/edgenode.go
  pkg/yurtctl/util/edgenode/util.go
Labels: approved, kind/bug, lgtm, size/L

#322 doc: add community membership into governance.md
  GOVERNANCE.md
Labels: approved, kind/documentation, lgtm, size/M

#319 add logs for eviction error
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
Labels: approved, kind/enhancement, lgtm, size/XS

#323 bugfix: update clusterrole and certificate for yurt-tunnel-server and fix kubeconfig path error for yurtctl
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
  pkg/yurtctl/util/edgenode/util.go
  pkg/yurttunnel/pki/certmanager/certmanager.go
  pkg/yurttunnel/server/serveraddr/addr.go
  pkg/yurttunnel/server/serveraddr/addr_test.go
Labels: approved, kind/bug, lgtm, size/L

#324 v0.4.0: release node-resource-manager
  CHANGELOG.md
  README.md
Labels: approved, lgtm, size/S

#329 Yurtctl code adds the verification of cluster version 1.20 and above.
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/XS
