Repository openyurtio/openyurt, pull requests merged in 2021-09, with the labels that each got.

#444 Yurtctl: more comfortable command line
  pkg/yurtctl/cmd/cmd.go
Labels: approved, lgtm, size/S, kind/feature

#446 remove excess chan that will block the program
  cmd/yurthub/app/start.go
Labels: approved, kind/bug, lgtm, size/XS

#448 The shebang must be on the first line. Delete blanks and move comments
  hack/lib/build.sh
  hack/lib/common.sh
  hack/lib/init.sh
  hack/lib/release-images.sh
  hack/make-rules/build.sh
  hack/make-rules/release-images.sh
Labels: approved, lgtm

#452 bugfix: fix incomplete data copy of resource filter
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/filter/filter.go
Labels: approved, kind/bug, lgtm, size/XS

#445 Yurthub: remove duplicate error logs
  cmd/yurthub/app/start.go
Labels: approved, lgtm, size/M, kind/feature

#451 bugfix: move MaxInFlightLimit handler chain after RequestClientComponent
  pkg/yurthub/proxy/proxy.go
Labels: approved, kind/bug, lgtm, size/XS

#454 feature: [yurthub] improve list/watch node pool resource in serviceTopology fil…
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
Labels: approved, lgtm, size/S

#440 feature: add discard cloud service filter in yurthub
  cmd/yurthub/app/config/config.go
  pkg/yurthub/filter/discardcloudservice/filter.go
  pkg/yurthub/filter/discardcloudservice/handler.go
Labels: approved, lgtm, size/L, kind/feature

#455 enhancement: add name info for filters
  cmd/yurthub/app/start.go
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/discardcloudservice/filter.go
  pkg/yurthub/filter/filter.go
  pkg/yurthub/filter/masterservice/filter.go
  pkg/yurthub/filter/servicetopology/filter.go
Labels: approved, kind/enhancement, lgtm, size/M

#442 feature: support proxy https request from cloud to edge through yurt-tunnel
  cmd/yurt-tunnel-server/app/start.go
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
  pkg/yurttunnel/dns/dns.go
  pkg/yurttunnel/dns/dns_test.go
  pkg/yurttunnel/iptables/iptables.go
  pkg/yurttunnel/iptables/iptables_test.go
  pkg/yurttunnel/util/util.go
  pkg/yurttunnel/util/util_test.go
Labels: approved, lgtm, size/XL, kind/feature

#457 bugfix: prepare yurthub server tls config panic
  pkg/yurthub/gc/gc.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/server/server.go
Labels: approved, kind/bug, lgtm, size/M

#459 Docs: add more nodes for --cloud-nodes
  docs/tutorial/yurtctl.md
Labels: approved, lgtm, size/XS

#463 fix typo; covert->convert
  docs/tutorial/yurt-tunnel.md
  pkg/yurtctl/cmd/convert/edgenode.go
Labels: approved, lgtm, size/XS

#429 Update yurtcluster operator proposal
  docs/proposals/20210722-yurtcluster-operator.md
Labels: approved, lgtm, size/L, kind/design

#456 update golang version to v1.15.13
  hack/lib/release-images.sh
Labels: approved, kind/enhancement, lgtm, size/XS

#464 enhancement: enable kube-proxy and addons access kube-apiserver through yurthub
  cmd/yurthub/app/options/options.go
Labels: approved, kind/enhancement, lgtm, size/XS

#466 enhancement: add configmap to configure user agents for specify response cache.
  cmd/yurthub/app/start.go
  config/setup/yurthub-cfg.yaml
  pkg/yurthub/cachemanager/cache_agent.go
  pkg/yurthub/cachemanager/cache_agent_test.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/cachemanager/cache_manager_test.go
  pkg/yurthub/proxy/local/local_test.go
  pkg/yurthub/util/util.go
Labels: approved, lgtm, size/L, kind/feature

#468 Add SataQiu as a reviewer of openyurtio/openyurt
  OWNERS
Labels: size/XS

#469 Add qclc as a reviewer of openyurt
  OWNERS
Labels: approved, lgtm, size/XS

#471 bugfix: use buffered channel for signal notifications
  cmd/yurt-tunnel-server/server.go
Labels: approved, kind/bug, lgtm, size/XS

#472 enhancement: optimize rabc setting of openyurt components
  config/setup/yurt-controller-manager.yaml
  config/setup/yurt-tunnel-server.yaml
  config/setup/yurthub-cfg.yaml
  config/yaml-template/yurt-controller-manager.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  config/yaml-template/yurthub-cfg.yaml
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
  pkg/yurtctl/util/edgenode/common.go
Labels: approved, lgtm, size/L

#470 add some unit tests for yurt tunnel
  pkg/profile/profile_test.go
  pkg/yurttunnel/dns/util.go
  pkg/yurttunnel/dns/util_test.go
  pkg/yurttunnel/handlerwrapper/tracerequest/tracereq_test.go
  pkg/yurttunnel/server/interceptor_test.go
  pkg/yurttunnel/server/serveraddr/addr_test.go
  pkg/yurttunnel/util/util_test.go
Labels: approved, lgtm, size/XL

#477 bugfix: exclude the effect of empty strings for agents
  pkg/yurthub/cachemanager/cache_agent.go
  pkg/yurthub/cachemanager/cache_agent_test.go
Labels: approved, kind/bug, lgtm, size/M

#475 perf: improve the usage of certificates
  pkg/yurttunnel/pki/certmanager/certmanager.go
  pkg/yurttunnel/pki/pki.go
  test/e2e/yurt/yurt.go
Labels: approved, lgtm, size/M

#473 read podManifestPath from kubeadm file
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/convert/edgenode.go
  pkg/yurtctl/cmd/revert/edgenode.go
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/util/edgenode/util.go
  pkg/yurtctl/util/edgenode/util_test.go
Labels: approved, lgtm, size/L

#490 rm duplicated code
  pkg/yurtctl/cmd/convert/edgenode.go
Labels: approved, kind/bug, lgtm, size/XS

#483 feature: add --working-mode flag for yurthub
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurthub/filter/constant.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/util/util.go
Labels: approved, lgtm, size/L, kind/feature

#493 Update convert.go
  pkg/yurtctl/cmd/convert/convert.go
Labels: approved, lgtm, size/XS

#491 Update config.go
  cmd/yurthub/app/config/config.go
Labels: approved, lgtm, size/XS

#492 add DeleteYurthubSetting to revert
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/util/edgenode/common.go
  pkg/yurtctl/util/kubernetes/apply_addons.go
Labels: approved, lgtm, size/M

#482 yurthub: stop renew node lease when kubelet's heartbeat is stopped
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  pkg/yurthub/healthchecker/fake_checker.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/proxy/proxy.go
Labels: approved, size/M

#495 enhancement: disable health checker in cloud mode
  cmd/yurthub/app/start.go
Labels: approved, kind/enhancement, lgtm, size/S

#494 Add tunnel server address
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/yurtinit/init.go
  pkg/yurtctl/cmd/yurtinit/phases/install_yurt_addons.go
  pkg/yurtctl/cmd/yurtinit/phases/types.go
  pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
  pkg/yurtctl/util/kubernetes/apply_addons.go
Labels: approved, lgtm, size/L

#500 add create to yurt-tunnel-server ClusterRole
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
Labels: approved, lgtm, size/XS

#503 docs: revise changelog and readme for releasing v0.5.0
  CHANGELOG.md
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/M

#507 Bump version to v0.5.0
  hack/lib/init.sh
Labels: approved, lgtm, size/XS

#509 bugfix: add client auth key usage to yurt-tunnel-server certmanager
  pkg/yurttunnel/pki/certmanager/certmanager.go
Labels: approved, kind/bug, lgtm, size/XS

#422 Proposal: YurtAppDaemon
  docs/enhancements/20210729-yurtappdaemon.md
Labels: approved, kind/documentation, lgtm, size/L, kind/feature

#512 pull yurt-tunnel-server image when IfNotPresent
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
Labels: approved, kind/bug, lgtm, size/XS

#496 e2e: add e2e test into github action
  .github/workflows/ci.yaml
  Makefile
  hack/kind-config-template.yaml
  hack/lib/release-images.sh
  hack/local_up_openyurt.sh
  hack/run-e2e-tests.sh
Labels: approved, kind/enhancement, lgtm, size/L

#510 bugfix(yurtctl): ensure the join token of yurthub has right usages and groups
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, kind/bug, lgtm, size/M
