Repository openyurtio/openyurt, pull requests merged in 2021-07, with the labels that each got.

#371 Update util.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/XS

#341 proposal to add subcommands init, join, reset for yurtctl.
  docs/img/img-20210607001.png
  docs/img/img-20210607002.png
  docs/proposals/20210607-adding-subcommands-server-join-reset-for-yurtctl.md
Labels: approved, kind/design, lgtm, size/L

#369 Add StorageWrapper test case
  .gitignore
  pkg/yurthub/cachemanager/storage_wrapper.go
  pkg/yurthub/cachemanager/storage_wrapper_test.go
Labels: approved, lgtm, size/L

#378 Fix the bug that tunnel-agent/tunnel-server crashes when the local certificate can not be loaded correctly
  pkg/yurttunnel/pki/certmanager/certmanager.go
  pkg/yurttunnel/pki/certmanager/store/filestore_wrapper.go
Labels: approved, kind/bug, lgtm, size/M

#373 proposal: add ingress feature support to nodepool
  docs/proposals/20210628-nodepool-ingress-support.md
Labels: approved, lgtm, size/L

#381 Add sync.Pool to cache *bufio.Reader in tunnel server
  README.md
  README.zh.md
  pkg/yurttunnel/server/interceptor.go
Labels: approved, kind/enhancement, lgtm, size/M

#365 Docs: better autonomy test tutorial
  docs/tutorial/yurtctl.md
Labels: approved, kind/documentation, lgtm, size/S

#359 fix the error when cert-mgr-mode set to kubelet
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurtctl/util/edgenode/common.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/certificate/hubself/fake_cert_mgr.go
  pkg/yurthub/certificate/interfaces/interfaces.go
  pkg/yurthub/certificate/kubelet/cert_mgr.go
  pkg/yurthub/certificate/kubelet/cert_mgr_test.go
  pkg/yurthub/gc/gc.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/transport/transport.go
  pkg/yurthub/util/util.go
Labels: approved, kind/bug, lgtm, size/XL

#357 EdgeX integration with OpenYurt proposal
  docs/img/edgex/edgexinstance.png
  docs/img/edgex/overview.png
  docs/proposals/20210310-edge-device-management.md
  docs/proposals/202106120-edgex-integration.md
Labels: approved, lgtm, size/L

#375 improve tunnel availability
  cmd/yurt-tunnel-agent/app/start.go
  cmd/yurt-tunnel-server/app/options/options.go
  pkg/yurttunnel/pki/certmanager/csrapprover.go
Labels: approved, kind/bug, lgtm, size/M

#388 Proposal: add data filtering framework on the edge
  docs/img/data-filtering-framework.png
  docs/img/improved-pod-inclusterconfig.png
  docs/img/original-pod-inclusterconfig.png
  docs/img/service-topology.png
  docs/proposals/20210720-data-filtering-framework.md
Labels: approved, kind/design, lgtm, size/L

#394 feature: add data filtering framework
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  go.mod
  go.sum
  pkg/yurthub/cachemanager/cache_agent.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/filter/approver.go
  pkg/yurthub/filter/chain.go
  pkg/yurthub/filter/filter.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/interfaces.go
  pkg/yurthub/filter/masterservice/filter.go
  pkg/yurthub/filter/masterservice/handler.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/filter/util/utils.go
  pkg/yurthub/kubernetes/serializer/serializer.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/proxy/remote/remote.go
Labels: approved, kind/feature, lgtm, size/XXL

#387 Add subcommand join to yurtctl.
  README.md
  docs/tutorial/yurtctl.md
  go.mod
  go.sum
  pkg/yurtctl/cmd/cmd.go
  pkg/yurtctl/cmd/convert/edgenode.go
  pkg/yurtctl/cmd/join/join.go
  pkg/yurtctl/cmd/join/phases/constants.go
  pkg/yurtctl/cmd/join/phases/join-cloud-node.go
  pkg/yurtctl/cmd/join/phases/join-edge-node.go
  pkg/yurtctl/cmd/join/phases/postcheck.go
  pkg/yurtctl/cmd/join/phases/prepare.go
  pkg/yurtctl/cmd/join/phases/type.go
  pkg/yurtctl/util/edgenode/common.go
  pkg/yurtctl/util/edgenode/util.go
  pkg/yurtctl/util/util.go
  pkg/yurtctl/util/util_test.go
Labels: approved, kind/feature, lgtm, size/XXL

#396 bugfix: the same prefix key lock error
  pkg/yurthub/storage/disk/storage.go
  pkg/yurthub/storage/disk/storage_test.go
Labels: approved, kind/bug, lgtm, size/S

#397 enhancement: close the underlying connections every time the heartbeat fails
  pkg/yurthub/healthchecker/health_checker.go
Labels: approved, kind/enhancement, lgtm, size/XS

#398 feature: add traffic(from cloud to edge) collector metrics for yurthub
  pkg/yurthub/metrics/metrics.go
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/util/util.go
  pkg/yurthub/util/util_test.go
Labels: approved, kind/feature, lgtm, size/M

#389 Proposal: OpenYurt Convertor Operator for converting K8S to OpenYurt
  20210722-yurtcluster-operator.md
Labels: approved, kind/feature, lgtm, size/L

#401 Move 20210722-yurtcluster-operator.md to docs/proposals
  docs/proposals/20210722-yurtcluster-operator.md
Labels: approved, kind/bug, lgtm, size/XS

#399 Yurtctl modify kube-controllersetting to close the nodelifecycle-controller
  docs/tutorial/yurtctl.md
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/convert/edgenode.go
  pkg/yurtctl/cmd/revert/edgenode.go
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, kind/bug, lgtm, size/L

#386 change yurthub's protocol from http to https
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/controller/certificates/csrapprover.go
  pkg/yurthub/network/network.go
  pkg/yurthub/pki/certmanager/certmanager.go
  pkg/yurthub/pki/pki.go
  pkg/yurthub/server/server.go
Labels: approved, kind/feature, lgtm, size/XL
