Repository openyurtio/openyurt, pull requests merged in 2021-08, with the labels that each got.

#403 fix mutated master service address from yurthub's http server address to https server address.
  cmd/yurthub/app/config/config.go
Labels: approved, kind/bug, lgtm, size/XS

#405 doc: add release note of OpenYurt v0.4.1
  CHANGELOG.md
Labels: approved, kind/documentation, lgtm, size/M

#326 bugfix: fix querying local empty list error
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/start.go
  pkg/yurthub/cachemanager/cache_agent_test.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/cachemanager/cache_manager_test.go
  pkg/yurthub/kubernetes/meta/restmapper.go
  pkg/yurthub/kubernetes/meta/restmapper_test.go
  pkg/yurthub/kubernetes/serializer/serializer.go
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/local/local_test.go
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/storage/disk/storage.go
  pkg/yurthub/storage/disk/storage_test.go
Labels: approved, kind/bug, lgtm, size/XXL

#402 add reset subcommand.
  README.md
  docs/tutorial/yurtctl.md
  pkg/yurtctl/cmd/cmd.go
  pkg/yurtctl/cmd/join/phases/constants.go
  pkg/yurtctl/cmd/join/phases/prepare.go
  pkg/yurtctl/cmd/reset/phases/cleanfile.go
  pkg/yurtctl/cmd/reset/reset.go
  pkg/yurtctl/constants/constants.go
Labels: approved, lgtm, size/L, kind/feature

#346 Add yurt-tunnel-server graceful shut down
  cmd/yurt-tunnel-server/app/start.go
  cmd/yurt-tunnel-server/server.go
  pkg/yurttunnel/iptables/iptables.go
  pkg/yurttunnel/iptables/iptables_test.go
Labels: approved, kind/enhancement, lgtm, size/L

#406 Followup #386: update the ClusterRole for yurt-controller-manager
  config/setup/yurt-controller-manager.yaml
  config/yaml-template/yurt-controller-manager.yaml
  pkg/yurtctl/constants/constants.go
Labels: approved, kind/bug, lgtm, size/M

#407 fix pod access yurthub https endpoint error
  cmd/yurthub/app/start.go
  pkg/controller/certificates/csrapprover.go
  pkg/yurthub/certificate/pki.go
  pkg/yurthub/certificate/server/certmanager.go
  pkg/yurthub/server/server.go
Labels: approved, kind/bug, size/M

#408 doc: revise readme to v0.4.1 release info
  README.md
  README.zh.md
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  hack/lib/init.sh
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
Labels: approved, lgtm, size/S

#404 fix server tls config
  pkg/yurttunnel/pki/pki.go
Labels: approved, kind/bug, lgtm, size/XS

#370 Bugfix: kubelet on edge node keeps restarting issue
  pkg/yurtctl/cmd/revert/edgenode.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/certificate/hubself/fake_cert_mgr.go
Labels: approved, kind/bug, lgtm, size/S

#438 Docs: remove deprecated yurt-app-manager doc
  docs/tutorial/yurt-app-manager.md
Labels: approved, kind/documentation, lgtm, size/L

#437 enhancement: proxy request with bearer token in header without client certificate
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/transport/transport.go
Labels: approved, kind/enhancement, lgtm, size/M

#441 bug fix for autonomous
  pkg/yurtctl/cmd/convert/edgenode.go
Labels: approved, kind/bug, lgtm, size/S

#443 feature: support forward cloud requests to edge node's localhost endpoint
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
  pkg/yurttunnel/constants/constants.go
  pkg/yurttunnel/handlerwrapper/localhostproxy/handler.go
  pkg/yurttunnel/handlerwrapper/localhostproxy/handler_test.go
  pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
  pkg/yurttunnel/util/util.go
Labels: approved, lgtm, size/L, kind/feature
