Repository openyurtio/openyurt, pull requests merged in 2021-11, with the labels that each got.

#540 delete yurtctl-lock and yurt-tunnel-nodes when revert the whole cluster
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/lock/lock.go
  pkg/yurttunnel/constants/constants.go
  pkg/yurttunnel/dns/dns.go
  pkg/yurttunnel/dns/handler.go
  pkg/yurttunnel/dns/util.go
Labels: approved, kind/bug, lgtm, size/M

#543 enhancement: revise key usage of yurthub server certificate
  pkg/yurthub/certificate/server/certmanager.go
Labels: approved, kind/enhancement, lgtm, size/XS

#542 enhancement: add openyurt.io/skip-discard annotation verify for discardcloudservice filter
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/discardcloudservice/handler.go
  pkg/yurthub/filter/servicetopology/handler.go
Labels: approved, lgtm, size/S

#458 enhancement: skip ensure iptables rule error for yurthub
  pkg/yurthub/network/iptables.go
Labels: approved, kind/enhancement, lgtm, size/XS

#552 inject working_mode
  pkg/yurtctl/cmd/join/phases/join-edge-node.go
Labels: lgtm, size/XS

#553 Add demo in the README.md
  README.md
  docs/img/demo.jpeg
Labels: approved, lgtm, size/XS

#554 Add demo in the README.zh.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#555 Yurtctl revert adds the function of deleting yurt app manager
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/L

#556 Add adamzhoul as reviewer of openYurt
  OWNERS
Labels: approved, lgtm, size/XS

#559 Add DrmagicE as reviewer of OpenYurt
  OWNERS
Labels: approved, lgtm, size/XS

#560 bugfix post header accept error
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/proxy/util/util_test.go
Labels: approved, lgtm, size/S

#563 When yurtctl revert executes yurtappmanager to delete automatically, no crd resource error is reported.
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, kind/bug, lgtm, size/XS

#525 update yurt-tunnel-server certificate automatically
  cmd/yurt-tunnel-server/app/start.go
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  hack/lib/release-images.sh
  hack/local_up_openyurt.sh
  hack/run-e2e-tests.sh
  pkg/projectinfo/projectinfo.go
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
  pkg/yurttunnel/dns/dns.go
  pkg/yurttunnel/pki/certmanager/certmanager.go
  pkg/yurttunnel/server/serveraddr/addr.go
  pkg/yurttunnel/server/serveraddr/addr_test.go
Labels: approved, kind/good-first-issue, lgtm, size/XL, kind/feature

#570 The import package sort adjustment in the go file under the openyurt/pkg/controller path.
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/rate_limited_queue.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/util/node/controller_utils.go
Labels: approved, kind/enhancement, lgtm, size/S

#575 The import package sort adjustment in the go file.
  pkg/node-servant/components/yurthub.go
  pkg/node-servant/convert/options.go
  pkg/node-servant/job.go
  pkg/node-servant/revert/options.go
Labels: approved, kind/enhancement, lgtm, size/S

#578 modeprobe br-netfilter
  pkg/yurtctl/util/system/util.go
Labels: approved, lgtm, size/XS

#582 The import package sort adjustment in the go file.
  pkg/yurtctl/cmd/cmd.go
  pkg/yurtctl/cmd/join/join.go
  pkg/yurtctl/cmd/join/phases/join-cloud-node.go
  pkg/yurtctl/cmd/reset/reset.go
  pkg/yurtctl/cmd/revert/cloudnode.go
  pkg/yurtctl/cmd/revert/edgenode.go
  pkg/yurtctl/cmd/yurtinit/init.go
  pkg/yurtctl/lock/lock.go
  pkg/yurtctl/util/edgenode/util.go
  pkg/yurtctl/util/system/util.go
  pkg/yurtctl/util/util.go
Labels: approved, kind/enhancement, lgtm, size/M

#583 Add gnunu (shaoqiang.chen@intel.com) as a maintainer of OpenYurt.
  MAINTAINERS.md
Labels: approved, lgtm, size/XS

#586 Docs: update Chao's affiliation
  MAINTAINERS.md
Labels: approved, kind/documentation, lgtm, size/XS

#588 The import package sort adjustment in the go file.
  pkg/yurthub/cachemanager/cache_agent_test.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/cachemanager/cache_manager_test.go
  pkg/yurthub/cachemanager/storage_wrapper.go
  pkg/yurthub/cachemanager/storage_wrapper_test.go
  pkg/yurthub/certificate/certificate.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/certificate/hubself/fake_cert_mgr.go
  pkg/yurthub/certificate/interfaces/interfaces.go
  pkg/yurthub/certificate/kubelet/cert_mgr.go
  pkg/yurthub/certificate/server/certmanager.go
  pkg/yurthub/gc/gc.go
  pkg/yurthub/metrics/metrics.go
  pkg/yurthub/transport/transport.go
Labels: approved, kind/enhancement, lgtm, size/L

#580 Add qclc as maintainer of OpenYurt
  MAINTAINERS.md
Labels: approved, lgtm, size/XS

#579 Add DrmagicE as maintainer of OpenYurt
  MAINTAINERS.md
Labels: approved, lgtm, size/XS

#585 Refactor: separate the creation of informers from tunnel server component
  cmd/yurt-tunnel-server/app/start.go
  pkg/yurttunnel/dns/dns.go
  pkg/yurttunnel/informers/serverinformer.go
  pkg/yurttunnel/pki/certmanager/certmanager.go
Labels: approved, kind/enhancement, lgtm, size/L, kind/design

#589 Add SataQiu as a maintainer of OpenYurt
  MAINTAINERS.md
Labels: approved, lgtm, size/XS

#596 Add lwmqwer as maintainer of OpenYurt
  MAINTAINERS.md
Labels: approved, lgtm, size/XS

#598 use https[s] proxy in docker for release build if necessary
  hack/lib/release-images.sh
Labels: approved, kind/bug, lgtm, size/XS

#601 add make push for pushing images generated during make release
  Makefile
  hack/lib/release-images.sh
  hack/make-rules/push-images.sh
Labels: approved, kind/enhancement, lgtm, size/M

#592 The import package sort adjustment in the go file.
  pkg/yurthub/filter/discardcloudservice/handler.go
  pkg/yurthub/filter/filter.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/interfaces.go
  pkg/yurthub/filter/masterservice/handler.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/filter/util/utils.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/kubernetes/meta/restmapper.go
  pkg/yurthub/kubernetes/meta/restmapper_test.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/kubernetes/serializer/serializer.go
Labels: approved, kind/enhancement, lgtm, size/M

#605 The import package sort adjustment in the go file.
  pkg/yurthub/network/dummyif_linux.go
  pkg/yurthub/network/network.go
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/local/local_test.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/proxy/util/util_test.go
  pkg/yurthub/server/server.go
  pkg/yurthub/storage/disk/storage.go
  pkg/yurthub/util/connrotation.go
  pkg/yurthub/util/util.go
Labels: approved, kind/enhancement, lgtm, size/M

#606 add trafficforward that contains two diversion modes: DNAT and DNS
  cmd/yurt-tunnel-server/app/start.go
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurttunnel/trafficforward/dns/dns.go
  pkg/yurttunnel/trafficforward/dns/dns_test.go
  pkg/yurttunnel/trafficforward/dns/event.go
  pkg/yurttunnel/trafficforward/dns/handler.go
  pkg/yurttunnel/trafficforward/dns/util.go
  pkg/yurttunnel/trafficforward/dns/util_test.go
  pkg/yurttunnel/trafficforward/iptables/iptables.go
  pkg/yurttunnel/trafficforward/iptables/iptables_test.go
Labels: approved, lgtm, size/XS

#608 Docs: add docs about service topology.
  docs/tutorial/README.md
  docs/tutorial/service-topology.md
Labels: approved, kind/documentation, lgtm, size/L

#607 bugfix: service topology filter can not work when hub agent work on cloud mode
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/start.go
  pkg/yurthub/cachemanager/cache_agent.go
  pkg/yurthub/cachemanager/cache_agent_test.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/interfaces.go
  pkg/yurthub/filter/masterservice/filter.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/proxy/proxy.go
Labels: approved, kind/bug, lgtm, size/L

#611 The import package sort adjustment in the go file.
  pkg/yurttunnel/agent/anpagent.go
  pkg/yurttunnel/handlerwrapper/initializer/initalizer.go
  pkg/yurttunnel/handlerwrapper/localhostproxy/handler.go
  pkg/yurttunnel/informers/serverinformer.go
  pkg/yurttunnel/pki/certmanager/certmanager.go
  pkg/yurttunnel/server/anpserver.go
  pkg/yurttunnel/server/metrics/metrics.go
  pkg/yurttunnel/server/serveraddr/addr.go
  pkg/yurttunnel/server/serveraddr/addr_test.go
  pkg/yurttunnel/trafficforward/dns/handler.go
  pkg/yurttunnel/util/util.go
Labels: approved, kind/enhancement, lgtm, size/M

#593 bugfix: reject delete pod request by yurthub when cloud-edge network disconnected
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/local/local_test.go
Labels: approved, kind/bug, lgtm, size/XS

#614 use const instead the string
  pkg/yurtctl/util/edgenode/util.go
Labels: approved, lgtm, size/XS

#624 Docs: optimize some descriptions of the document
  docs/img/service-topology-example.png
  docs/tutorial/README.md
  docs/tutorial/service-topology.md
Labels: approved, kind/documentation, lgtm, size/L

#622 correct the comment line
  pkg/yurthub/certificate/certificate.go
  pkg/yurthub/certificate/kubelet/cert_mgr.go
  pkg/yurthub/healthchecker/health_checker.go
Labels: approved, lgtm

#627 The import package sort adjustment in the go file.
  cmd/yurt-controller-manager/app/config/config.go
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/options/debugging.go
  cmd/yurt-controller-manager/app/options/nodelifecyclecontroller.go
  cmd/yurt-controller-manager/controller-manager.go
  cmd/yurt-node-servant/revert/revert.go
Labels: approved, kind/enhancement, lgtm, size/S

#621 Remove k8s.io/kubernetes dependency for yurt-tunnel
  go.mod
  pkg/util/iptables/iptables.go
  pkg/util/iptables/iptables_linux.go
  pkg/util/iptables/iptables_test.go
  pkg/util/iptables/iptables_unsupported.go
  pkg/util/iptables/monitor_test.go
  pkg/util/iptables/save_restore.go
  pkg/util/iptables/save_restore_test.go
  pkg/util/iptables/testing/fake.go
  pkg/yurthub/network/iptables.go
  pkg/yurttunnel/trafficforward/iptables/iptables.go
  pkg/yurttunnel/trafficforward/iptables/iptables_test.go
Labels: approved, lgtm, size/XXL

#632 declare a const instead the string
  pkg/yurtctl/util/kubernetes/apply_addons.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, kind/enhancement, lgtm, size/S

#635 The import package sort adjustment in the go file.
  cmd/yurt-node-servant/node-servant.go
  cmd/yurt-tunnel-agent/agent.go
  cmd/yurt-tunnel-agent/app/options/options.go
  cmd/yurt-tunnel-agent/app/start.go
  cmd/yurt-tunnel-server/app/options/options.go
  cmd/yurt-tunnel-server/app/start.go
  cmd/yurt-tunnel-server/server.go
Labels: approved, kind/enhancement, lgtm, size/M

#636 print error log when remote proxy is trapped into errorHandler
  pkg/yurthub/proxy/remote/remote.go
Labels: approved, kind/bug, lgtm, size/XS

#628 ci(master): ln hotfix to build in macOS
  hack/make-rules/build.sh
Labels: approved, lgtm, size/S, kind/feature

#639 deprecate kubelet certificate management mode
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurthub/certificate/kubelet/cert_mgr.go
  pkg/yurthub/certificate/kubelet/cert_mgr_test.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/util/util.go
Labels: approved, lgtm, size/L, kind/design

#620 fix node autonomy annotation key
  go.sum
  pkg/controller/util/node/controller_utils.go
  pkg/projectinfo/projectinfo.go
  pkg/yurtctl/constants/constants.go
Labels: approved, kind/enhancement, lgtm, size/M
