Repository openyurtio/openyurt, pull requests merged in 2021-06, with the labels that each got.

#332 Update slack invitation link
  README.md
  README.zh.md
Labels: approved, lgtm, size/XS

#336 Add parameter verification of specified cloud node.
  pkg/yurtctl/cmd/convert/convert.go
Labels: approved, kind/bug, lgtm, size/XS

#339 update Dingtalk QR code
  README.md
  README.zh.md
  docs/img/ding.jpeg
  docs/img/ding.jpg
Labels: approved, lgtm, size/XS

#354 add tolerations for yurt-tunnel-agent in order to avoid confict with nodepool taints
  config/setup/yurt-tunnel-agent.yaml
  config/yaml-template/yurt-tunnel-agent.yaml
Labels: approved, lgtm, size/XS

#342 Update doc
  docs/tutorial/yurt-app-manager-dev.md
Labels: approved, kind/documentation, lgtm, size/M

#352 New function development -- yurtctl adds parameter enable app manager to control automatic deployment of yurtappmanager.
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/constants/yurt-app-manager-tmpl.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, kind/feature, lgtm, size/XXL

#363 [REQUEST Membership]: update OWNERS file
  OWNERS
Labels: approved, lgtm

#349 change cache path from fixed to configurable parameter
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  pkg/yurthub/storage/disk/storage.go
  pkg/yurthub/storage/factory/factory.go
Labels: approved, kind/feature, lgtm, size/S
