Repository openyurtio/openyurt, pull requests merged in 2021-12, with the labels that each got.

#617 refactor: yurtctl convert use node-servant in dispatch job
  hack/local_up_openyurt.sh
  pkg/node-servant/convert/options.go
  pkg/yurtctl/cmd/convert/cloudnode.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/convert/edgenode.go
  pkg/yurtctl/cmd/convert/node.go
  pkg/yurtctl/cmd/markautonomous/markautonomous.go
  pkg/yurtctl/cmd/yurtinit/init.go
  pkg/yurtctl/cmd/yurtinit/phases/install_yurt_addons.go
  pkg/yurtctl/cmd/yurtinit/phases/label_cloud_node.go
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/constants/yurt-app-manager-tmpl.go
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
  pkg/yurtctl/util/kubernetes/apply_addons.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/XL, kind/feature

#642 The import package sort adjustment in the go file.
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  cmd/yurthub/yurthub.go
Labels: approved, kind/enhancement, lgtm, size/M

#649 use const instead the magical number
  pkg/yurttunnel/util/util.go
Labels: approved, kind/enhancement, lgtm, size/XS

#640 combine the yurthub's server and client certificate into one
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/certificate/pki.go
  pkg/yurthub/certificate/server/certmanager.go
  pkg/yurthub/server/server.go
Labels: approved, kind/enhancement, lgtm, size/L

#653 The import package sort adjustment in the go file.
  cmd/yurt-controller-manager/app/options/options.go
Labels: approved, kind/enhancement, lgtm, size/XS

#655 detect the openyurt version automatically
  hack/lib/init.sh
Labels: approved, lgtm, size/XS

#657 add some comments and adjust the order of some packages.
  hack/lib/release-images.sh
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/interfaces.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/network/dummyif_linux.go
  pkg/yurthub/proxy/remote/loadbalancer.go
Labels: approved, kind/enhancement, lgtm, size/M

#658 Note bug: changing edge nodes to cloud nodes
  pkg/yurtctl/cmd/revert/cloudnode.go
Labels: approved, lgtm, size/XS

#650 remove k8s.io/kubernetes dependency from e2e test
  test/e2e/common/ns/ns.go
  test/e2e/common/pod/pod.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/util/expect.go
  test/e2e/util/ginkgowrapper/wrapper.go
  test/e2e/util/util.go
  test/e2e/yurt/yurt.go
  test/e2e/yurtconfig/yurtconfig.go
  test/e2e/yurthub/yurthub.go
  test/e2e/yurttunnel/yurttunnel.go
Labels: approved, kind/enhancement, lgtm, size/XL

#660 Notebug:change -e to -c
  pkg/yurtctl/cmd/revert/cloudnode.go
Labels: approved, lgtm, size/XS

#644 Remove k8s.io/kubernetes dependency for yurt-controller-manager
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  cmd/yurt-controller-manager/app/options/generic.go
  cmd/yurt-controller-manager/app/options/nodelifecyclecontroller.go
  cmd/yurt-controller-manager/app/options/options.go
  go.mod
  go.sum
  pkg/controller/apis/config/types.go
  pkg/controller/kubernetes/client/leaderelectionconfig/config.go
  pkg/controller/kubernetes/cmd/controller-manager/app/helper.go
  pkg/controller/kubernetes/cmd/controller-manager/app/serve.go
  pkg/controller/kubernetes/controller/client_builder.go
  pkg/controller/kubernetes/controller/controller_utils.go
  pkg/controller/kubernetes/controller/testutil/test_utils.go
  pkg/controller/kubernetes/controller/util/node/controller_utils.go
  pkg/controller/kubernetes/features/kube_features.go
  pkg/controller/kubernetes/util/node/node.go
  pkg/controller/kubernetes/util/taints/taints.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/util/node/controller_utils.go
Labels: approved, lgtm, kind/feature, size/XXL

#661 split the yurthub certificate into server and client certificates
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/certificate/pki.go
  pkg/yurthub/certificate/server/certmanager.go
  pkg/yurthub/server/server.go
Labels: approved, kind/bug, lgtm, size/L

#665 ci(master): replace DOCKER_BUILD_BASE_IDR => DOCKER_BUILD_BASE_DIR
  hack/lib/release-manifest.sh
Labels: approved, kind/bug, lgtm, size/S

#662 ci(master): add golint makefile
  Makefile
  pkg/util/iptables/iptables_unsupported_test.go
Labels: approved, lgtm, size/M, kind/feature

#664 remove "k8s.io/kubernetes/pkg/controller/apis/config" dependency for yurt-controller-manager
  cmd/yurt-controller-manager/app/options/generic.go
  cmd/yurt-controller-manager/app/options/options.go
  pkg/controller/apis/config/types.go
  pkg/controller/kubernetes/controller/apis/config/types.go
Labels: approved, lgtm, size/M

#666 ci(master): replace ${binary_name} => $1
  hack/lib/common.sh
Labels: approved, kind/bug, lgtm, size/XS

#654 refactor: yurtctl revert use node-servant in dispatch job
  docs/tutorial/manually-setup.md
  docs/tutorial/yurtctl.md
  pkg/node-servant/components/kubelet.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/revert/cloudnode.go
  pkg/yurtctl/cmd/revert/edgenode.go
  pkg/yurtctl/cmd/revert/node.go
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/XL, kind/feature

#667 ci(master): doc coredns min version tips
  docs/tutorial/prometheus.md
Labels: approved, lgtm, size/XS

#669 The import package sort adjustment in the go file.
  test/e2e/common/node/ecs/ecs.go
  test/e2e/common/node/ens/ens.go
  test/e2e/common/node/user/user.go
Labels: approved, kind/enhancement, lgtm, size/XS

#670 add unit tests for yurthub data filtering framework
  pkg/yurthub/filter/approver_test.go
  pkg/yurthub/filter/discardcloudservice/handler_test.go
  pkg/yurthub/filter/masterservice/handler_test.go
  pkg/yurthub/filter/servicetopology/handler_test.go
Labels: approved, kind/good-first-issue, lgtm, kind/feature, size/XXL

#673 [enhancement] enable yurthub to handle upgrade request
  go.sum
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/proxy/util/util.go
Labels: approved, kind/enhancement, lgtm, size/M

#678 support of kubernetes v1.19 and v1.21
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, kind/enhancement, lgtm, size/XS

#679 docs: add RBAC instruction for patched flannel
  docs/tutorial/edge-pod-network.md
Labels: approved, kind/documentation, lgtm, size/M

#681 Remove k8s.io/kubernetes dependency for yurtctl
  go.mod
  go.sum
  pkg/util/kubeadmapi/kubeadmapi.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/L, kind/feature

#683 [bugfix] fix transport race conditions in yurthub
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/util/connrotation.go
Labels: approved, kind/bug, lgtm, size/M

#688 docs: update expired slack channel links
  README.md
  README.zh.md
Labels: approved, lgtm, size/XS

#645 ingress: update nodepool ingress proposal
  docs/proposals/20210628-nodepool-ingress-support.md
Labels: approved, lgtm, size/L

#686 node-servant: add preflight-convert command
  cmd/yurt-node-servant/convert/convert.go
  cmd/yurt-node-servant/node-servant.go
  cmd/yurt-node-servant/preflight-convert/preflight.go
  pkg/node-servant/components/kubelet.go
  pkg/node-servant/components/runtime.go
  pkg/node-servant/components/util.go
  pkg/node-servant/constant.go
  pkg/node-servant/convert/convert.go
  pkg/node-servant/convert/options.go
  pkg/node-servant/job.go
  pkg/node-servant/preflight-convert/options.go
  pkg/node-servant/preflight-convert/preflight.go
  pkg/node-servant/revert/revert.go
  pkg/preflight/checks.go
  pkg/preflight/constants.go
  pkg/preflight/interface.go
  pkg/yurtctl/util/edgenode/common.go
Labels: approved, lgtm, size/XL, kind/feature

#690 user can specifies the certificate directory
  cmd/yurt-tunnel-agent/app/config/config.go
  cmd/yurt-tunnel-agent/app/options/options.go
  cmd/yurt-tunnel-agent/app/start.go
  cmd/yurt-tunnel-server/app/config/config.go
  cmd/yurt-tunnel-server/app/options/options.go
  cmd/yurt-tunnel-server/app/start.go
  pkg/yurttunnel/pki/certmanager/certmanager.go
Labels: approved, lgtm, size/M

#637 Proposal: enhance cluster networking capabilities.
  docs/img/networking/img-1.png
  docs/img/networking/img-2.png
  docs/img/networking/img-3.png
  docs/proposals/20211123-enhancement-of-cluster-networking.md
Labels: approved, lgtm, size/L, kind/feature

#689 change default WaitServantJobTimeout && export param of WaitServantJo…
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/M

#692 Separator = replaced by cons
  pkg/yurttunnel/util/util.go
Labels: approved, lgtm, size/XS

#693 string var repaced by constant
  pkg/yurtctl/cmd/revert/revert.go
Labels: approved, lgtm, size/XS

#694 [CI Enhancement] Add gci linter check
  .github/workflows/ci.yaml
  .golangci.yaml
  Makefile
  cmd/yurt-controller-manager/controller-manager.go
  cmd/yurt-tunnel-agent/app/config/config.go
  cmd/yurt-tunnel-server/app/config/config.go
  cmd/yurthub/app/config/config.go
  pkg/controller/certificates/csrapprover.go
  pkg/controller/kubernetes/cmd/controller-manager/app/serve.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/join/phases/join-edge-node.go
  pkg/yurtctl/util/kubernetes/util.go
  pkg/yurthub/network/dummyif_linux.go
  pkg/yurttunnel/handlerwrapper/localhostproxy/handler.go
  pkg/yurttunnel/server/interceptor.go
  pkg/yurttunnel/server/serveraddr/addr.go
  pkg/yurttunnel/util/util.go
Labels: approved, kind/enhancement, lgtm, size/L

#695 port repaced by constant
  cmd/yurthub/app/options/options.go
  pkg/yurthub/util/util.go
Labels: approved, lgtm, size/S

#698 [bug] fix make lint bug
  Makefile
  hack/make-rules/check_license.sh
  pkg/util/iptables/iptables_linux.go
  pkg/util/iptables/iptables_test.go
  pkg/util/iptables/iptables_unsupported.go
  pkg/util/iptables/monitor_test.go
  pkg/yurthub/network/dummyif_test.go
  pkg/yurthub/network/dummyif_unsupported.go
Labels: approved, kind/bug, lgtm, size/S

#696 ingress: add nodepool endpoints filtering for nginx ingress controller
  cmd/yurthub/app/config/config.go
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/ingresscontroller/filter.go
  pkg/yurthub/filter/ingresscontroller/handler.go
Labels: approved, lgtm, size/L

#691 refactor: remove duplicate code about certmanager of yurthub and yurttunnel
  cmd/yurt-tunnel-agent/app/start.go
  cmd/yurt-tunnel-server/app/options/options.go
  cmd/yurt-tunnel-server/app/start.go
  pkg/util/certmanager/certmanager.go
  pkg/util/certmanager/pki.go
  pkg/util/certmanager/store/filestore_wrapper.go
  pkg/yurthub/certificate/pki.go
  pkg/yurthub/certificate/server/certmanager.go
  pkg/yurthub/server/server.go
Labels: approved, lgtm, size/L

#703 str replaced by const
  cmd/yurt-controller-manager/app/controllermanager.go
Labels: approved, lgtm, size/XS

#631 yurthub verify bootstrap ca on start
  pkg/yurthub/certificate/hubself/cert_mgr.go
Labels: approved, kind/bug, lgtm, size/M

#700 [docs] update arch pic
  docs/img/arch.png
Labels: approved, kind/documentation, lgtm, size/XS

#702 [feature]add stale config file
  .github/stale.yml
Labels: approved, lgtm, size/M, kind/feature
