Repository openyurtio/openyurt, pull requests merged in 2022-05, with the labels that each got.

#814 use constants instead the string
  pkg/yurttunnel/constants/constants.go
  pkg/yurttunnel/kubernetes/kubernetes.go
Labels: approved, lgtm, size/XS

#816 ingress: update edge ingress proposal to add enhancements
  docs/proposals/20210628-nodepool-ingress-support.md
Labels: approved, lgtm, size/M

#787 finish ut of sa token replacement
  .golangci.yaml
  Makefile
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/start.go
  go.mod
  go.sum
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/proxy/util/util_test.go
  pkg/yurthub/tenant/jwt/jwt_test.go
  pkg/yurthub/tenant/tenant.go
  pkg/yurthub/util/util.go
  pkg/yurthub/util/util_test.go
  test/integration/yurttunnel_test.go
Labels: approved, lgtm, size/XL

#822 add enable-node-pool parameter for yurthub in order to disable nodepools list/watch in filters when testing.
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
Labels: approved, kind/enhancement, lgtm, size/S

#826 Remove convert and revert command from yurtctl
  pkg/yurtctl/cmd/cmd.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/convert/options.go
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/kubernetes/kubeadm/app/phases/kubelet/flags_windows.go
Labels: approved, lgtm, kind/feature, size/XXL

#828 【ADD】Uniform use processCreateErr func to create resource
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/S

#829 【ADD】update node servant revert step
  pkg/node-servant/components/tunnel.go
  pkg/node-servant/revert/revert.go
Labels: approved, lgtm, size/M

#840 Update filter.go
  pkg/yurthub/filter/filter.go
Labels: approved, lgtm

#841 Remove docs to openyurt/openyurt.io/docs
  docs/developer-guide.md
  docs/resource-and-system-requirements-cn.md
  docs/resource-and-system-requirements.md
  docs/todo.md
  docs/tutorial/0001-flannel-keep-vtep-mac.patch
  docs/tutorial/0002-ipam-keep-pod-ip.patch
  docs/tutorial/README.md
  docs/tutorial/edge-pod-network.md
  docs/tutorial/manually-setup.md
  docs/tutorial/prometheus.md
  docs/tutorial/service-topology.md
  docs/tutorial/yurt-app-manager-dev.md
  docs/tutorial/yurt-app-manager.md
  docs/tutorial/yurt-e2e-test.md
  docs/tutorial/yurt-tunnel.md
  docs/tutorial/yurtctl.md
Labels: approved, kind/documentation, lgtm, size/XXL

#825 adjust to weekly meeting and revise slack link
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#843 [enhancement] add release workfolow for daily release and tag event.
  .github/workflows/release.yaml
  Makefile
Labels: approved, kind/documentation, lgtm, size/M

#847 [fix] revise backport workflow
  .github/workflows/back-port.yaml
Labels: approved, kind/enhancement, lgtm, size/S

#809 [feature] adapt k8s v1.22 version
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Makefile
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  cmd/yurt-controller-manager/controller-manager.go
  cmd/yurt-tunnel-server/app/start.go
  cmd/yurthub/app/start.go
  config/setup/yurt-controller-manager.yaml
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-controller-manager.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  go.mod
  go.sum
  hack/make-rules/local-up-openyurt.sh
  pkg/controller/certificates/csrapprover.go
  pkg/controller/certificates/csrapprover_test.go
  pkg/util/certmanager/certmanager.go
  pkg/util/certmanager/pki.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/constants/yurt-tunnel-server-tmpl.go
  pkg/yurtadm/util/kubernetes/apply_addons.go
  pkg/yurtadm/util/kubernetes/util.go
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/server/server.go
  pkg/yurttunnel/constants/constants.go
  pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
  pkg/yurttunnel/server/anpserver.go
  pkg/yurttunnel/server/server.go
  test/integration/yurttunnel_test.go
Labels: approved, lgtm, kind/feature, size/XXL

#834 【FIX】Update service topology for k8s 1.21 and unit test
  go.mod
  go.sum
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/filter/servicetopology/handler_test.go
Labels: approved, lgtm, size/XL

#842 support ipv6 network
  cmd/yurt-tunnel-agent/app/options/options.go
  cmd/yurt-tunnel-server/app/config/config.go
  cmd/yurt-tunnel-server/app/options/options.go
  cmd/yurt-tunnel-server/app/start.go
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/util/certmanager/certmanager.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
  pkg/yurthub/network/iptables.go
  pkg/yurthub/server/server.go
  pkg/yurttunnel/handlerwrapper/localhostproxy/handler.go
  pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
  pkg/yurttunnel/server/interceptor.go
  pkg/yurttunnel/server/serveraddr/addr.go
  pkg/yurttunnel/server/serveraddr/addr_test.go
  pkg/yurttunnel/trafficforward/iptables/iptables.go
Labels: approved, kind/enhancement, lgtm, size/L

#850 revise user in the rbac of tunnel-proxy-client
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-server.yaml
Labels: approved, kind/bug, lgtm, size/XS

#853 fix buildx arm64 error
  .github/workflows/release.yaml
  Makefile
Labels: approved, kind/bug, lgtm, size/M

#854 Fix: yurt-tunnel-server can not find conntrack executable
  hack/dockerfiles/Dockerfile.yurt-tunnel-server
Labels: approved, kind/bug, lgtm, size/XS

#860 revise docs for releasing OpenYurt v0.7.0
  CHANGELOG.md
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/L

#861 add roadmap for OpenYurt v0.8.0
  CHANGELOG.md
  docs/roadmap.md
Labels: approved, kind/documentation, size/M

#862 refactor of certmanager for general use
  cmd/yurt-tunnel-agent/app/start.go
  cmd/yurt-tunnel-server/app/start.go
  pkg/controller/certificates/csrapprover.go
  pkg/controller/certificates/csrapprover_test.go
  pkg/util/certmanager/certmanager.go
  pkg/util/certmanager/factory/factory.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/server/server.go
  pkg/yurttunnel/constants/constants.go
  pkg/yurttunnel/server/serveraddr/addr.go
Labels: approved, kind/enhancement, lgtm, size/XL
