Repository openyurtio/openyurt, pull requests merged in 2022-07, with the labels that each got.

#901 deprecate cert-mgr-mode option of yurthub
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurthub/certificate/certificate.go
  pkg/yurthub/certificate/certificate_test.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/util/util.go
Labels: approved, lgtm, size/L

#899 revise dingtalk QRCode
  README.md
  README.zh.md
  docs/img/ding.jpg
Labels: approved, kind/documentation, lgtm, size/XS

#905 openyurt chart and sync to repo
  .github/workflows/sync-charts.yaml
  charts/openyurt/Chart.yaml
  charts/openyurt/README.md
  charts/openyurt/templates/_helpers.tpl
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/templates/yurt-tunnel-agent.yaml
  charts/openyurt/templates/yurt-tunnel-server.yaml
  charts/openyurt/values.yaml
  hack/lib/sync-charts.sh
Labels: approved, lgtm, size/XL, kind/feature

#907 fix sync chart secret
  .github/workflows/sync-charts.yaml
  charts/openyurt/templates/yurt-tunnel-server.yaml
Labels: approved, kind/enhancement, size/XS, kind/feature

#903 restore flannel network patch
  docs/tutorial/0001-flannel-keep-vtep-mac.patch
  docs/tutorial/0002-ipam-keep-pod-ip.patch
Labels: approved, kind/documentation, lgtm, size/L

#910 add codecov token
  .github/workflows/ci.yaml
Labels: approved, kind/enhancement, size/XS

#911 remove build binaries in workflow and add codecov badge
  .github/workflows/ci.yaml
  README.md
  README.zh.md
Labels: approved, kind/enhancement, lgtm, size/S

#912 add luckymrwang as reviewer of OpenYurt
  OWNERS
Labels: approved, lgtm, size/XS

#904 fix-typos
  pkg/preflight/checks.go
  pkg/yurthub/kubernetes/meta/restmapper.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/transport/transport.go
Labels: approved, lgtm, size/S

#927 clean redundant lint in makefile
  Makefile
Labels: approved, lgtm, size/S

#922 CI fix: codecov failure
  pkg/yurthub/filter/masterservice/handler_test.go
Labels: approved, kind/bug, lgtm, size/S

#929 Add zzguang as approver of OpenYurt
  OWNERS
Labels: approved, lgtm, size/XS

#931 add unit tests for yurt-controller-manager
  go.mod
  pkg/controller/kubernetes/controller/testutil/test_utils.go
  pkg/controller/kubernetes/util/node/node.go
  pkg/controller/kubernetes/util/node/node_test.go
  pkg/controller/kubernetes/util/taints/taints_test.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#932 remove redundant sig storage label in pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/documentation, lgtm, size/XS

#934 allow codecov to tolerate coverage rate jitter
  .codecov.yml
Labels: approved, kind/enhancement, lgtm, size/XS
