Repository openyurtio/openyurt, pull requests merged in 2022-09, with the labels that each got.

#983 check ci repo
  .github/workflows/sync-charts.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#985 [enhancement] enable `yurtctl test init` to install cluster without default kindnet
  hack/make-rules/local-up-openyurt.sh
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  pkg/yurtctl/constants/openyurt-kindconfig-tmpl.go
Labels: approved, kind/enhancement, lgtm, size/M

#989 enhancement: complement openyurt helm charts
  charts/openyurt/Chart.yaml
  charts/openyurt/README.md
  charts/openyurt/templates/yurthub-cfg.yaml
Labels: approved, kind/enhancement, lgtm, size/M

#991 kubeadm join check download file exist
  pkg/yurtadm/util/kubernetes/util.go
Labels: approved, kind/enhancement, lgtm, size/S

#993 extend chart parmeters
  charts/openyurt/Chart.yaml
  charts/openyurt/templates/yurt-tunnel-agent.yaml
  charts/openyurt/templates/yurt-tunnel-server.yaml
  charts/openyurt/values.yaml
Labels: approved, kind/enhancement, lgtm, size/S

#995 [Fix] trim suffix new line when getting gopath
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator_test.go
Labels: approved, kind/bug, lgtm, size/S

#996 enable service topology filter for coredns in default setting
  charts/openyurt/templates/yurthub-cfg.yaml
  config/setup/yurthub-cfg.yaml
  config/yaml-template/yurthub-cfg.yaml
  pkg/yurtctl/constants/constants.go
  pkg/yurthub/filter/approver.go
Labels: approved, kind/enhancement, lgtm, size/S

#997 fix log level
  pkg/yurthub/filter/servicetopology/handler.go
Labels: approved, kind/enhancement, lgtm, size/XS

#998 revise changelog for v1.0
  CHANGELOG.md
Labels: approved, kind/documentation, lgtm, size/M

#1000 update yurtadm init
  pkg/yurtadm/cmd/yurtinit/init.go
  pkg/yurtadm/cmd/yurtinit/options.go
Labels: approved, kind/enhancement, lgtm, size/L

#1005 charts use 1.0.0 image
  charts/openyurt/Chart.yaml
  charts/openyurt/values.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#1007 update valid openyurt version of yurtctl test
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
Labels: approved, kind/bug, lgtm, size/S

#1002 gc error process
  pkg/yurthub/gc/gc.go
Labels: approved, kind/enhancement, lgtm, size/S

#1008 cache agent change optimize
  pkg/yurthub/cachemanager/cache_agent.go
  pkg/yurthub/cachemanager/cache_agent_test.go
Labels: approved, kind/enhancement, lgtm, size/S

#1011 feature: yurtadm join add yurthubserveraddr para
  pkg/node-servant/components/yurthub.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/cmd/join/phases/joinnode.go
  pkg/yurtadm/cmd/join/phases/postcheck.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/constants/join_options.go
  pkg/yurtadm/util/edgenode/common.go
Labels: approved, kind/enhancement, lgtm, size/S

#1015 Check if error via ListKeys of Storage Interface.
  pkg/yurthub/gc/gc.go
Labels: approved, kind/bug, lgtm, size/XS

#1006 [Proposal] make servicetopology filter work properly when service or nodepool
  docs/img/service-topology-endpoints-choose-nodepool-change.png
  docs/img/service-topology-nodepool-change.png
  docs/img/service-topology-service-change.png
  docs/proposals/20220910-enhancement-of-servicetopology.md
Labels: approved, lgtm, size/L

#1018 revise readme of Yurthub
  docs/img/yurthub.png
  pkg/yurthub/README.md
Labels: approved, kind/documentation, lgtm, size/S

#1016 Add released openyurt versions to projectInfo when building binaries
  hack/lib/common.sh
  pkg/projectinfo/projectinfo.go
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
Labels: approved, kind/enhancement, lgtm, size/L

#970 add auto pod upgrade controller for daemoset
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  go.mod
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller_test.go
  pkg/controller/daemonpodupdater/kubernetes/controller_utils.go
  pkg/controller/daemonpodupdater/kubernetes/controller_utils_test.go
  pkg/controller/daemonpodupdater/kubernetes/pod_util.go
  pkg/controller/daemonpodupdater/kubernetes/pod_util_test.go
  pkg/controller/daemonpodupdater/util.go
  pkg/controller/daemonpodupdater/util_test.go
Labels: approved, lgtm, size/XXL

#981 [Propalsal] propalsal to add edge-autonomy-e2e-tests
  docs/img/e2e-test-components.png
  docs/img/e2e-test-process.png
  docs/proposals/20220901-add-edge-autonomy-e2e-tests.md
Labels: approved, kind/documentation, size/M

#1013 revise proposal docs
  docs/proposals/202106120-edgex-integration.md
  docs/proposals/20210628-nodepool-ingress-support.md
Labels: approved, lgtm, size/L

#1021 set default maxUnavailable to 10%
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller_test.go
Labels: approved, lgtm, size/M

#1004 add ota update RESTful API
  pkg/yurthub/otaupdate/ota.go
  pkg/yurthub/otaupdate/ota_test.go
  pkg/yurthub/server/server.go
Labels: approved, lgtm, size/L
