Repository openyurtio/openyurt, pull requests merged in 2022-12, with the labels that each got.

#1089 add_join_test.go
  pkg/yurtadm/cmd/join/join_test.go
Labels: approved, lgtm, size/XL

#1088 Fix: fix dynamicRESTMapper nil pointer bug
  pkg/yurthub/kubernetes/meta/restmapper.go
Labels: approved, lgtm, size/XS

#1034 feat: add pool-coordinator chart
  charts/openyurt/README.md
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/values.yaml
Labels: size/L

#1040 add poolcoordinator controller and webhooks to replace nodelifecycle …
  charts/openyurt/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/role.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/openyurt/templates/admission-webhooks/mutatingwebhookconfiguration.yaml
  charts/openyurt/templates/admission-webhooks/validatingwebhookconfiguration.yaml
  charts/openyurt/templates/admission-webhooks/webhookService.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/values.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  go.mod
  go.sum
  pkg/controller/nodelifecycle/metrics.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/rate_limited_queue.go
  pkg/controller/nodelifecycle/scheduler/rate_limited_queue_test.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/nodelifecycle/scheduler/timed_workers_test.go
  pkg/controller/poolcoordinator/constant/constant.go
  pkg/controller/poolcoordinator/poolcoordinator_controller.go
  pkg/controller/poolcoordinator/utils/file.go
  pkg/controller/poolcoordinator/utils/lease.go
  pkg/controller/poolcoordinator/utils/lease_test.go
  pkg/controller/poolcoordinator/utils/nodepool.go
  pkg/controller/poolcoordinator/utils/nodepool_test.go
  pkg/controller/poolcoordinator/utils/taints.go
  pkg/controller/poolcoordinator/utils/tolerations.go
  pkg/webhook/poolcoordinator_webhook.go
  pkg/webhook/webhook.go
Labels: kind/feature, size/XXL

#1092 bugfix: add ignore preflight errors to adapt kubeadm before version 1.23.0
  pkg/yurtadm/constants/constants.go
Labels: approved, kind/bug, lgtm, size/XS

#1083 add poolcoordinator cert manager
  charts/openyurt/templates/yurt-controller-manager.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  pkg/controller/certificates/csrapprover.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
  pkg/controller/poolcoordinator/cert/util.go
  pkg/util/ip/ip.go
  pkg/yurtadm/util/kubeconfig/kubeconfig.go
Labels: size/XL, kind/feature

#1093 add_reset_test.go
  pkg/yurtadm/cmd/reset/reset_test.go
Labels: approved, lgtm, size/L

#1097 modify pool-coordinator yaml to remove kubectl container
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/values.yaml
Labels: approved, size/L, kind/feature

#1098 modify pool-coordinator secrets
  charts/openyurt/templates/pool-coordinator.yaml
Labels: approved, size/S

#1100 add_wraphandler_test.go
  pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler_test.go
Labels: approved, lgtm, size/L
