Repository openyurtio/openyurt, pull requests merged in 2022-10, with the labels that each got.

#1019 make servicetopology filter in yurthub work properly when service or nodepool change
  charts/openyurt/templates/yurt-controller-manager.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  pkg/controller/servicetopology/adapter/adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
  pkg/controller/servicetopology/servicetopology.go
  pkg/controller/servicetopology/servicetopology_test.go
  pkg/yurtctl/constants/constants.go
Labels: approved, lgtm, size/XXL

#1029 do not set host service topology in test cluster
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
Labels: approved, kind/bug, lgtm, size/S

#1028 bugfix: even no endpoints left after filter, an empty object should be returned to clients
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/filter/servicetopology/handler_test.go
Labels: approved, kind/bug, lgtm, size/XXL

#1025 improve data filter framework
  charts/openyurt/templates/yurthub-cfg.yaml
  cmd/yurthub/app/config/config.go
  pkg/yurtctl/constants/constants.go
  pkg/yurthub/filter/approver.go
  pkg/yurthub/filter/approver_test.go
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/discardcloudservice/filter.go
  pkg/yurthub/filter/filter.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/interfaces.go
  pkg/yurthub/filter/manager.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/manager/manager_test.go
  pkg/yurthub/filter/masterservice/filter.go
  pkg/yurthub/filter/masterservice/handler.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/proxy/remote/remote.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#1027 add proposal to unify cloud edge comms solution
  docs/img/raven-l7-option1.png
  docs/img/raven-l7.png
  docs/img/raven.png
  docs/img/yurttunnel.png
  docs/proposals/20220930-unifying-cloud-edge-comms.md
Labels: approved, lgtm, size/L

#1032 improve health checker for adapting coordinator
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurthub/healthchecker/fake_checker.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/healthchecker/health_checker_test.go
  pkg/yurthub/healthchecker/interfaces.go
  pkg/yurthub/healthchecker/node_lease.go
  pkg/yurthub/healthchecker/prober.go
  pkg/yurthub/healthchecker/prober_test.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/proxy/remote/loadbalancer_test.go
  pkg/yurthub/proxy/remote/remote.go
Labels: approved, lgtm, kind/feature, size/XXL

#1036 update roadmap for SIG controlplane
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/S

#1022 Edge-autonomy-e2e-test implementation
  .github/workflows/ci.yaml
  hack/lib/build.sh
  hack/make-rules/run-e2e-tests.sh
  test/e2e/autonomy/autonomy_test.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/util/util.go
  test/e2e/yamls/nginx.yaml
  test/e2e/yamls/nginxService.yaml
  test/e2e/yurt/yurt.go
  test/e2e/yurt/yurt_test.go
  test/e2e/yurtconfig/yurtconfig.go
  test/e2e/yurthub/yurthub.go
  test/e2e/yurttunnel/yurttunnel_test.go
Labels: approved, lgtm, size/XXL

#1042 Docs: replace guide link in README.md
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/XS
