Repository openyurtio/openyurt, pull requests merged in 2022-08, with the labels that each got.

#933 revise roadmap
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/M

#921 [Proposal] add proposal of daemosnet update model
  docs/img/OTA.png
  docs/img/process.png
  docs/img/xxx-controller.png
  docs/proposals/20220718-workload-update-model.md
Labels: approved, lgtm, size/L, kind/design

#941 add dingding community group2
  README.md
  README.zh.md
  docs/img/ding.jpg
Labels: approved, kind/documentation, lgtm, size/XS

#948 verify go mod in CI
  .github/workflows/ci.yaml
  Makefile
  hack/make-rules/verify_mod.sh
Labels: approved, lgtm, size/M

#936 fix: cache the server version info of kubernetes
  cmd/yurthub/app/start.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/server/nonresource.go
  pkg/yurthub/server/nonresource_test.go
  pkg/yurthub/server/server.go
Labels: approved, lgtm, size/L

#952 fix: get proper nodename from hostname in yurtadm
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/util/edgenode/util.go
  pkg/yurtadm/util/edgenode/util_test.go
Labels: approved, kind/bug, lgtm, size/L

#956 add yurt-tunnel-dns yaml
  config/setup/yurt-tunnel-dns.yaml
Labels: approved, kind/enhancement, lgtm, size/L

#950 post result to codecov only in openyurt repo
  .github/workflows/ci.yaml
Labels: kind/enhancement, size/XS

#959 Separate YurtHubHost & YurtHubProxyHost
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
Labels: approved, kind/enhancement, lgtm, size/M

#947 Yurtctl devfor ut
  pkg/yurtctl/cmd/yurttest/kindinit/converter.go
  pkg/yurtctl/cmd/yurttest/kindinit/converter_test.go
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator_test.go
  pkg/yurtctl/lock/lock.go
  pkg/yurtctl/lock/lock_test.go
  pkg/yurtctl/util/kubernetes/apply_addons.go
  pkg/yurtctl/util/kubernetes/apply_addons_test.go
  pkg/yurtctl/util/kubernetes/util.go
  pkg/yurtctl/util/kubernetes/util_test.go
Labels: approved, kind/enhancement, size/XXL

#960 fix issue 957
  pkg/yurthub/cachemanager/cache_manager_test.go
  pkg/yurthub/util/util.go
  pkg/yurthub/util/util_test.go
Labels: approved, lgtm, size/L

#961 Fix: fix tunnel dns settings
  config/setup/yurt-tunnel-dns.yaml
Labels: approved, kind/bug, lgtm, size/M

#963 merge endpoints filter into service topology filter
  cmd/yurthub/app/config/config.go
  pkg/yurthub/filter/approver.go
  pkg/yurthub/filter/approver_test.go
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/endpointsfilter/filter.go
  pkg/yurthub/filter/endpointsfilter/handler.go
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/filter/servicetopology/handler_test.go
Labels: approved, lgtm, kind/feature, size/XXL

#964 support yurtadm join to join multiple master nodes
  pkg/util/kubernetes/kubeadm/app/constants/constants.go
  pkg/util/kubernetes/kubeadm/app/discovery/token/token.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/phases/joinnode.go
  pkg/yurtadm/cmd/join/phases/preflight.go
  pkg/yurtadm/util/kubernetes/util.go
Labels: approved, kind/enhancement, lgtm, size/M

#965 feature: add lantency metrics for yurthub
  pkg/yurthub/metrics/metrics.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/proxy/util/util_test.go
Labels: approved, size/L, kind/feature

#945 bump ginkgo to v2
  go.mod
  go.sum
  test/e2e/common/node/user/user.go
  test/e2e/common/pod/pod.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/util/ginkgowrapper/wrapper.go
  test/e2e/util/util.go
  test/e2e/yurt/yurt.go
  test/e2e/yurthub/yurthub.go
  test/e2e/yurttunnel/yurttunnel.go
Labels: approved, lgtm, size/M

#969 beta.kubernetes.io is deprecated, use kubernetes.io instead
  charts/openyurt/templates/yurt-tunnel-agent.yaml
  charts/openyurt/templates/yurt-tunnel-server.yaml
  config/setup/yurt-tunnel-agent.yaml
  config/setup/yurt-tunnel-server.yaml
  config/yaml-template/yurt-tunnel-agent.yaml
  config/yaml-template/yurt-tunnel-server.yaml
  pkg/yurtctl/constants/yurt-app-manager-tmpl.go
  pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
Labels: approved, kind/bug, lgtm, size/S

#972 test: add test cases for yurthub
  pkg/yurthub/certificate/hubself/cert_mgr_test.go
  pkg/yurthub/transport/transport.go
  pkg/yurthub/util/connrotation.go
  pkg/yurthub/util/connrotation_test.go
  pkg/yurthub/util/util.go
  pkg/yurthub/util/util_test.go
Labels: approved, lgtm, size/XL

#906 download yurtadm shell
  hack/lib/download.sh
Labels: size/L, kind/feature

#973 add unit tests for yurt-tunnel
  pkg/yurttunnel/trafficforward/dns/dns.go
  pkg/yurttunnel/trafficforward/dns/dns_test.go
  pkg/yurttunnel/trafficforward/dns/handler.go
  pkg/yurttunnel/trafficforward/dns/handler_test.go
  pkg/yurttunnel/trafficforward/iptables/iptables.go
  pkg/yurttunnel/trafficforward/iptables/iptables_test.go
  pkg/yurttunnel/util/util.go
Labels: approved, lgtm, kind/feature, size/XXL

#930 <Proposal> Optimize the pods recovery efficiency when edge nodes restart proposal
  docs/img/kubelet-start.png
  docs/img/kubelet-step.png
  docs/img/pod-restart-step.png
  docs/img/yurthub-start-process-en.png
  docs/proposals/20220725-pod-recovery-efficiency-proposal.md
Labels: lgtm, size/L

#966 remove no track network setting for yurthub
  pkg/yurthub/network/iptables.go
Labels: approved, lgtm

#979 increate chart version
  charts/openyurt/Chart.yaml
Labels: approved, lgtm

#978 cleanup yurtappmanager deploy
  pkg/yurtctl/constants/yurt-app-manager-tmpl.go
  pkg/yurtctl/util/kubernetes/apply_addons.go
  pkg/yurtctl/util/kubernetes/util_test.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#980 update ubuntu-18.04 to ubuntu-20.04
  .github/workflows/release.yaml
Labels: approved, kind/enhancement, lgtm, size/XS
