Repository openyurtio/openyurt, pull requests merged in 2022-04, with the labels that each got.

#792 upgrade the golint ci step
  .github/workflows/ci.yaml
Labels: approved, lgtm, size/XS, kind/feature

#793 add configmap delete handler for approver
  pkg/yurthub/filter/approver.go
Labels: approved, lgtm, size/S, kind/feature

#791 support configmap delete
  pkg/yurthub/cachemanager/cache_agent.go
Labels: approved, lgtm, size/S, kind/feature

#781 upgrade webhook version
  pkg/yurtctl/constants/yurt-app-manager-tmpl.go
Labels: approved, lgtm

#712 [docs] revise roadmap for v0.7.0/v0.8.0
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/S

#799 just clean code
  pkg/util/certmanager/certmanager.go
  pkg/yurttunnel/trafficforward/iptables/iptables.go
Labels: approved, lgtm, size/M

#796 dns sync err process
  pkg/yurttunnel/trafficforward/dns/dns.go
  pkg/yurttunnel/trafficforward/dns/handler.go
Labels: approved, lgtm, size/S

#795 iptables error process
  pkg/yurthub/network/iptables.go
  pkg/yurthub/network/network.go
Labels: approved, kind/bug, lgtm, size/S

#798 fix spelling mistakes
  pkg/node-servant/revert/revert.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/convert/options.go
Labels: approved, lgtm, size/XS

#746 update slack link
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#772 add nodepool governance capability proposal
  docs/img/nodepool-governance/img-1.png
  docs/img/nodepool-governance/img-2.png
  docs/img/nodepool-governance/img-3.png
  docs/img/nodepool-governance/img-4.png
  docs/proposals/20220307-nodepool-governance-capability.md
Labels: approved, lgtm, size/L, kind/feature

#783 add `yurtctl test init` cmd to setup OpenYurt cluster with kind
  hack/kind-config-template.yaml
  hack/lib/release-images.sh
  hack/local_up_openyurt.sh
  pkg/yurtctl/cmd/cmd.go
  pkg/yurtctl/cmd/yurtinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/converter.go
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator_test.go
  pkg/yurtctl/cmd/yurttest/yurttest.go
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/constants/openyurt-kindconfig-tmpl.go
Labels: approved, lgtm, kind/feature, size/XXL

#740 add back port for github actions
  .github/workflows/back-port.yaml
Labels: approved, lgtm, size/S

#794 [bugfix] ungzip response by yurthub when response header contains content-encoding=gzip
  pkg/yurthub/filter/manager.go
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/util/util.go
Labels: approved, kind/bug, lgtm, size/M

#801 test prow
  .gitignore
Labels: approved, lgtm, size/XS

#807 [bug] fix git safe dir error
  hack/lib/release-images.sh
Labels: approved, kind/bug, lgtm, size/S

#805 【Optimize】unified image pull policy
  config/setup/yurthub.yaml
  config/yaml-template/yurthub.yaml
  pkg/yurtctl/constants/yurt-app-manager-tmpl.go
Labels: approved, lgtm, size/XS

#808 【Optimize】optimize kubernetes util function
  pkg/yurtctl/util/kubernetes/apply_addons.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, size/S

#806 【FIX】fix cloud node was heterogeneous
  pkg/yurtctl/constants/yurt-app-manager-tmpl.go
  pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
Labels: approved, lgtm, size/XS

#813 cleanup: io/ioutil
  pkg/node-servant/components/kubelet.go
  pkg/node-servant/components/yurthub.go
  pkg/util/certmanager/pki.go
  pkg/yurtctl/cmd/join/phases/joinnode.go
  pkg/yurtctl/cmd/join/phases/postcheck.go
  pkg/yurtctl/cmd/reset/phases/unmount_linux.go
  pkg/yurtctl/cmd/yurtinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  pkg/yurtctl/kubernetes/kubeadm/app/phases/kubelet/flags.go
  pkg/yurtctl/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig.go
  pkg/yurtctl/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig_test.go
  pkg/yurtctl/kubernetes/kubeadm/app/util/runtime/runtime_test.go
  pkg/yurtctl/util/edgenode/util.go
  pkg/yurtctl/util/kubernetes/util.go
  pkg/yurtctl/util/system/util.go
  pkg/yurthub/cachemanager/cache_manager_test.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/filter/discardcloudservice/handler_test.go
  pkg/yurthub/filter/masterservice/handler_test.go
  pkg/yurthub/storage/disk/storage.go
  pkg/yurthub/transport/transport.go
  pkg/yurthub/util/util_test.go
  pkg/yurttunnel/kubernetes/kubernetes.go
  test/integration/yurttunnel_test.go
Labels: approved, lgtm
