Repository openyurtio/openyurt, pull requests merged in 2022-01, with the labels that each got.

#704 refactor yurtctl init
  README.md
  README.zh.md
  docs/tutorial/yurtctl.md
  pkg/yurtctl/cmd/cmd.go
  pkg/yurtctl/cmd/yurtinit/init.go
  pkg/yurtctl/cmd/yurtinit/options.go
  pkg/yurtctl/cmd/yurtinit/phases/controlplane.go
  pkg/yurtctl/cmd/yurtinit/phases/install_cni.go
  pkg/yurtctl/cmd/yurtinit/phases/install_yurt_addons.go
  pkg/yurtctl/cmd/yurtinit/phases/label_cloud_node.go
  pkg/yurtctl/cmd/yurtinit/phases/prepare.go
  pkg/yurtctl/cmd/yurtinit/phases/types.go
Labels: approved, lgtm, kind/feature, size/XXL

#708 Fix namespace
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurtctl/constants/constants.go
Labels: approved, lgtm, size/S

#705 [feature] adapt k8s v1.20 version
  .github/workflows/ci.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  cmd/yurt-controller-manager/app/options/debugging.go
  cmd/yurt-controller-manager/app/options/generic.go
  cmd/yurt-controller-manager/app/options/options.go
  cmd/yurt-controller-manager/controller-manager.go
  go.mod
  go.sum
  hack/lib/release-images.sh
  pkg/controller/apis/config/types.go
  pkg/controller/certificates/csrapprover.go
  pkg/controller/certificates/csrapprover_test.go
  pkg/controller/kubernetes/client/leaderelectionconfig/config.go
  pkg/controller/kubernetes/cmd/controller-manager/app/helper.go
  pkg/controller/kubernetes/cmd/controller-manager/app/serve.go
  pkg/controller/kubernetes/controller/apis/config/types.go
  pkg/controller/kubernetes/controller/client_builder.go
  pkg/controller/kubernetes/controller/controller_utils.go
  pkg/controller/kubernetes/controller/testutil/test_utils.go
  pkg/controller/kubernetes/features/kube_features.go
  pkg/controller/kubernetes/util/node/node.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/BUILD
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/util/certmanager/certmanager.go
  pkg/yurtctl/cmd/convert/options.go
  pkg/yurtctl/util/kubernetes/util.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/kubernetes/meta/restmapper.go
Labels: approved, lgtm, kind/feature, size/XXL

#709 [docs] revise readme and changelog for OpenYurt v0.6.0
  CHANGELOG.md
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/L

#710 Revise README.md
  README.md
Labels: approved, kind/documentation, lgtm, size/S

#711 [docs] revise README.zh.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/S

#716 replaced zone by const
  pkg/controller/nodelifecycle/metrics.go
Labels: approved, lgtm, size/XS

#717 0755 dirmode replaced by Const
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm

#718 string var repalced by const
  pkg/yurtctl/util/edgenode/util.go
Labels: approved, lgtm, size/XS

#719 fix dirmod replaced by Const
  pkg/yurtctl/cmd/yurtinit/init.go
Labels: approved, lgtm, size/XS

#721 Update start.go
  cmd/yurt-tunnel-server/app/start.go
Labels: approved, lgtm, size/XS

#723 add zzguang as reviewer of OpenYurt
  OWNERS
Labels: approved, lgtm, size/XS

#724 bugfix: panic happened when x-tunnel-server-svc service type is lb
  pkg/yurttunnel/server/serveraddr/addr.go
Labels: approved, kind/bug, lgtm, size/XS

#726 add Congrool as reviewer of OpenYurt
  OWNERS
Labels: approved, lgtm, size/XS

#725 enhancement: tunnel-server supports to proxy requests that access tunnel-server directly with specified destination
  pkg/util/certmanager/certmanager.go
  pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
Labels: approved, kind/enhancement, lgtm, size/S

#727 cache-agent for yurthub support '*'
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/cachemanager/cache_manager_test.go
Labels: approved, lgtm, size/M

#728 [bug] add NoArgs check for cmds
  cmd/yurt-node-servant/convert/convert.go
  cmd/yurt-node-servant/preflight-convert/preflight.go
  cmd/yurt-node-servant/revert/revert.go
  cmd/yurt-tunnel-agent/app/start.go
  cmd/yurt-tunnel-server/app/start.go
  pkg/node-servant/constant.go
  pkg/yurtctl/cmd/clusterinfo/clusterinfo.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/markautonomous/markautonomous.go
  pkg/yurtctl/cmd/revert/revert.go
Labels: approved, kind/bug, lgtm, size/S
