Repository openyurtio/openyurt, pull requests merged in 2022-11, with the labels that each got.

#1044 bugfix: non resource handle miss for coredns
  pkg/yurthub/certificate/hubself/fake_cert_mgr.go
  pkg/yurthub/server/certificate_test.go
  pkg/yurthub/server/nonresource.go
  pkg/yurthub/server/nonresource_test.go
  pkg/yurthub/server/server.go
Labels: approved, kind/bug, lgtm, size/L

#1045 improve e2e tests for supporting mac env and coredns autonomy
  Makefile
  hack/make-rules/run-e2e-tests.sh
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  test/e2e/autonomy/autonomy_test.go
Labels: approved, kind/enhancement, lgtm, size/L

#897 proposal of yurthub cache refactoring
  docs/img/yurthub-cache-refactoring/arch.jpg
  docs/proposals/20220627-yurthub-cache-refactoring.md
Labels: approved, kind/documentation, sig/storage, lgtm, size/L, kind/design

#1046 add release note and changeLog for OpenYurt v1.1.0
  CHANGELOG.md
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/M

#1047 update helm charts for OpenYurt v1.1.0
  CHANGELOG.md
  charts/openyurt/Chart.yaml
  charts/openyurt/values.yaml
Labels: approved, kind/documentation, lgtm, size/S

#1048 proposal of yurtadm join refactoring
  docs/proposals/20221108-yurtadm-join-refactoring.md
Labels: approved, lgtm, size/L

#1052 Extend timeout for coredns autonomy test
  test/e2e/autonomy/autonomy_test.go
Labels: approved, lgtm, size/XS

#1051 [Proposal] edgex auto-collector proposal
  docs/img/edgex-auto-collector/auto-collector-process.png
  docs/img/edgex-auto-collector/edgex-collector.png
  docs/img/edgex-auto-collector/edgex-compose.png
  docs/img/edgex-auto-collector/security-switch.png
  docs/img/edgex-auto-collector/verifying-test.png
  docs/proposals/20221109-edgex-auto-collector.md
Labels: approved, lgtm, size/L, kind/design

#1035 add yurthub leader election and coordinator framework
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/yurthub/healthchecker/fake_checker.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/healthchecker/health_checker_test.go
  pkg/yurthub/healthchecker/interfaces.go
  pkg/yurthub/healthchecker/node_lease.go
  pkg/yurthub/healthchecker/prober.go
  pkg/yurthub/healthchecker/prober_test.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/poolcoordinator/leader_election.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/proxy/remote/loadbalancer_test.go
  pkg/yurthub/proxy/remote/remote.go
Labels: approved, lgtm, size/XXL

#1057 Modify some details in the edgex auto-collector proposal
  docs/img/edgex-auto-collector/security switch.png
  docs/img/edgex-auto-collector/security-switch.png
  docs/proposals/20221109-edgex-auto-collector.md
Labels: approved, sig/iot, lgtm, size/XS, kind/design

#1056 add timeout config in yurthub to handle those watch requests without …
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/local/local_test.go
  pkg/yurthub/proxy/proxy.go
Labels: approved, kind/enhancement, lgtm, size/L

#1060 retry deleting test ns after reconnecting cloud node
  test/e2e/autonomy/autonomy_test.go
  test/e2e/common/ns/ns.go
Labels: approved, lgtm, size/S

#1049 refactor yurtadm join
  go.mod
  go.sum
  pkg/node-servant/components/kubelet.go
  pkg/node-servant/components/yurthub.go
  pkg/node-servant/convert/options.go
  pkg/node-servant/revert/options.go
  pkg/preflight/checks.go
  pkg/util/kubernetes/kubeadm/app/constants/constants_unix.go
  pkg/util/kubernetes/kubeadm/app/phases/kubelet/flags.go
  pkg/util/kubernetes/kubeadm/app/phases/kubelet/kubelet.go
  pkg/util/kubernetes/kubeadm/app/preflight/checks.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/idempotency.go
  pkg/util/kubernetes/kubeadm/app/util/arguments.go
  pkg/util/kubernetes/kubeadm/app/util/initsystem/initsystem_unix.go
  pkg/util/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig.go
  pkg/util/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig_test.go
  pkg/util/kubernetes/kubeadm/app/util/runtime/runtime_unix.go
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/phases/joinnode.go
  pkg/yurtadm/cmd/join/phases/postcheck.go
  pkg/yurtadm/cmd/join/phases/preflight.go
  pkg/yurtadm/cmd/join/phases/prepare.go
  pkg/yurtadm/cmd/reset/phases/cleanyurtfile.go
  pkg/yurtadm/cmd/token/token.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/edgenode/common.go
  pkg/yurtadm/util/edgenode/edgenode.go
  pkg/yurtadm/util/edgenode/edgenode_test.go
  pkg/yurtadm/util/kubeconfig/kubeconfig.go
  pkg/yurtadm/util/kubeconfig/kubeconfig_test.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
  pkg/yurtadm/util/pubkeypin/pubkeypin.go
  pkg/yurtadm/util/pubkeypin/pubkeypin_test.go
  pkg/yurtadm/util/system/system.go
  pkg/yurtadm/util/token/token.go
Labels: approved, lgtm, size/XXL

#1062 expose helm values for yurthub cacheagents
  charts/openyurt/Chart.yaml
  charts/openyurt/templates/yurthub-cfg.yaml
  charts/openyurt/values.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#1063 wait for a moment before start to clean up yurt-e2e-test namespace
  test/e2e/autonomy/autonomy_test.go
Labels: approved, kind/bug, lgtm, size/S

#1066 bugfix: StreamResponseFilter of data filter framework can't work if size of one object is over 32KB
  pkg/yurthub/filter/discardcloudservice/filter.go
  pkg/yurthub/filter/discardcloudservice/handler.go
  pkg/yurthub/filter/discardcloudservice/handler_test.go
  pkg/yurthub/filter/filter.go
  pkg/yurthub/filter/filter_test.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/interfaces.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/masterservice/filter.go
  pkg/yurthub/filter/masterservice/handler.go
  pkg/yurthub/filter/masterservice/handler_test.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/filter/servicetopology/handler_test.go
  pkg/yurthub/filter/util/utils.go
Labels: approved, kind/bug, lgtm, size/XXL

#882 refactor yurthub cache to adapt different storages
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/start.go
  pkg/yurthub/cachemanager/cache_agent.go
  pkg/yurthub/cachemanager/cache_agent_test.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/cachemanager/cache_manager_test.go
  pkg/yurthub/cachemanager/storage_wrapper.go
  pkg/yurthub/cachemanager/storage_wrapper_test.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/certificate/hubself/cert_mgr_test.go
  pkg/yurthub/certificate/hubself/fake_cert_mgr.go
  pkg/yurthub/filter/manager/manager_test.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/gc/gc.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/healthchecker/node_lease.go
  pkg/yurthub/healthchecker/node_lease_test.go
  pkg/yurthub/kubernetes/meta/restmapper.go
  pkg/yurthub/kubernetes/meta/restmapper_test.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/otaupdate/ota.go
  pkg/yurthub/otaupdate/ota_test.go
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/local/local_test.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/remote.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/proxy/util/util_test.go
  pkg/yurthub/server/nonresource.go
  pkg/yurthub/server/nonresource_test.go
  pkg/yurthub/storage/disk/key.go
  pkg/yurthub/storage/disk/key_test.go
  pkg/yurthub/storage/disk/storage.go
  pkg/yurthub/storage/disk/storage_test.go
  pkg/yurthub/storage/errors.go
  pkg/yurthub/storage/key.go
  pkg/yurthub/storage/store.go
  pkg/yurthub/storage/utils/validate.go
  pkg/yurthub/util/fs/errors.go
  pkg/yurthub/util/fs/store.go
  pkg/yurthub/util/fs/store_test.go
  pkg/yurthub/util/util.go
  pkg/yurthub/util/util_test.go
Labels: approved, kind/enhancement, sig/storage, lgtm, size/XXL

#1069 add_pki_test.go
  pkg/util/certmanager/pki_test.go
Labels: approved, lgtm, size/L

#1072 extend timeout to 2min when reconnecting cloud node after suite
  test/e2e/autonomy/autonomy_test.go
Labels: approved, lgtm, size/XS

#1071 add_filestore_wrapper_test.go
  pkg/util/certmanager/store/filestore_wrapper_test.go
Labels: approved, lgtm, size/L

#1065 add proposal of static pod upgrade model
  docs/img/static-pod/auto.png
  docs/img/static-pod/process.png
  docs/proposals/20221115-static-pod-upgrade-model.md
Labels: approved, lgtm, size/L

#1070 add_factory_test.go
  pkg/util/certmanager/factory/factory_test.go
Labels: approved, lgtm, size/L

#1075 refactor yurtadm reset
  go.mod
  go.sum
  pkg/util/kubernetes/kubeadm/app/apis/kubeadm/types.go
  pkg/util/kubernetes/kubeadm/app/cmd/options/constant.go
  pkg/util/kubernetes/kubeadm/app/cmd/phases/workflow/phase.go
  pkg/util/kubernetes/kubeadm/app/cmd/phases/workflow/runner.go
  pkg/util/kubernetes/kubeadm/app/cmd/phases/workflow/runner_test.go
  pkg/util/kubernetes/kubeadm/app/constants/constants.go
  pkg/util/kubernetes/kubeadm/app/constants/constants_unix.go
  pkg/util/kubernetes/kubeadm/app/constants/constants_windows.go
  pkg/util/kubernetes/kubeadm/app/features/features.go
  pkg/util/kubernetes/kubeadm/app/features/features_test.go
  pkg/util/kubernetes/kubeadm/app/phases/kubelet/kubelet.go
  pkg/util/kubernetes/kubeadm/app/preflight/checks.go
  pkg/util/kubernetes/kubeadm/app/preflight/checks_unix.go
  pkg/util/kubernetes/kubeadm/app/preflight/checks_windows.go
  pkg/util/kubernetes/kubeadm/app/preflight/utils.go
  pkg/util/kubernetes/kubeadm/app/preflight/utils_test.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/idempotency.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/idempotency_test.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/wait.go
  pkg/util/kubernetes/kubeadm/app/util/arguments.go
  pkg/util/kubernetes/kubeadm/app/util/initsystem/initsystem.go
  pkg/util/kubernetes/kubeadm/app/util/initsystem/initsystem_unix.go
  pkg/util/kubernetes/kubeadm/app/util/initsystem/initsystem_windows.go
  pkg/util/kubernetes/kubeadm/app/util/runtime/runtime.go
  pkg/util/kubernetes/kubeadm/app/util/runtime/runtime_test.go
  pkg/util/kubernetes/kubelet/apis/config/register.go
  pkg/util/kubernetes/kubelet/apis/config/scheme/scheme.go
  pkg/util/kubernetes/kubelet/apis/config/types.go
  pkg/util/kubernetes/kubelet/apis/config/v1beta1/defaults.go
  pkg/util/kubernetes/kubelet/apis/config/v1beta1/defaults_linux.go
  pkg/util/kubernetes/kubelet/apis/config/v1beta1/defaults_others.go
  pkg/util/kubernetes/kubelet/apis/config/v1beta1/register.go
  pkg/util/kubernetes/kubelet/apis/config/v1beta1/zz_generated.conversion.go
  pkg/util/kubernetes/kubelet/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/util/kubernetes/kubelet/apis/config/v1beta1/zz_generated.defaults.go
  pkg/util/kubernetes/kubelet/apis/config/zz_generated.deepcopy.go
  pkg/util/kubernetes/kubelet/kubeletconfig/util/codec/codec.go
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/phases/postcheck.go
  pkg/yurtadm/cmd/reset/phases/cleanupnode.go
  pkg/yurtadm/cmd/reset/phases/cleanyurtfile.go
  pkg/yurtadm/cmd/reset/phases/data.go
  pkg/yurtadm/cmd/reset/phases/preflight.go
  pkg/yurtadm/cmd/reset/phases/resetnode.go
  pkg/yurtadm/cmd/reset/phases/unmount.go
  pkg/yurtadm/cmd/reset/phases/unmount_linux.go
  pkg/yurtadm/cmd/reset/reset.go
  pkg/yurtadm/cmd/reset/resetdata/data.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/constants/join_options.go
  pkg/yurtadm/util/initsystem/initsystem.go
  pkg/yurtadm/util/initsystem/initsystem_unix.go
  pkg/yurtadm/util/initsystem/initsystem_windows.go
Labels: approved, lgtm, kind/feature, size/XXL

#1074 revise roadmap
  docs/roadmap.md
Labels: approved, lgtm

#1081 revise roadmap
  docs/roadmap.md
Labels: approved, lgtm, size/S

#1077 fix: unknown object type "nil" in yurthub-cfg.yaml
  charts/openyurt/templates/yurthub-cfg.yaml
Labels: approved, lgtm, size/XS

#1082 add_util_test.go
  pkg/util/strings/util_test.go
Labels: approved, lgtm, size/M

#1078 add_fake_test.go
  pkg/util/iptables/testing/fake_test.go
Labels: approved, lgtm, size/XL
