Repository openyurtio/openyurt, pull requests merged in 2022-06, with the labels that each got.

#863 check yurthub parameter exist when exec yurtadm join
  pkg/yurtadm/util/edgenode/common.go
Labels: approved, kind/bug, lgtm, size/XS

#865 output processing info to stdout at real time
  pkg/yurtctl/cmd/cmd.go
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
  pkg/yurtctl/cmd/yurttest/kindinit/kindoperator_test.go
  pkg/yurtctl/cmd/yurttest/yurttest.go
Labels: approved, kind/enhancement, lgtm, size/M

#864 upgrade kubeadm to 1.22
  pkg/util/kubernetes/kubeadm/app/apis/bootstraptoken/v1/types.go
  pkg/util/kubernetes/kubeadm/app/apis/bootstraptoken/v1/utils.go
  pkg/util/kubernetes/kubeadm/app/apis/bootstraptoken/v1/utils_test.go
  pkg/util/kubernetes/kubeadm/app/apis/bootstraptoken/v1/zz_generated.deepcopy.go
  pkg/util/kubernetes/kubeadm/app/apis/kubeadm/bootstraptokenstring.go
  pkg/util/kubernetes/kubeadm/app/apis/kubeadm/types.go
  pkg/util/kubernetes/kubeadm/app/cmd/options/constant.go
  pkg/util/kubernetes/kubeadm/app/cmd/phases/workflow/runner.go
  pkg/util/kubernetes/kubeadm/app/constants/constants.go
  pkg/util/kubernetes/kubeadm/app/constants/constants_unix.go
  pkg/util/kubernetes/kubeadm/app/constants/constants_windows.go
  pkg/util/kubernetes/kubeadm/app/discovery/token/token.go
  pkg/util/kubernetes/kubeadm/app/features/features.go
  pkg/util/kubernetes/kubeadm/app/features/features_test.go
  pkg/util/kubernetes/kubeadm/app/phases/bootstraptoken/clusterinfo/clusterinfo.go
  pkg/util/kubernetes/kubeadm/app/phases/bootstraptoken/node/token.go
  pkg/util/kubernetes/kubeadm/app/phases/kubelet/flags.go
  pkg/util/kubernetes/kubeadm/app/phases/kubelet/flags_test.go
  pkg/util/kubernetes/kubeadm/app/phases/kubelet/flags_unix.go
  pkg/util/kubernetes/kubeadm/app/phases/kubelet/flags_windows.go
  pkg/util/kubernetes/kubeadm/app/preflight/checks.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/idempotency.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/tryidempotency.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/wait.go
  pkg/util/kubernetes/kubeadm/app/util/cgroupdriver.go
  pkg/util/kubernetes/kubeadm/app/util/initsystem/initsystem_unix.go
  pkg/util/kubernetes/kubeadm/app/util/initsystem/initsystem_windows.go
  pkg/util/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig.go
  pkg/util/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig_test.go
  pkg/util/kubernetes/kubeadm/app/util/pubkeypin/pubkeypin.go
  pkg/util/kubernetes/kubeadm/app/util/pubkeypin/pubkeypin_test.go
  pkg/util/kubernetes/kubeadm/app/util/runtime/runtime.go
  pkg/util/kubernetes/kubeadm/app/util/runtime/runtime_test.go
  pkg/util/kubernetes/kubeadm/app/util/runtime/runtime_unix.go
  pkg/util/kubernetes/kubeadm/app/util/runtime/runtime_windows.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/phases/preflight.go
  pkg/yurtadm/constants/join_options.go
  pkg/yurtctl/util/kubernetes/util.go
Labels: approved, lgtm, kind/feature, size/XXL

#873 cleanup openyurt shell
  hack/lib/common.sh
  hack/make-rules/build.sh
Labels: approved, kind/enhancement, lgtm, size/S

#875 support yurtadm token subcommand
  go.mod
  go.sum
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/token/token.go
Labels: approved, lgtm, size/L, kind/feature

#877 bugfix: only set signer name when not nil in order to prevent panic.
  pkg/controller/certificates/csrapprover.go
Labels: approved, kind/bug, lgtm, size/S

#878 fix approver unit test miss
  pkg/yurthub/filter/approver_test.go
Labels: approved, kind/enhancement, size/L

#881 add proxy to docker build-arg in case of proxy env
  Makefile
Labels: approved, kind/bug, lgtm, size/XS

#884 fix Makefile miss
  Makefile
Labels: approved, kind/enhancement, lgtm, size/S

#888 update slack link
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#868 yurthub return fake token when edge node disconnected with K8s APIServer
  go.mod
  go.sum
  pkg/yurthub/proxy/local/faketoken.go
  pkg/yurthub/proxy/proxy.go
Labels: approved, lgtm, size/L

#892 docker release ci only execute on openyurt repo
  .github/workflows/release.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#894 Update tracereq.go
  pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
Labels: approved, lgtm, size/XS

#885 Docs: Update Readme to the Requirements Reference
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/XS
