Repository openyurtio/openyurt, pull requests merged in 2022-02, with the labels that each got.

#733 fix: not initialized `sets.String` cause panic
  pkg/yurtctl/cmd/join/join.go
Labels: approved, kind/bug, lgtm, size/XS

#739 【backport】Release v0.6.1
  cmd/yurt-node-servant/convert/convert.go
  cmd/yurt-node-servant/preflight-convert/preflight.go
  cmd/yurt-node-servant/revert/revert.go
  cmd/yurt-tunnel-agent/app/start.go
  cmd/yurt-tunnel-server/app/start.go
  pkg/node-servant/constant.go
  pkg/util/certmanager/certmanager.go
  pkg/yurtctl/cmd/clusterinfo/clusterinfo.go
  pkg/yurtctl/cmd/convert/convert.go
  pkg/yurtctl/cmd/join/join.go
  pkg/yurtctl/cmd/markautonomous/markautonomous.go
  pkg/yurtctl/cmd/revert/revert.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/cachemanager/cache_manager_test.go
  pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
  pkg/yurttunnel/server/serveraddr/addr.go
Labels: approved, kind/enhancement, lgtm, size/M

#743 update sealer version to render yaml with env variables
  pkg/yurtctl/cmd/yurtinit/init.go
Labels: approved, kind/enhancement, lgtm, size/S

#747 Use camel case instead of snake case
  pkg/yurtctl/cmd/reset/phases/cleanyurtfile.go
  pkg/yurtctl/constants/constants.go
  pkg/yurtctl/util/system/util.go
Labels: approved, lgtm, size/XS
