Repository openyurtio/openyurt, pull requests merged in 2023-05, with the labels that each got.

#1425 revise readme and changeLog for v1.3
  CHANGELOG.md
  README.md
  README.zh.md
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/templates/yurthub-staticpod.yaml
  charts/openyurt/values.yaml
  docs/img/arch.png
  docs/img/ding.jpg
  pkg/controller/controller.go
  pkg/controller/raven/common.go
Labels: approved, kind/documentation, lgtm, size/L

#1429 fix misses in yurt-manager
  charts/openyurt/templates/yurt-manager.yaml
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/generic.go
  cmd/yurt-manager/app/options/staticpodcontroller.go
  go.mod
  go.sum
  pkg/controller/apis/config/types.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/controller/nodepool/nodepool_controller.go
  pkg/controller/poolcoordinator/delegatelease/delegatelease_controller.go
  pkg/controller/poolcoordinator/podbinding/podbinding_controller.go
  pkg/controller/raven/gateway/gateway_controller.go
  pkg/controller/raven/service/service_controller.go
  pkg/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/controller/servicetopology/endpoints/endpoints_enqueue_handlers.go
  pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
  pkg/controller/servicetopology/endpointslice/endpointslice_enqueue_handlers.go
  pkg/controller/servicetopology/util/util.go
  pkg/controller/staticpod/staticpod_controller.go
  pkg/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/controller/yurtappset/yurtappset_controller.go
  pkg/webhook/builder/webhook.go
  pkg/webhook/pod/v1/pod_handler.go
  pkg/webhook/server.go
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/health/handler.go
  pkg/webhook/util/util.go
  test/e2e/cmd/init/constants/constants.go
Labels: approved, kind/enhancement, lgtm, size/XL

#1437 improve service topology by using inject funcs
  pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
Labels: approved, kind/enhancement, lgtm, size/L

#1436 improve charts of openyurt
  Makefile
  charts/README.md
  charts/openyurt/README.md
  charts/openyurt/templates/_helpers.tpl
  charts/openyurt/values.yaml
  charts/pool-coordinator/.helmignore
  charts/pool-coordinator/Chart.yaml
  charts/pool-coordinator/templates/_helpers.tpl
  charts/pool-coordinator/templates/pool-coordinator.yaml
  charts/pool-coordinator/values.yaml
  charts/yurt-manager/.helmignore
  charts/yurt-manager/Chart.yaml
  charts/yurt-manager/crds/apps.openyurt.io_nodepools.yaml
  charts/yurt-manager/crds/apps.openyurt.io_staticpods.yaml
  charts/yurt-manager/crds/apps.openyurt.io_yurtappdaemons.yaml
  charts/yurt-manager/crds/apps.openyurt.io_yurtappsets.yaml
  charts/yurt-manager/crds/raven.openyurt.io_gateways.yaml
  charts/yurt-manager/templates/_helpers.tpl
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  charts/yurt-manager/templates/yurt-manager.yaml
  charts/yurt-manager/values.yaml
  charts/yurthub/.helmignore
  charts/yurthub/Chart.yaml
  charts/yurthub/templates/_helpers.tpl
  charts/yurthub/templates/yurthub-cfg.yaml
  charts/yurthub/templates/yurthub-staticpod.yaml
  charts/yurthub/values.yaml
  hack/lib/sync-charts.sh
  hack/make-rules/kustomize_to_chart.sh
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/yurthub/yurthub.go
  test/e2e/cmd/init/converter.go
Labels: approved, kind/enhancement, lgtm, size/XL

#1442 fix: raven-controller-manager supports calico
  pkg/apis/addtoscheme_raven_v1alpha1.go
Labels: approved, kind/bug, lgtm, size/XS

#1422 optimize staticpod controller for upgrade info
  pkg/controller/staticpod/config/types.go
  pkg/controller/staticpod/staticpod_controller.go
  pkg/controller/staticpod/upgradeinfo/upgrade_info.go
  pkg/controller/staticpod/upgradeinfo/upgrade_info_test.go
Labels: approved, kind/enhancement, lgtm, size/L

#1447 improve yurtadm join for keeping consistency with v1.2
  charts/yurt-manager/values.yaml
  charts/yurthub/templates/yurthub-staticpod.yaml
  charts/yurthub/values.yaml
  cmd/yurt-manager/app/manager.go
  pkg/node-servant/components/yurthub.go
  pkg/profile/profile.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/yurthub/yurthub.go
Labels: approved, lgtm, size/M

#1451 rename auto to AdvancedRollingUpdate
  charts/yurt-manager/crds/apps.openyurt.io_staticpods.yaml
  pkg/apis/apps/v1alpha1/default.go
  pkg/apis/apps/v1alpha1/staticpod_types.go
  pkg/controller/staticpod/staticpod_controller.go
  pkg/controller/staticpod/staticpod_controller_test.go
  pkg/controller/staticpod/upgradeinfo/upgrade_info.go
  pkg/controller/staticpod/util/util.go
  pkg/webhook/staticpod/v1alpha1/staticpod_validation.go
Labels: approved, lgtm, size/M

#1452 rename auto to AdvancedRollingUpdate
  docs/proposals/20221115-static-pod-upgrade-model.md
Labels: approved, lgtm, size/S

#1453 rename auto to AdvancedRollingUpdate
  docs/proposals/20220718-workload-update-model.md
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller_test.go
  pkg/controller/daemonpodupdater/util.go
  pkg/controller/daemonpodupdater/util_test.go
Labels: approved, lgtm, size/M

#1455 fix yurthub static pod upgrade error
  CHANGELOG.md
  charts/yurthub/templates/yurthub-staticpod.yaml
Labels: approved, kind/bug, lgtm, size/XS

#1457 rename CRD StaticPod to YurtStaticSet
  charts/yurt-manager/crds/apps.openyurt.io_yurtstaticsets.yaml
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  charts/yurthub/templates/yurthub-cfg.yaml
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/app/options/yurtstaticsetcontroller.go
  hack/make-rules/kustomize_to_chart.sh
  pkg/apis/apps/v1alpha1/default.go
  pkg/apis/apps/v1alpha1/yurtstaticset_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/apis/config/types.go
  pkg/controller/controller.go
  pkg/controller/yurtstaticset/config/types.go
  pkg/controller/yurtstaticset/upgradeinfo/upgrade_info.go
  pkg/controller/yurtstaticset/upgradeinfo/upgrade_info_test.go
  pkg/controller/yurtstaticset/util/util.go
  pkg/controller/yurtstaticset/yurtstaticset_controller.go
  pkg/controller/yurtstaticset/yurtstaticset_controller_test.go
  pkg/node-servant/static-pod-upgrade/upgrade.go
  pkg/webhook/server.go
  pkg/webhook/yurtstaticset/v1alpha1/yurtstaticset_default.go
  pkg/webhook/yurtstaticset/v1alpha1/yurtstaticset_handler.go
  pkg/webhook/yurtstaticset/v1alpha1/yurtstaticset_validation.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
  pkg/yurthub/otaupdate/ota.go
  pkg/yurthub/otaupdate/upgrader/static_pod.go
  pkg/yurthub/otaupdate/upgrader/static_pod_test.go
  pkg/yurthub/otaupdate/util/util.go
  test/e2e/cmd/init/constants/constants.go
Labels: approved, lgtm, size/XL

#1459 fix ota upgrade dir non-existent
  pkg/yurthub/otaupdate/upgrader/static_pod.go
Labels: approved, lgtm, size/XS

#1458 fix yurthub static pod isntallation in yurtadm join command
  CHANGELOG.md
  charts/yurt-manager/crds/apps.openyurt.io_yurtstaticsets.yaml
  charts/yurthub/templates/yurthub-cfg.yaml
  charts/yurthub/templates/yurthub-cloud-yurtstaticset.yaml
  charts/yurthub/templates/yurthub-yurtstaticset.yaml
  charts/yurthub/values.yaml
  cmd/yurthub/app/config/config.go
  pkg/apis/apps/v1alpha1/yurtstaticset_types.go
  pkg/controller/yurtstaticset/upgradeinfo/upgrade_info.go
  pkg/controller/yurtstaticset/util/util.go
  pkg/controller/yurtstaticset/yurtstaticset_controller.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/cmd/join/phases/prepare.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
  pkg/yurtadm/util/yurthub/yurthub.go
Labels: approved, kind/enhancement, lgtm, size/L

#1460 fix syntax errors
  CHANGELOG.md
Labels: approved, lgtm, size/S

#1469 upgrade chart version
  charts/pool-coordinator/Chart.yaml
  charts/yurt-manager/Chart.yaml
  charts/yurthub/Chart.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#1465 optimization: replacing commonly used HTTP strings with enumerations.
  pkg/util/util.go
  pkg/yurthub/otaupdate/util/util.go
  pkg/yurthub/proxy/local/faketoken.go
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/server/certificate.go
  pkg/yurthub/server/nonresource.go
Labels: approved, lgtm, size/M

#1471 fix memory leak for yur-tunnel-server
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#1495 Fix the grammatical errors in README.md
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1497 fix format err in pkg/webhook/builder/webhook.go
  pkg/webhook/builder/webhook.go
Labels: approved, lgtm, size/XS
