Repository openyurtio/openyurt, pull requests merged in 2023-08, with the labels that each got.

#1640 delete configmap when yurtstaticset is deleting
  pkg/controller/yurtstaticset/yurtstaticset_controller.go
  pkg/controller/yurtstaticset/yurtstaticset_controller_test.go
Labels: approved, lgtm, size/M, kind/feature

#1647 feat: reclaim device, deviceprofile and deviceservice before exiting YurtIoTDock
  cmd/yurt-iot-dock/app/core.go
  pkg/yurtiotdock/controllers/device_controller.go
  pkg/yurtiotdock/controllers/deviceprofile_controller.go
  pkg/yurtiotdock/controllers/deviceservice_controller.go
Labels: approved, sig/iot, lgtm, size/L, kind/feature

#1652 use dynamicinformerfactory to get nodepool instead of yurt-app-manager-api repo
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/start.go
  go.mod
  go.sum
  pkg/apis/apps/well_known_labels_annotations.go
  pkg/util/kubeconfig/kubeconfig.go
  pkg/util/kubeconfig/kubeconfig_test.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/idempotency.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/initializer/initializer_test.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/manager/manager_test.go
  pkg/yurthub/filter/nodeportisolation/filter.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/filter_test.go
Labels: approved, lgtm, size/XL, kind/feature

#1645 replace str by const
  pkg/yurttunnel/trafficforward/dns/dns.go
Labels: approved, lgtm, size/XS

#1632 remove node-servant unused command
  cmd/yurt-node-servant/node-servant.go
  cmd/yurt-node-servant/preflight-convert/preflight.go
  pkg/node-servant/constant.go
  pkg/node-servant/job.go
  pkg/node-servant/preflight-convert/options.go
  pkg/node-servant/preflight-convert/preflight.go
  pkg/node-servant/preflight/checks.go
  pkg/node-servant/preflight/constants.go
  pkg/node-servant/preflight/interface.go
Labels: approved, lgtm, size/XL, kind/feature

#1635 replace string var by const
  pkg/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_validation.go
Labels: approved, lgtm, size/XS

#1651 improve nodepool to support hostnetwork mode
  Makefile
  charts/yurt-manager/crds/apps.openyurt.io_nodepools.yaml
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/nodepoolcontroller.go
  go.mod
  hack/make-rules/kustomize_to_chart.sh
  pkg/apis/apps/v1alpha1/nodepool_conversion.go
  pkg/apis/apps/v1alpha1/nodepool_types.go
  pkg/apis/apps/v1beta1/default.go
  pkg/apis/apps/v1beta1/nodepool_conversion.go
  pkg/apis/apps/v1beta1/nodepool_types.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/apis/apps/well_known_labels_annotations.go
  pkg/controller/nodepool/config/types.go
  pkg/controller/nodepool/nodepool_controller.go
  pkg/controller/nodepool/nodepool_controller_test.go
  pkg/controller/nodepool/nodepool_enqueue_handlers.go
  pkg/controller/nodepool/nodepool_enqueue_handlers_test.go
  pkg/controller/nodepool/util.go
  pkg/controller/nodepool/util_test.go
  pkg/webhook/node/v1/node_default.go
  pkg/webhook/node/v1/node_default_test.go
  pkg/webhook/node/v1/node_handler.go
  pkg/webhook/node/v1/node_validation.go
  pkg/webhook/node/v1/node_validation_test.go
  pkg/webhook/nodepool/v1alpha1/nodepool_default.go
  pkg/webhook/nodepool/v1alpha1/nodepool_handler.go
  pkg/webhook/nodepool/v1alpha1/nodepool_validation.go
  pkg/webhook/nodepool/v1beta1/nodepool_default.go
  pkg/webhook/nodepool/v1beta1/nodepool_default_test.go
  pkg/webhook/nodepool/v1beta1/nodepool_handler.go
  pkg/webhook/nodepool/v1beta1/nodepool_validation.go
  pkg/webhook/nodepool/v1beta1/nodepool_validation_test.go
  pkg/webhook/server.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/yurthub/network/dummyif_test.go
Labels: approved, lgtm, kind/feature, size/XXL

#1654 feat: add nodepool hostnetwork propagation filter
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/hostnetworkpropagation/filter.go
  pkg/yurthub/filter/hostnetworkpropagation/filter_test.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/manager/manager_test.go
  pkg/yurthub/filter/nodeportisolation/filter.go
  pkg/yurthub/filter/nodeportisolation/filter_test.go
Labels: approved, lgtm, size/XL

#1653 fix verify join token and bootstrapfile only in token bootstrap mode
  cmd/yurthub/app/options/options.go
  pkg/yurthub/certificate/interfaces.go
Labels: approved, kind/bug, lgtm, size/S

#1648 update gateway pickup controller for gateway v1beta1
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/options/gatewaycontroller.go
  cmd/yurt-manager/app/options/options.go
  pkg/controller/apis/config/types.go
  pkg/controller/controller.go
  pkg/controller/raven/common.go
  pkg/controller/raven/gateway/gateway_controller.go
  pkg/controller/raven/gateway/gateway_controller_test.go
  pkg/controller/raven/gateway/gateway_enqueue_handlers.go
  pkg/controller/raven/gatewaypickup/config/types.go
  pkg/controller/raven/gatewaypickup/gateway_pickup_controller.go
  pkg/controller/raven/gatewaypickup/gateway_pickup_controller_test.go
  pkg/controller/raven/gatewaypickup/gateway_pickup_enqueue_handlers.go
  pkg/controller/raven/service/service_controller.go
  pkg/controller/raven/utils/utils.go
Labels: approved, lgtm, size/XXL

#1655 enhancement: remove some client global vars
  cmd/yurt-manager/app/manager.go
  pkg/client/generic_client.go
  pkg/client/registry.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/controller/platformadmin/platformadmin_controller.go
  pkg/controller/raven/gatewaypickup/gateway_pickup_controller.go
  pkg/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/controller/yurtappset/yurtappset_controller.go
  pkg/controller/yurtstaticset/yurtstaticset_controller.go
  pkg/profile/profile_test.go
  pkg/util/client/client.go
  pkg/util/discovery/discovery.go
  pkg/webhook/util/controller/webhook_controller.go
Labels: approved, lgtm, size/L

#1663 improve labels and annotations definition
  pkg/apis/apps/v1alpha1/well_known_labels_annotations.go
  pkg/apis/apps/v1beta1/nodepool_types.go
  pkg/apis/apps/well_known_labels_annotations.go
  pkg/util/json.go
  pkg/yurthub/filter/nodeportisolation/filter_test.go
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
  pkg/yurtmanager/controller/yurtappdaemon/nodepool_enqueue_handlers_test.go
  pkg/yurtmanager/controller/yurtappdaemon/revision_test.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller_test.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/util.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/util_test.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/workload.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/workload_test.go
  pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller_test.go
  pkg/yurtmanager/controller/yurtappset/adapter/adapter_util.go
  pkg/yurtmanager/controller/yurtappset/adapter/adapter_util_test.go
  pkg/yurtmanager/controller/yurtappset/adapter/deployment_adapter.go
  pkg/yurtmanager/controller/yurtappset/adapter/deployment_adapter_test.go
  pkg/yurtmanager/controller/yurtappset/adapter/statefulset_adapter.go
  pkg/yurtmanager/controller/yurtappset/adapter/statefulset_adapter_test.go
  pkg/yurtmanager/controller/yurtappset/pool_control.go
  pkg/yurtmanager/controller/yurtappset/yurtappset_controller_utils.go
  pkg/yurtmanager/webhook/pod/v1/pod_validation.go
  test/e2e/util/nodepool.go
Labels: approved, kind/enhancement, lgtm, size/L

#1633 fix node-servant convert not use yss template to deploy yurthub
  pkg/node-servant/components/yurthub.go
  pkg/node-servant/constant.go
  test/e2e/cmd/init/constants/constants.go
  test/e2e/cmd/init/converter.go
Labels: approved, kind/bug, lgtm, size/L

#1650 feat: establish the component mechanism of the iot system
  charts/yurt-manager/crds/iot.openyurt.io_platformadmins.yaml
  pkg/apis/iot/v1alpha2/platformadmin_types.go
  pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/manifest.yaml
  pkg/yurtmanager/controller/platformadmin/config/config.go
  pkg/yurtmanager/controller/platformadmin/iotdock.go
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
  pkg/yurtmanager/webhook/platformadmin/v1alpha1/platformadmin_handler.go
  pkg/yurtmanager/webhook/platformadmin/v1alpha2/platformadmin_handler.go
  pkg/yurtmanager/webhook/platformadmin/v1alpha2/platformadmin_validation.go
Labels: approved, sig/iot, lgtm, size/L, kind/feature

#1666 feat: upgrade YurtIoTDock to support edgex v3 api
  cmd/yurt-iot-dock/app/core.go
  cmd/yurt-iot-dock/app/options/options.go
  go.mod
  go.sum
  pkg/yurtiotdock/clients/edgex-foundry/edgexobject.go
  pkg/yurtiotdock/clients/edgex-foundry/v2/device_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v2/device_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v2/deviceprofile_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v2/deviceprofile_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v2/deviceservice_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v2/deviceservice_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v2/util.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/device_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/device_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceprofile_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceprofile_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceservice_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceservice_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/util.go
  pkg/yurtiotdock/clients/interface.go
  pkg/yurtiotdock/controllers/device_controller.go
  pkg/yurtiotdock/controllers/device_syncer.go
  pkg/yurtiotdock/controllers/deviceprofile_controller.go
  pkg/yurtiotdock/controllers/deviceprofile_syncer.go
  pkg/yurtiotdock/controllers/deviceservice_controller.go
  pkg/yurtiotdock/controllers/deviceservice_syncer.go
  pkg/yurtiotdock/controllers/util/string.go
  pkg/yurtmanager/controller/platformadmin/iotdock.go
Labels: approved, kind/bug, sig/iot, lgtm, kind/feature, size/XXL

#1639 proposal of support raven NAT traversal
  docs/img/support-raven-nat-traversal/1.png
  docs/img/support-raven-nat-traversal/2.png
  docs/proposals/20230807-support-raven-nat-traversal.md
Labels: approved, kind/documentation, lgtm, size/L

#1669 fix syntax errors
  docs/proposals/00_openyurt-glossary.md
  pkg/yurttunnel/kubernetes/kubernetes.go
  pkg/yurttunnel/server/anpserver.go
Labels: approved, lgtm, size/XS

#1664 add proposal of install openyurt components using dashboard
  docs/img/dashboard-config-modal.png
  docs/img/dashboard-install-modal.png
  docs/img/dashboard-login-page.png
  docs/img/dashboard-manage-page.png
  docs/proposals/20230820-install-openyurt-components-using-dashboard.md
Labels: kind/documentation, lgtm, size/L

#1658 add raven l7 dns controller
  cmd/yurt-manager/app/options/options.go
  pkg/apis/raven/well_known_labels_annotations.go
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/raven/common.go
  pkg/yurtmanager/controller/raven/dns/dns_controller.go
  pkg/yurtmanager/controller/raven/dns/dns_controller_test.go
  pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers_test.go
  pkg/yurtmanager/controller/raven/utils/utils.go
Labels: size/XL

#1659 feat: unserve v1alpha1 version of platformadmin crd
  charts/yurt-manager/crds/iot.openyurt.io_platformadmins.yaml
  pkg/apis/iot/v1alpha1/platformadmin_types.go
Labels: approved, kind/enhancement, sig/iot, lgtm, size/XS

#1679 fix: yurt-iot-dock cannot be dynamically deployed in platformadmin
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
Labels: approved, kind/bug, sig/iot, lgtm, size/S

#1677 add gateway internal service controller
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/raven/common.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller_test.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/utils/options.go
  pkg/yurtmanager/controller/raven/utils/utils.go
Labels: approved, lgtm, size/XL

#1681 feat: add token format checking to yurtadm join process
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
Labels: approved, lgtm, size/S, kind/feature
