Repository openyurtio/openyurt, pull requests merged in 2023-11, with the labels that each got.

#1764 add imagepullsecrets for chart
  charts/yurt-manager/Chart.yaml
  charts/yurt-manager/templates/yurt-manager.yaml
  charts/yurt-manager/values.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#1767 optimize raven controllers
  cmd/yurt-manager/names/controller_names.go
  pkg/yurtmanager/controller/raven/common.go
  pkg/yurtmanager/controller/raven/dns/dns_controller.go
  pkg/yurtmanager/controller/raven/dns/dns_controller_test.go
  pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers_test.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller_test.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller_test.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller_test.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/util/constants.go
  pkg/yurtmanager/controller/raven/util/options.go
  pkg/yurtmanager/controller/raven/util/util.go
  pkg/yurtmanager/webhook/gateway/v1beta1/gateway_validation.go
Labels: approved, lgtm, size/L

#1770 disable the iptables setting of yurthub component by default
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/options/options_test.go
  pkg/yurthub/certificate/manager/manager.go
  pkg/yurthub/certificate/manager/manager_test.go
  pkg/yurthub/network/dummyif_linux.go
  pkg/yurthub/network/network.go
Labels: approved, kind/enhancement, lgtm, size/M

#1765 update maintainers and owners of OpenYurt
  MAINTAINERS.md
  OWNERS
  cmd/yurtadm/OWNERS
  pkg/yurtadm/OWNERS
  pkg/yurtmanager/controller/raven/OWNERS
  pkg/yurtmanager/webhook/gateway/OWNERS
Labels: approved, kind/documentation, lgtm, size/L

#1774 update changelog for release-v1.4
  CHANGELOG.md
Labels: approved, kind/documentation, lgtm, size/L

#1778 update readme for release v1.4
  README.md
  README.zh.md
  docs/img/arch.png
  pkg/yurthub/certificate/manager/manager_test.go
Labels: approved, kind/documentation, lgtm, size/M

#1777 docs: add iot section in changelog for release-v1.4
  CHANGELOG.md
Labels: approved, kind/documentation, sig/iot, lgtm, size/S

#1779 add archive info in changelog
  CHANGELOG.md
Labels: kind/documentation, lgtm, size/S

#1784 add rerun failed workflows script
  .github/workflows/rerun-failed-workflows.yaml
Labels: approved, kind/enhancement, lgtm, size/M

#1787 optimize raven controllers
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller_test.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller_test.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/util/options.go
Labels: approved, size/L

#1788 fix rereun failed jobs in workflow of github actions
  .github/workflows/rerun-failed-workflows.yaml
Labels: approved, lgtm, size/S, kind/feature

#1791 feat:fix error log format in cache manager
  pkg/yurthub/cachemanager/cache_manager.go
Labels: approved, kind/good-first-issue, lgtm, size/XS, kind/feature

#1783 feat: improve request proxy log in yurthub component (#1772)
  pkg/yurthub/proxy/util/util.go
Labels: approved, lgtm, size/XS, kind/feature

#1795 fix the cache leak in yurtappoverrider controller
  pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
Labels: approved, lgtm, size/XS

#1814 Comments alse need camelCase format
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/gatewaycontroller.go
  cmd/yurt-manager/app/options/nodepoolcontroller.go
  cmd/yurt-manager/app/options/platformadmincontroller.go
  cmd/yurt-manager/app/options/yurtappdaemoncontroller.go
  cmd/yurt-manager/app/options/yurtappoverridercontroller.go
  cmd/yurt-manager/app/options/yurtappsetcontroller.go
  cmd/yurt-manager/app/options/yurtstaticsetcontroller.go
Labels: approved, lgtm

#1810 feat: remove gateway v1alpha1 nat fields
  charts/yurt-manager/crds/raven.openyurt.io_gateways.yaml
  pkg/apis/raven/v1alpha1/gateway_conversion.go
  pkg/apis/raven/v1alpha1/gateway_types.go
Labels: approved, lgtm, size/M, kind/feature

#1821 Added logs of yurt-manager component
  pkg/yurtmanager/webhook/util/configuration/configuration.go
Labels: lgtm, size/XS

#1817 Reduce redundant logs
  pkg/yurtmanager/controller/raven/dns/dns_controller.go
  pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers.go
Labels: lgtm, size/L

#1818 improve node labels that are managed by nodepool
  hack/lib/common.sh
  hack/lib/init.sh
  pkg/apis/apps/well_known_labels_annotations.go
  pkg/projectinfo/projectinfo.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurthub/filter/hostnetworkpropagation/filter.go
  pkg/yurthub/filter/hostnetworkpropagation/filter_test.go
  pkg/yurthub/filter/nodeportisolation/filter.go
  pkg/yurthub/filter/nodeportisolation/filter_test.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/filter_test.go
  pkg/yurtmanager/controller/nodepool/nodepool_controller.go
  pkg/yurtmanager/controller/nodepool/nodepool_controller_test.go
  pkg/yurtmanager/controller/nodepool/nodepool_enqueue_handlers.go
  pkg/yurtmanager/controller/nodepool/nodepool_enqueue_handlers_test.go
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/util.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/util_test.go
  pkg/yurtmanager/webhook/node/v1/node_default.go
  pkg/yurtmanager/webhook/node/v1/node_default_test.go
  pkg/yurtmanager/webhook/node/v1/node_validation.go
  pkg/yurtmanager/webhook/node/v1/node_validation_test.go
  pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_validation.go
  pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_validation_test.go
  test/e2e/util/nodepool.go
Labels: approved, kind/enhancement, lgtm, size/L

#1825 modify yurt-manager client's default qps and burst
  cmd/yurt-manager/app/options/generic.go
Labels: approved, lgtm, size/XS, kind/feature

#1824 print out all registered controllers
  pkg/yurtmanager/controller/controller.go
Labels: approved, lgtm, size/XS

#1827 fix dns host using configmap name
  config/setup/raven-proxy-dns.yaml
Labels: approved, lgtm, size/L
