Repository openyurtio/openyurt, pull requests merged in 2023-04, with the labels that each got.

#1349 fix nodepool kind
  pkg/controller/nodepool/nodepool_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#1354 Revert "feat: yurthub automatically recognize nftables or iptables (#1135)"
  hack/dockerfiles/build/Dockerfile.yurthub
  hack/dockerfiles/release/Dockerfile.yurthub
  hack/iptables-wrapper-installer.sh
Labels: approved, lgtm, size/L

#1358 fix nil image registry of pool-coordinator
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/values.yaml
Labels: approved, lgtm, size/XS

#1352 feat: change yurt-manager ClusterRoleBinding name
  charts/openyurt/templates/yurt-manager.yaml
Labels: approved, lgtm, size/XS, kind/feature

#1359 add a new way to create webhook
  hack/make-rules/add_controller.sh
  pkg/webhook/builder/defaulter_custom.go
  pkg/webhook/builder/validator_custom.go
  pkg/webhook/builder/webhook.go
Labels: approved, kind/enhancement, lgtm, size/XL

#1360 fix misses
  pkg/controller/poolcoordinator/cert/util.go
  pkg/webhook/gateway/v1alpha1/gateway_handler.go
Labels: approved, kind/enhancement, lgtm, size/XS

#1355 feat: support pool-coordinator component work in specified namespace
  charts/openyurt/templates/yurt-manager.yaml
  cmd/yurt-manager/app/options/generic.go
  pkg/controller/apis/config/types.go
  pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller.go
Labels: approved, lgtm, size/S

#1364 refactor pool-coordinator-cert controller
  pkg/controller/poolcoordinator/cert/certificate.go
  pkg/controller/poolcoordinator/cert/certificate_test.go
  pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller.go
  pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller_test.go
  pkg/controller/poolcoordinator/cert/secret.go
  pkg/util/kubeconfig/kubeconfig.go
Labels: approved, lgtm, size/L

#1363 fix some misses in yurt-manager
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/manager.go
  pkg/controller/nodepool/nodepool_enqueue_handlers.go
  pkg/controller/poolcoordinator/cert/secret.go
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
Labels: approved, kind/enhancement, lgtm, size/M

#1362 migrate daemonpod controller to yurt-manager
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  pkg/controller/add_daemonpodupdater.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller_test.go
  pkg/controller/daemonpodupdater/util.go
  pkg/controller/daemonpodupdater/util_test.go
Labels: approved, lgtm, size/XL

#1322 add nodepool autonomy into yurt-manager
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  hack/make-rules/add_controller.sh
  pkg/webhook/builder/webhook.go
  pkg/webhook/pod/v1/pod_handler.go
  pkg/webhook/pod/v1/pod_validation.go
Labels: approved, lgtm, size/L

#1365 feat: add nodepool e2e
  hack/make-rules/local-up-openyurt.sh
  test/e2e/util/nodepool.go
  test/e2e/util/util.go
  test/e2e/yurt/nodepool.go
  test/e2e/yurtconfig/yurtconfig.go
Labels: approved, kind/enhancement, lgtm, size/L

#1367 feat: support yurt-manager work in specified namespace
  charts/openyurt/templates/yurt-manager.yaml
  cmd/yurt-manager/app/manager.go
  pkg/controller/gateway/gateway/gateway_controller.go
  pkg/webhook/server.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/util.go
Labels: approved, lgtm, size/M, kind/feature

#1168 add app to support upgrade static pod
  cmd/yurt-node-servant/node-servant.go
  cmd/yurt-node-servant/static-pod-upgrade/upgrade.go
  pkg/node-servant/static-pod-upgrade/options.go
  pkg/node-servant/static-pod-upgrade/upgrade.go
  pkg/node-servant/static-pod-upgrade/upgrade_test.go
  pkg/node-servant/static-pod-upgrade/util/pods.go
  pkg/node-servant/static-pod-upgrade/util/util.go
Labels: approved, lgtm, size/XL

#1261 add StaticPod CRD and controller
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/app/options/staticpodcontroller.go
  go.mod
  pkg/apis/apps/v1alpha1/default.go
  pkg/apis/apps/v1alpha1/staticpod_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_staticpod.go
  pkg/controller/apis/config/types.go
  pkg/controller/staticpod/config/types.go
  pkg/controller/staticpod/staticpod_controller.go
  pkg/controller/staticpod/staticpod_controller_test.go
  pkg/controller/staticpod/upgradeinfo/upgrade_info.go
  pkg/controller/staticpod/upgradeinfo/upgrade_info_test.go
  pkg/controller/staticpod/util/util.go
  pkg/webhook/add_v1alpha1_staticpod.go
  pkg/webhook/pod/v1/pod_handler.go
  pkg/webhook/staticpod/v1alpha1/staticpod_default.go
  pkg/webhook/staticpod/v1alpha1/staticpod_handler.go
  pkg/webhook/staticpod/v1alpha1/staticpod_validation.go
Labels: approved, lgtm, size/XXL

#1366 support yurthub component work in specified namespace
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/options/options_test.go
  cmd/yurthub/app/start.go
  pkg/yurthub/poolcoordinator/certmanager/certmanager.go
  pkg/yurthub/poolcoordinator/certmanager/certmanager_test.go
  pkg/yurthub/poolcoordinator/constants/constants.go
Labels: approved, lgtm, size/M

#1172 support ota upgrade for static pod
  pkg/node-servant/static-pod-upgrade/upgrade.go
  pkg/node-servant/static-pod-upgrade/upgrade_test.go
  pkg/yurthub/otaupdate/ota.go
  pkg/yurthub/otaupdate/ota_test.go
  pkg/yurthub/otaupdate/upgrader/daemon_pod.go
  pkg/yurthub/otaupdate/upgrader/daemon_pod_test.go
  pkg/yurthub/otaupdate/upgrader/static_pod.go
  pkg/yurthub/otaupdate/upgrader/static_pod_test.go
  pkg/yurthub/otaupdate/util/util.go
Labels: approved, lgtm, size/XL

#1373 feat: add feature gate
  cmd/yurt-manager/app/options/generic.go
  pkg/features/features.go
Labels: approved, lgtm, size/M, kind/feature

#1347 merge podbinding and delegatelease controllers into yurt-manager
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  pkg/controller/add_delegatelease.go
  pkg/controller/add_podbinding.go
  pkg/controller/poolcoordinator/delegatelease/delegatelease_controller.go
  pkg/controller/poolcoordinator/delegatelease/delegatelease_controller_test.go
  pkg/controller/poolcoordinator/delegatelease/poolcoordinator_controller.go
  pkg/controller/poolcoordinator/podbinding/pod_binding_controller.go
  pkg/controller/poolcoordinator/podbinding/podbinding_controller.go
Labels: approved, lgtm, kind/feature, size/XXL

#1368 migrate controller yurtappset
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/app/options/yurtappsetcontroller.go
  go.mod
  go.sum
  pkg/apis/apps/v1alpha1/default.go
  pkg/apis/apps/v1alpha1/well_known_labels_annotations.go
  pkg/apis/apps/v1alpha1/yurtappset_conversion.go
  pkg/apis/apps/v1alpha1/yurtappset_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_yurtappset.go
  pkg/controller/apis/config/types.go
  pkg/controller/controller.go
  pkg/controller/nodepool/nodepool_controller.go
  pkg/controller/util/gate/custom_resource_gate.go
  pkg/controller/util/gate/custom_resource_gate_test.go
  pkg/controller/util/refmanager/ref_manager.go
  pkg/controller/util/refmanager/ref_manager_test.go
  pkg/controller/util/statefulset_utils.go
  pkg/controller/util/tools.go
  pkg/controller/util/tools_test.go
  pkg/controller/yurtappset/adapter/adapter.go
  pkg/controller/yurtappset/adapter/adapter_util.go
  pkg/controller/yurtappset/adapter/adapter_util_test.go
  pkg/controller/yurtappset/adapter/deployment_adapter.go
  pkg/controller/yurtappset/adapter/deployment_adapter_test.go
  pkg/controller/yurtappset/adapter/statefulset_adapter.go
  pkg/controller/yurtappset/adapter/statefulset_adapter_test.go
  pkg/controller/yurtappset/config/types.go
  pkg/controller/yurtappset/pool.go
  pkg/controller/yurtappset/pool_control.go
  pkg/controller/yurtappset/pool_controller_test.go
  pkg/controller/yurtappset/revision.go
  pkg/controller/yurtappset/revision_test.go
  pkg/controller/yurtappset/yurtappset_controller.go
  pkg/controller/yurtappset/yurtappset_controller_statefulset_test.go
  pkg/controller/yurtappset/yurtappset_controller_suite_test.go
  pkg/controller/yurtappset/yurtappset_controller_test.go
  pkg/controller/yurtappset/yurtappset_controller_utils.go
  pkg/controller/yurtappset/yurtappset_update.go
  pkg/webhook/add_v1alpha1_yurtappset.go
  pkg/webhook/yurtappset/v1alpha1/validate.go
  pkg/webhook/yurtappset/v1alpha1/yurtappset_default.go
  pkg/webhook/yurtappset/v1alpha1/yurtappset_handler.go
  pkg/webhook/yurtappset/v1alpha1/yurtappset_validation.go
  pkg/webhook/yurtappset/v1alpha1/yurtappset_webhook_test.go
  test/e2e/util/matchers.go
  test/e2e/yurt/yurtappset.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#1383 feat: migrate service topology controller to yurt-manager
  .github/workflows/ci.yaml
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-controller-manager/app/config/config.go
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  cmd/yurt-controller-manager/app/options/options.go
  cmd/yurt-controller-manager/controller-manager.go
  pkg/controller/add_servicetopology_endpoints.go
  pkg/controller/add_servicetopology_endpointslice.go
  pkg/controller/servicetopology/adapter/endpoints_adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
  pkg/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/controller/servicetopology/endpoints/endpoints_enqueue_handlers.go
  pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
  pkg/controller/servicetopology/endpointslice/endpointslice_enqueue_handlers.go
  pkg/controller/servicetopology/servicetopology.go
  pkg/controller/servicetopology/servicetopology_test.go
Labels: approved, lgtm, kind/feature, size/XXL

#1385 fix: modify the naming format
  pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
  pkg/controller/servicetopology/endpointslice/endpointslice_enqueue_handlers.go
Labels: approved, lgtm, size/M

#1376 add luckymrwang as maintainer of OpenYurt
  MAINTAINERS.md
Labels: approved, lgtm, size/S

#1388 support to specify enabled controllers
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/values.yaml
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/generic.go
  pkg/controller/add_csrapprover.go
  pkg/controller/add_daemonpodupdater.go
  pkg/controller/add_delegatelease.go
  pkg/controller/add_gateway.go
  pkg/controller/add_nodepool.go
  pkg/controller/add_podbinding.go
  pkg/controller/add_poolcoordinatorcert.go
  pkg/controller/add_servicetopology_endpoints.go
  pkg/controller/add_servicetopology_endpointslice.go
  pkg/controller/add_staticpod.go
  pkg/controller/add_yurtappset.go
  pkg/controller/apis/config/types.go
  pkg/controller/controller.go
  pkg/controller/util/controller_utils.go
  pkg/webhook/add_v1alpha1_gateway.go
  pkg/webhook/add_v1alpha1_nodepool.go
  pkg/webhook/add_v1alpha1_staticpod.go
  pkg/webhook/add_v1alpha1_yurtappset.go
  pkg/webhook/add_v1beta1_nodepool.go
  pkg/webhook/server.go
Labels: approved, lgtm, size/L

#1391 bugfix for yurtappset
  pkg/webhook/yurtappset/v1alpha1/validate.go
Labels: approved, lgtm, size/XS

#1344 migrate YurtAppDaemon from yurt-app-manager to yurt-manager
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/app/options/yurtappdaemoncontroller.go
  go.mod
  go.sum
  pkg/apis/apps/v1alpha1/default.go
  pkg/apis/apps/v1alpha1/well_known_labels_annotations.go
  pkg/apis/apps/v1alpha1/yurtappdaemon_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_yurtappdaemon.go
  pkg/controller/apis/config/types.go
  pkg/controller/yurtappdaemon/config/types.go
  pkg/controller/yurtappdaemon/nodepool_enqueue_handlers.go
  pkg/controller/yurtappdaemon/nodepool_enqueue_handlers_test.go
  pkg/controller/yurtappdaemon/revision.go
  pkg/controller/yurtappdaemon/revision_test.go
  pkg/controller/yurtappdaemon/util.go
  pkg/controller/yurtappdaemon/util_test.go
  pkg/controller/yurtappdaemon/workloadcontroller/controller.go
  pkg/controller/yurtappdaemon/workloadcontroller/deployment_controller.go
  pkg/controller/yurtappdaemon/workloadcontroller/deployment_controller_test.go
  pkg/controller/yurtappdaemon/workloadcontroller/statefulset_controller.go
  pkg/controller/yurtappdaemon/workloadcontroller/util.go
  pkg/controller/yurtappdaemon/workloadcontroller/util_test.go
  pkg/controller/yurtappdaemon/workloadcontroller/workload.go
  pkg/controller/yurtappdaemon/workloadcontroller/workload_test.go
  pkg/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/controller/yurtappdaemon/yurtappdaemon_controller_test.go
  pkg/webhook/add_v1alpha1_yurtappdaemon.go
  pkg/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_default.go
  pkg/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_handler.go
  pkg/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_validation.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#1387 add validation for StaticPod PodTemplateSpec
  pkg/webhook/staticpod/v1alpha1/staticpod_validation.go
Labels: approved, lgtm, size/S

#1397 move controller register into controller.go
  pkg/controller/add_csrapprover.go
  pkg/controller/add_daemonpodupdater.go
  pkg/controller/add_delegatelease.go
  pkg/controller/add_gateway.go
  pkg/controller/add_nodepool.go
  pkg/controller/add_podbinding.go
  pkg/controller/add_poolcoordinatorcert.go
  pkg/controller/add_servicetopology_endpoints.go
  pkg/controller/add_servicetopology_endpointslice.go
  pkg/controller/add_staticpod.go
  pkg/controller/add_yurtappdaemon.go
  pkg/controller/add_yurtappset.go
  pkg/controller/controller.go
  pkg/webhook/add_v1alpha1_yurtappdaemon.go
Labels: approved, lgtm, size/L

#1398 feat: install yurthub component on edge nodes depending on StaticPod cr resource
  charts/openyurt/templates/yurthub-staticpod.yaml
  charts/openyurt/values.yaml
  pkg/controller/staticpod/staticpod_controller.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
  pkg/yurtadm/util/yurthub/yurthub.go
Labels: approved, lgtm, size/L

#1399 add a parameter for yurt-manager to disable independent webhooks
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/values.yaml
  cmd/yurt-manager/app/options/generic.go
  pkg/controller/apis/config/types.go
  pkg/webhook/add_v1alpha1_gateway.go
  pkg/webhook/add_v1alpha1_nodepool.go
  pkg/webhook/add_v1alpha1_staticpod.go
  pkg/webhook/add_v1alpha1_yurtappdaemon.go
  pkg/webhook/add_v1alpha1_yurtappset.go
  pkg/webhook/add_v1beta1_nodepool.go
  pkg/webhook/server.go
  pkg/webhook/util/util.go
Labels: approved, lgtm, size/L

#1389 feat: crd generate crds
  .github/workflows/ci.yaml
  Makefile
  charts/openyurt/crds/apiextensions.k8s.io_v1_customresourcedefinition_gateways.raven.openyurt.io.yaml
  charts/openyurt/crds/apiextensions.k8s.io_v1_customresourcedefinition_nodepools.apps.openyurt.io.yaml
  charts/openyurt/crds/apiextensions.k8s.io_v1_customresourcedefinition_staticpods.apps.openyurt.io.yaml
  charts/openyurt/crds/apiextensions.k8s.io_v1_customresourcedefinition_yurtappdaemons.apps.openyurt.io.yaml
  charts/openyurt/crds/apiextensions.k8s.io_v1_customresourcedefinition_yurtappsets.apps.openyurt.io.yaml
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  hack/make-rules/kustomize_to_chart.sh
  hack/make-rules/verify_manifests.sh
  test/e2e/cmd/init/converter.go
  test/e2e/cmd/init/util/kubernetes/apply_addons.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#1401 misspelling about log info
  pkg/node-servant/static-pod-upgrade/util/util.go
Labels: approved, lgtm, size/XS

#1404 fix: set default podspec for staticpod podtemplatespec
  pkg/apis/apps/v1alpha1/default.go
Labels: approved, kind/bug, lgtm, size/XS

#1405 invalid doc link
  cmd/yurt-app-manager/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1406 add Yurtappdaemon e2e test
  test/e2e/yurt/yurtappdaemon.go
Labels: approved, lgtm, size/L, kind/feature

#1409 expose yurtmanager metrics port for prometheus use
  charts/openyurt/templates/yurt-manager.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#1408 fix generated crd name
  charts/openyurt/crds/apps.openyurt.io_nodepools.yaml
  charts/openyurt/crds/apps.openyurt.io_staticpods.yaml
  charts/openyurt/crds/apps.openyurt.io_yurtappdaemons.yaml
  charts/openyurt/crds/apps.openyurt.io_yurtappsets.yaml
  charts/openyurt/crds/raven.openyurt.io_gateways.yaml
  hack/make-rules/kustomize_to_chart.sh
Labels: approved, kind/enhancement, lgtm, size/XS

#1413 fix: yurtappset patch
  charts/openyurt/crds/apps.openyurt.io_yurtappsets.yaml
  pkg/apis/apps/v1alpha1/yurtappset_types.go
  test/e2e/yurt/yurtappset.go
Labels: approved, lgtm, size/M

#1415 fix helm charts misses
  charts/openyurt/README.md
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/templates/yurthub-cfg.yaml
  charts/openyurt/values.yaml
  hack/make-rules/kustomize_to_chart.sh
  test/e2e/cmd/init/converter.go
Labels: approved, kind/enhancement, lgtm, size/L

#1416 fix: yurtappdaemon enable check
  pkg/controller/util/gate/custom_resource_gate.go
  pkg/controller/util/gate/custom_resource_gate_test.go
  pkg/controller/yurtappdaemon/yurtappdaemon_controller.go
Labels: approved, kind/enhancement, lgtm, size/L

#1419 support mac os
  hack/make-rules/kustomize_to_chart.sh
Labels: approved, lgtm, size/S

#1417 improve controller names
  cmd/yurt-manager/app/options/gatewaycontroller.go
  pkg/controller/apis/config/types.go
  pkg/controller/controller.go
  pkg/controller/csrapprover/csrapprover_controller.go
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/controller/nodepool/nodepool_controller.go
  pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller.go
  pkg/controller/poolcoordinator/delegatelease/delegatelease_controller.go
  pkg/controller/poolcoordinator/podbinding/podbinding_controller.go
  pkg/controller/raven/common.go
  pkg/controller/raven/config/types.go
  pkg/controller/raven/gateway/gateway_controller.go
  pkg/controller/raven/gateway/gateway_controller_test.go
  pkg/controller/raven/gateway/gateway_enqueue_handlers.go
  pkg/controller/raven/service/service_controller.go
  pkg/controller/raven/utils/utils.go
  pkg/controller/servicetopology/common.go
  pkg/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
  pkg/controller/staticpod/staticpod_controller.go
  pkg/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/controller/yurtappdaemon/yurtappdaemon_controller_test.go
  pkg/controller/yurtappset/yurtappset_controller.go
  pkg/webhook/server.go
Labels: approved, kind/enhancement, lgtm, size/L

#1420 improve yurtadm join command
  charts/openyurt/templates/yurthub-staticpod.yaml
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/constants/constants.go
  pkg/yurthub/certificate/token/token.go
Labels: approved, kind/enhancement, lgtm, size/M

#1421 improve yurt-manager ports and affinity
  charts/openyurt/values.yaml
  cmd/yurt-manager/app/options/generic.go
  pkg/webhook/util/util.go
  test/e2e/cmd/init/constants/constants.go
Labels: approved, kind/enhancement, lgtm, size/S
