Repository openyurtio/openyurt, pull requests merged in 2023-09, with the labels that each got.

#1685 add public service controller for manage loadbalancer service
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/raven/common.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller_test.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers.go
  pkg/yurtmanager/controller/raven/utils/utils.go
  pkg/yurtmanager/webhook/server.go
Labels: approved, lgtm, size/XXL

#1687 improve controller names
  charts/yurt-manager/values.yaml
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/generic.go
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/names/controller_names.go
  go.mod
  go.sum
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/csrapprover/csrapprover_controller.go
  pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/yurtmanager/controller/nodepool/nodepool_controller.go
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
  pkg/yurtmanager/controller/raven/common.go
  pkg/yurtmanager/controller/raven/dns/dns_controller.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
  pkg/yurtmanager/controller/servicetopology/common.go
  pkg/yurtmanager/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/yurtmanager/controller/servicetopology/endpointslice/endpointslice_controller.go
  pkg/yurtmanager/controller/util/controller_utils.go
  pkg/yurtmanager/controller/util/controller_utils_test.go
  pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller_test.go
  pkg/yurtmanager/controller/yurtappset/yurtappset_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/cert/yurtcoordinatorcert_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/delegatelease/delegatelease_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/podbinding/podbinding_controller.go
  pkg/yurtmanager/controller/yurtstaticset/yurtstaticset_controller.go
  pkg/yurtmanager/webhook/server.go
  test/e2e/cmd/init/constants/constants.go
Labels: approved, lgtm, size/XL

#1698 unified expression about DaemonSet
  pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go
Labels: approved, lgtm, size/M

#1690 chore: slice loop replace
  cmd/yurt-tunnel-server/app/options/options.go
  pkg/yurtmanager/controller/yurtappset/adapter/adapter_util.go
Labels: approved, lgtm, size/XS

#1689 modify the logic for judging static pods and combine the utils for pod and node
  pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/yurtmanager/controller/daemonpodupdater/util.go
  pkg/yurtmanager/controller/daemonpodupdater/util_test.go
  pkg/yurtmanager/controller/util/node/controller_utils.go
  pkg/yurtmanager/controller/util/pod/pod_util.go
  pkg/yurtmanager/controller/util/pod/pod_util_test.go
  pkg/yurtmanager/controller/yurtstaticset/upgradeinfo/upgrade_info.go
  pkg/yurtmanager/controller/yurtstaticset/upgradeinfo/upgrade_info_test.go
  pkg/yurtmanager/controller/yurtstaticset/util/util.go
  pkg/yurtmanager/controller/yurtstaticset/yurtstaticset_controller.go
Labels: approved, lgtm, size/L, kind/feature

#1684 Add yurtappoverrider
  charts/yurt-manager/crds/apps.openyurt.io_yurtappoverriders.yaml
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/app/options/yurtappoverridercontroller.go
  cmd/yurt-manager/names/controller_names.go
  go.mod
  pkg/apis/apps/v1alpha1/yurtappoverrider_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/yurtmanager/controller/apis/config/types.go
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/yurtappoverrider/config/types.go
  pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
  pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller_test.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_default.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_handler.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_webhook_test.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/item_control.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/item_control_test.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/patch_control.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/patch_control_test.go
  pkg/yurtmanager/webhook/server.go
  pkg/yurtmanager/webhook/yurtappoverrider/v1alpha1/yurtappoverrider_default.go
  pkg/yurtmanager/webhook/yurtappoverrider/v1alpha1/yurtappoverrider_handler.go
  pkg/yurtmanager/webhook/yurtappoverrider/v1alpha1/yurtappoverrider_validation.go
  test/e2e/yurt/yurtappoverrider.go
Labels: approved, lgtm, kind/feature, size/XXL

#1693 Fix work dir nested `yurthub/yurthub`
  pkg/yurthub/certificate/manager/manager.go
  pkg/yurthub/certificate/manager/manager_test.go
Labels: approved, kind/bug, lgtm, size/S

#1695 fix: add the logic of removing the finalizer in yurt-iot-dock
  pkg/yurtiotdock/controllers/device_syncer.go
  pkg/yurtiotdock/controllers/deviceprofile_syncer.go
  pkg/yurtiotdock/controllers/deviceservice_syncer.go
Labels: kind/bug, sig/iot, lgtm, size/M

#1702 Add status info to YurtAppSet/YurtAppDaemon
  charts/yurt-manager/crds/apps.openyurt.io_yurtappdaemons.yaml
  charts/yurt-manager/crds/apps.openyurt.io_yurtappsets.yaml
  go.mod
  go.sum
  pkg/apis/apps/v1alpha1/yurtappdaemon_types.go
  pkg/apis/apps/v1alpha1/yurtappset_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/yurtmanager/controller/yurtappdaemon/util.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/workload.go
  pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller_test.go
  pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
  pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller_test.go
  pkg/yurtmanager/controller/yurtappset/adapter/adapter.go
  pkg/yurtmanager/controller/yurtappset/adapter/deployment_adapter.go
  pkg/yurtmanager/controller/yurtappset/adapter/statefulset_adapter.go
  pkg/yurtmanager/controller/yurtappset/pool.go
  pkg/yurtmanager/controller/yurtappset/pool_control.go
  pkg/yurtmanager/controller/yurtappset/yurtappset_controller.go
Labels: approved, kind/enhancement, lgtm, size/L

#1676 fix(yurt-manager): raven controller can't list calico blockaffinity
  pkg/apis/addtoscheme_raven_v1alpha1.go
  pkg/apis/calico/v3/blockaffinity.go
  pkg/apis/calico/v3/register.go
  pkg/apis/calico/v3/zz_generated.deepcopy.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
Labels: approved, kind/bug, size/L
