Repository openyurtio/openyurt, pull requests merged in 2023-07, with the labels that each got.

#1576 change access permission to default in general.
  pkg/yurtadm/util/kubernetes/kubernetes.go
Labels: approved, kind/bug, lgtm, size/XS

#1577 feat: add yurtadm binaries release workflow
  .github/workflows/registry.yaml
  .github/workflows/release-assets.yaml
  .goreleaser.yaml
Labels: approved, lgtm, size/M, kind/feature

#1578 build: added github registry
  .github/workflows/registry.yaml
Labels: approved, kind/enhancement, lgtm, size/M

#1582 feat: support edgex minnesota through auto-collector
  pkg/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
  pkg/controller/platformadmin/config/EdgeXConfig/config.json
  pkg/controller/platformadmin/config/EdgeXConfig/manifest.yaml
Labels: approved, sig/iot, lgtm, kind/feature, size/XXL

#1541 add proposal for raven l7
  docs/img/networking/img-4.png
  docs/img/networking/img-5.png
  docs/img/networking/img-6.png
  docs/img/networking/img-7.png
  docs/proposals/20230613-raven-l7-proxy.md
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/apis/raven/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#1592 update chart version from v1.3.2 to v1.3.4
  charts/yurt-coordinator/Chart.yaml
  charts/yurt-manager/Chart.yaml
  charts/yurt-manager/values.yaml
  charts/yurthub/Chart.yaml
  charts/yurthub/values.yaml
Labels: approved, kind/documentation, lgtm, size/S

#1599 change access permission to default in general.
  pkg/yurtadm/util/kubernetes/util.go
Labels: kind/bug, lgtm, size/XS

#1598 change access permission to default in general.
  pkg/yurtadm/util/kubernetes/util.go
Labels: kind/bug, lgtm, size/XS

#1492 add proposal of nodepool with host network mode
  docs/img/host-network-nodepool/arch.png
  docs/img/host-network-nodepool/podhostnetwork-filter.png
  docs/img/host-network-nodepool/podhostnetwork-yurtadm.png
  docs/img/host-network-nodepool/process.png
  docs/proposals/20230524-support-nodepool-with-host-network-mode.md
Labels: approved, lgtm, size/L

#1602 backport: feat: add yurtadm binaries release workflow
  .github/workflows/ci.yaml
  .github/workflows/registry.yaml
  .github/workflows/release-assets.yaml
  .goreleaser.yaml
Labels: approved, lgtm, size/L

#1601 backport: feat: add yurtadm binaries release workflow
  .github/workflows/ci.yaml
  .github/workflows/registry.yaml
  .github/workflows/release-assets.yaml
  .goreleaser.yaml
Labels: approved, lgtm, size/L

#1603 backport: feat: add yurtadm binaries release workflow
  .github/workflows/ci.yaml
  .github/workflows/registry.yaml
  .github/workflows/release-assets.yaml
  .goreleaser.yaml
Labels: approved, lgtm, size/L

#1444 feat: prevent node movement by label modification
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  go.mod
  pkg/webhook/node/v1/node_handler.go
  pkg/webhook/node/v1/node_validation.go
  pkg/webhook/server.go
  pkg/webhook/util/controller/webhook_controller.go
  test/e2e/yurt/nodepool.go
  test/e2e/yurt/yurtappdaemon.go
  test/e2e/yurt/yurtappset.go
Labels: approved, lgtm, kind/feature, size/XXL

#1609 add cpu limit for yurthub
  config/setup/yurthub.yaml
Labels: lgtm, size/XS

#1612 str replaced by const
  pkg/webhook/yurtstaticset/v1alpha1/yurtstaticset_validation.go
Labels: approved, lgtm, size/XS

#1596 feat: provide users with the ability to customize the edgex framework
  pkg/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
  pkg/controller/platformadmin/config/EdgeXConfig/config.json
  pkg/controller/platformadmin/platformadmin_controller.go
Labels: approved, sig/iot, lgtm, kind/feature, size/XXL

#1613 str replaced by const
  pkg/webhook/yurtappset/v1alpha1/yurtappset_validation.go
Labels: approved, lgtm, size/XS

#1625 add kubelet certificate mode in yurthub
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/config/config_test.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/options/options_test.go
  pkg/yurthub/certificate/interfaces.go
  pkg/yurthub/certificate/kubeletcertificate/kubelet_certificate.go
  pkg/yurthub/certificate/kubeletcertificate/kubelet_certificate_test.go
  pkg/yurthub/certificate/manager/manager.go
  pkg/yurthub/certificate/manager/manager_test.go
  pkg/yurthub/certificate/server/server.go
  pkg/yurthub/certificate/server/server_test.go
  pkg/yurthub/certificate/testdata/ca.crt
  pkg/yurthub/certificate/testdata/ca.key
  pkg/yurthub/certificate/testdata/fake_client.go
  pkg/yurthub/certificate/testdata/kubelet.conf
  pkg/yurthub/certificate/testdata/kubelet.pem
  pkg/yurthub/certificate/token/token.go
  pkg/yurthub/certificate/token/token_test.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/server/certificate_test.go
Labels: approved, lgtm, kind/feature, size/XXL

#1631 check whether yurt manager's container is ready in e2e
  test/e2e/cmd/init/converter.go
  test/e2e/cmd/init/init.go
Labels: approved, lgtm, size/S
