Repository openyurtio/openyurt, pull requests merged in 2023-10, with the labels that each got.

#1723 feat: use node-role.kubernetes.io/control-plane for yurt-manager node selection
  charts/yurt-manager/values.yaml
Labels: approved, lgtm, size/XS, kind/feature

#1724 add convert webhook for gateway
  charts/yurt-manager/crds/raven.openyurt.io_gateways.yaml
  hack/make-rules/kustomize_to_chart.sh
Labels: approved, lgtm, size/XL

#1686 refactor(yurt-iot-dock): temporarily remove v3 client to deal with code duplication
  go.mod
  go.sum
  pkg/yurtiotdock/clients/edgex-foundry/edgexobject.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/device_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/device_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceprofile_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceprofile_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceservice_client.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/deviceservice_client_test.go
  pkg/yurtiotdock/clients/edgex-foundry/v3/util.go
  pkg/yurtmanager/controller/platformadmin/iotdock.go
  pkg/yurtmanager/controller/platformadmin/utils/version.go
Labels: kind/enhancement, sig/iot, lgtm, size/XXL

#1709 feat: support yurtadm config command
  go.mod
  go.sum
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/config/config.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/cmdutil.go
Labels: lgtm, size/L, kind/feature

#1719 fix: fix some typo
  pkg/node-servant/convert/convert.go
Labels: lgtm, size/XS

#1712 update make newcontroller logic
  hack/make-rules/add_controller.sh
Labels: approved, lgtm, size/L, kind/feature

#1717 refactor: create yurt-iot-dock helm chart
  charts/yurt-iot-dock/.helmignore
  charts/yurt-iot-dock/Chart.yaml
  charts/yurt-iot-dock/crds/iot.openyurt.io_deviceprofiles.yaml
  charts/yurt-iot-dock/crds/iot.openyurt.io_devices.yaml
  charts/yurt-iot-dock/crds/iot.openyurt.io_deviceservices.yaml
  charts/yurt-iot-dock/templates/_helpers.tpl
  charts/yurt-iot-dock/templates/yurt-iot-dock-auto-generated.yaml
  charts/yurt-iot-dock/values.yaml
  charts/yurt-manager/crds/apps.openyurt.io_yurtappoverriders.yaml
  hack/lib/sync-charts.sh
  hack/make-rules/kustomize_to_chart.sh
Labels: approved, kind/enhancement, sig/iot, lgtm, size/L

#1726 fix: kustomize build yaml skipping blockaffinity
  pkg/apis/calico/v3/doc.go
Labels: approved, lgtm, size/S

#1730 fix yurtappoverrider panic for handling normal deployments that has no ownerreferences
  pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
Labels: approved, kind/bug, lgtm, size/S

#1729 fix pool scope crd resource etcd key path
  pkg/yurthub/storage/etcd/key.go
Labels: approved, lgtm, size/XS

#1745 make yurthub can cache metadata for raven agent
  pkg/yurthub/util/util.go
Labels: approved, kind/enhancement, lgtm, size/XS

#1740 [yurthub component]: fix kubeletcertificate file name error and empty nodepool
  pkg/yurthub/certificate/kubeletcertificate/kubelet_certificate.go
  pkg/yurthub/certificate/manager/manager.go
  pkg/yurtmanager/webhook/node/v1/node_default.go
Labels: approved, kind/bug, lgtm, size/XS

#1743 add ping healthz and readyz for yurt-manager component
  charts/yurt-manager/templates/yurt-manager.yaml
  cmd/yurt-manager/app/manager.go
  test/e2e/cmd/init/constants/constants.go
Labels: approved, kind/enhancement, lgtm, size/M

#1680 [Proposal] use message-bus instead of REST to communicate with EdgeX
  docs/img/messagebus-communication/Image-of-EdgeX-MessageBus.jpg
  docs/img/messagebus-communication/add-device-to-EdgeX.png
  docs/img/messagebus-communication/add-successful-subscription.png
  docs/img/messagebus-communication/an-example-of-the-current-synchronizer.png
  docs/img/messagebus-communication/delete-successful-subscription.png
  docs/img/messagebus-communication/overall-structure.png
  docs/img/messagebus-communication/update-successful-subscription1.png
  docs/img/messagebus-communication/update-successful-subscription2.png
  docs/img/messagebus-communication/update-successful-subscription3.png
  docs/proposals/20230825-use-message-bus-instead-of-REST-to-communicate-with-EdgeX.md
Labels: approved, sig/iot, size/L, kind/design

#1741 improve lease lock for yurt-manager component
  charts/yurt-manager/templates/yurt-manager.yaml
  charts/yurt-manager/values.yaml
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/generic.go
  pkg/yurtmanager/controller/apis/config/types.go
  test/e2e/cmd/init/constants/constants.go
Labels: approved, kind/enhancement, lgtm, size/M

#1742 improve rabc settings of secrets for yurt-manager component
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  charts/yurt-manager/templates/yurt-manager.yaml
  pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/yurtmanager/controller/yurtappset/yurtappset_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/cert/yurtcoordinatorcert_controller.go
  pkg/yurtmanager/webhook/server.go
  pkg/yurtmanager/webhook/util/controller/webhook_controller.go
  pkg/yurtmanager/webhook/util/writer/certwriter.go
  pkg/yurtmanager/webhook/util/writer/error.go
  pkg/yurtmanager/webhook/util/writer/secret.go
  test/e2e/cmd/init/constants/constants.go
  test/e2e/cmd/init/util/kubernetes/apply_addons.go
  test/e2e/cmd/init/util/kubernetes/util.go
Labels: approved, lgtm, size/L

#1746 add nodelifecycle controller
  .github/workflows/ci.yaml
  Makefile
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/generic.go
  cmd/yurt-manager/app/options/nodelifecyclecontroller.go
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/names/controller_names.go
  go.mod
  go.sum
  pkg/util/taints/taints.go
  pkg/util/taints/taints_test.go
  pkg/yurtmanager/controller/apis/config/types.go
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/csrapprover/csrapprover_controller.go
  pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/yurtmanager/controller/internal/controller/controller.go
  pkg/yurtmanager/controller/nodelifecycle/metrics.go
  pkg/yurtmanager/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/yurtmanager/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/yurtmanager/controller/nodelifecycle/scheduler/rate_limited_queue.go
  pkg/yurtmanager/controller/nodelifecycle/scheduler/rate_limited_queue_test.go
  pkg/yurtmanager/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/yurtmanager/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/yurtmanager/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/yurtmanager/controller/nodelifecycle/scheduler/timed_workers_test.go
  pkg/yurtmanager/controller/nodepool/nodepool_controller.go
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
  pkg/yurtmanager/controller/raven/dns/dns_controller.go
  pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
  pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
  pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
  pkg/yurtmanager/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/yurtmanager/controller/servicetopology/endpointslice/endpointslice_controller.go
  pkg/yurtmanager/controller/testutil/test_utils.go
  pkg/yurtmanager/controller/util/helper/helpers.go
  pkg/yurtmanager/controller/util/helper/helpers_test.go
  pkg/yurtmanager/controller/util/node/controller_utils.go
  pkg/yurtmanager/controller/util/tools.go
  pkg/yurtmanager/controller/yurtappdaemon/revision_test.go
  pkg/yurtmanager/controller/yurtappdaemon/util_test.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller_test.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/util_test.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/workload_test.go
  pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
  pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
  pkg/yurtmanager/controller/yurtappset/yurtappset_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/cert/yurtcoordinatorcert_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/delegatelease/delegatelease_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/podbinding/podbinding_controller.go
  pkg/yurtmanager/controller/yurtcoordinator/podbinding/podbinding_controller_test.go
  pkg/yurtmanager/controller/yurtstaticset/yurtstaticset_controller.go
  pkg/yurtmanager/webhook/node/v1/node_handler.go
  pkg/yurtmanager/webhook/pod/v1/pod_handler.go
  pkg/yurtmanager/webhook/pod/v1/pod_validation.go
  pkg/yurtmanager/webhook/server.go
Labels: approved, lgtm, size/XXL

#1757 remove some k8s.io/kubernetes dependencies
  pkg/util/helper/helpers.go
  pkg/util/helper/helpers_test.go
  pkg/util/taints/taints.go
  pkg/yurtmanager/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/yurtmanager/controller/util/node/controller_utils.go
Labels: approved, kind/enhancement, lgtm, size/XS

#1758 upgrade helm charts version to v1.4.0
  charts/yurt-coordinator/Chart.yaml
  charts/yurt-manager/Chart.yaml
  charts/yurthub/Chart.yaml
Labels: approved, lgtm, size/S, kind/feature

#1759 fix dns controller get raven dns configmap
  pkg/yurtmanager/controller/raven/dns/dns_controller.go
Labels: approved, lgtm, size/S

#1762 feat: update gateway for nat traversal
  charts/yurt-manager/crds/raven.openyurt.io_gateways.yaml
  pkg/apis/calico/v3/zz_generated.deepcopy.go
  pkg/apis/raven/v1alpha1/gateway_conversion.go
  pkg/apis/raven/v1alpha1/gateway_types.go
  pkg/apis/raven/v1beta1/gateway_types.go
Labels: approved, lgtm, size/L, kind/feature
