Repository openyurtio/openyurt, pull requests merged in 2023-02, with the labels that each got.

#1192 feat: bump golang from 1.16 to 1.17
  go.mod
Labels: approved, lgtm, size/M, kind/feature

#1191 [Enhancement] improve image build efficiency
  Makefile
  hack/dockerfiles/build/Dockerfile.node-servant
  hack/dockerfiles/build/Dockerfile.yurt-controller-manager
  hack/dockerfiles/build/Dockerfile.yurt-tunnel-agent
  hack/dockerfiles/build/Dockerfile.yurt-tunnel-server
  hack/dockerfiles/build/Dockerfile.yurthub
  hack/dockerfiles/release/Dockerfile.node-servant
  hack/dockerfiles/release/Dockerfile.yurt-controller-manager
  hack/dockerfiles/release/Dockerfile.yurt-tunnel-agent
  hack/dockerfiles/release/Dockerfile.yurt-tunnel-server
  hack/dockerfiles/release/Dockerfile.yurthub
  hack/lib/build.sh
  hack/lib/common.sh
  hack/make-rules/build.sh
  hack/make-rules/image_build.sh
  hack/make-rules/local-up-openyurt.sh
Labels: approved, kind/enhancement, lgtm, size/L

#1187 Bugfix: fix handle poolcoordinator certificates in case of restarting…
  pkg/controller/poolcoordinator/cert/certificate.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
Labels: approved, kind/bug, lgtm, size/M

#1189 support filter chain for filtering response data
  pkg/yurthub/filter/approver.go
  pkg/yurthub/filter/approver_test.go
  pkg/yurthub/filter/discardcloudservice/filter.go
  pkg/yurthub/filter/discardcloudservice/filter_test.go
  pkg/yurthub/filter/discardcloudservice/handler.go
  pkg/yurthub/filter/filter.go
  pkg/yurthub/filter/filter_test.go
  pkg/yurthub/filter/inclusterconfig/filter.go
  pkg/yurthub/filter/inclusterconfig/filter_test.go
  pkg/yurthub/filter/inclusterconfig/handler.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/interfaces.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/manager/manager_test.go
  pkg/yurthub/filter/masterservice/filter.go
  pkg/yurthub/filter/masterservice/filter_test.go
  pkg/yurthub/filter/masterservice/handler.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/filter_test.go
  pkg/yurthub/filter/servicetopology/handler.go
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/remote/loadbalancer.go
Labels: approved, lgtm, kind/feature, size/XXL

#1194 Create dependabot.yml
  .github/dependabot.yml
Labels: approved, kind/enhancement, lgtm, size/S

#1196 add 2023 roadmap for SIG controlplane
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/S

#1208 fix unavailable coordinator image
  charts/openyurt/values.yaml
Labels: approved, lgtm, size/XS

#1210 add ignore package for dependabot
  .github/dependabot.yml
Labels: approved, kind/enhancement, lgtm, size/XS

#1195 fix: re-list when target change
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/proxy/util/util.go
Labels: lgtm, size/M

#1218 fix: pool-coordinator cannot be rescheduled when its node fails (#1212)
  charts/openyurt/templates/pool-coordinator.yaml
Labels: approved, lgtm, size/XS

#1224 fix: make lint bug
  Makefile
Labels: approved, kind/bug, lgtm, size/XS

#1228 align versions of CI tools
  .github/workflows/ci.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#1232 Add yurt-manager controller framework
  .gitignore
  Makefile
  charts/openyurt/templates/_helpers.tpl
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/values.yaml
  cmd/yurt-manager/README.md
  cmd/yurt-manager/main.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/dockerfiles/build/Dockerfile.yurt-manager
  hack/dockerfiles/release/Dockerfile.yurt-manager
  hack/make-rules/add_controller.sh
  hack/make-rules/build.sh
  hack/make-rules/image_build.sh
  hack/make-rules/kustomize_to_chart.sh
  pkg/apis/apis.go
  pkg/client/generic_client.go
  pkg/client/registry.go
  pkg/controller/controller.go
  pkg/util/client/client.go
  pkg/util/discovery/discovery.go
  pkg/util/json.go
  pkg/webhook/server.go
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/generator/certgenerator.go
  pkg/webhook/util/generator/selfsigned.go
  pkg/webhook/util/generator/util.go
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/health/handler.go
  pkg/webhook/util/util.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
  pkg/webhook/util/writer/certwriter.go
  pkg/webhook/util/writer/error.go
  pkg/webhook/util/writer/fs.go
  pkg/webhook/util/writer/secret.go
Labels: approved, kind/feature, size/XXL

#1219 feat: merge yurtctl to e2e
  .gitignore
  cmd/yurtctl/yurtctl.go
  go.mod
  go.sum
  hack/lib/build.sh
  hack/make-rules/build.sh
  hack/make-rules/local-up-openyurt.sh
  hack/make-rules/run-e2e-tests.sh
  pkg/yurtctl/cmd/clusterinfo/clusterinfo.go
  pkg/yurtctl/cmd/markautonomous/markautonomous.go
  test/e2e/autonomy/autonomy.go
  test/e2e/cmd/cmd.go
  test/e2e/cmd/e2e/e2e.go
  test/e2e/cmd/init/constants/constants.go
  test/e2e/cmd/init/constants/openyurt-kindconfig-tmpl.go
  test/e2e/cmd/init/constants/yurt-tunnel-agent-tmpl.go
  test/e2e/cmd/init/constants/yurt-tunnel-server-tmpl.go
  test/e2e/cmd/init/converter.go
  test/e2e/cmd/init/converter_test.go
  test/e2e/cmd/init/init.go
  test/e2e/cmd/init/init_test.go
  test/e2e/cmd/init/kindoperator.go
  test/e2e/cmd/init/kindoperator_test.go
  test/e2e/cmd/init/lock/lock.go
  test/e2e/cmd/init/lock/lock_test.go
  test/e2e/cmd/init/util/kubernetes/apply_addons.go
  test/e2e/cmd/init/util/kubernetes/apply_addons_test.go
  test/e2e/cmd/init/util/kubernetes/util.go
  test/e2e/cmd/init/util/kubernetes/util_test.go
  test/e2e/constants/constants.go
  test/e2e/e2e_test.go
  test/e2e/yurt/yurt.go
  test/e2e/yurttunnel/yurttunnel.go
Labels: approved, lgtm, size/XL, kind/feature

#1237 Fix: make rename replace old dir
  pkg/yurthub/util/fs/store.go
Labels: approved, size/XS

#1244 Fix: yurtadm minor version compatibility of kubelet and kubeadm
  pkg/yurtadm/util/kubernetes/kubernetes.go
Labels: approved, kind/bug, lgtm, size/S

#1209 add nodeportisolation filter in yurthub
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/nodeportisolation/filter.go
  pkg/yurthub/filter/nodeportisolation/filter_test.go
Labels: approved, lgtm, size/XL, kind/feature

#1252 fix: update k8s registry url
  charts/openyurt/values.yaml
Labels: approved, kind/bug, lgtm, size/XS

#1251 feat: upgrade golangci-lint and golang version to v1.18
  .github/workflows/ci.yaml
  Makefile
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  cmd/yurt-controller-manager/app/options/options.go
  cmd/yurt-controller-manager/controller-manager.go
  cmd/yurt-manager/main.go
  go.mod
  go.sum
  pkg/apis/apis.go
  pkg/client/generic_client.go
  pkg/client/registry.go
  pkg/controller/controller.go
  pkg/controller/kubernetes/util/node/node.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager_test.go
  pkg/controller/servicetopology/adapter/adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
  pkg/controller/servicetopology/servicetopology.go
  pkg/controller/servicetopology/servicetopology_test.go
  pkg/util/certmanager/factory/factory_test.go
  pkg/util/client/client.go
  pkg/util/discovery/discovery.go
  pkg/util/json.go
  pkg/util/strings/util_test.go
  pkg/webhook/server.go
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/generator/certgenerator.go
  pkg/webhook/util/generator/selfsigned.go
  pkg/webhook/util/generator/util.go
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/health/handler.go
  pkg/webhook/util/util.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
  pkg/webhook/util/writer/certwriter.go
  pkg/webhook/util/writer/error.go
  pkg/webhook/util/writer/fs.go
  pkg/webhook/util/writer/secret.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/reset/reset_test.go
  pkg/yurtadm/util/util.go
  pkg/yurthub/kubernetes/serializer/serializer.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/storage/etcd/storage.go
  pkg/yurthub/tenant/jwt/jwt_test.go
  pkg/yurthub/util/fs/store_test.go
  pkg/yurttunnel/handlerwrapper/initializer/initializer_test.go
  pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
  pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler_test.go
  pkg/yurttunnel/server/serveraddr/addr.go
  pkg/yurttunnel/server/serveraddr/addr_test.go
  test/e2e/util/util.go
Labels: approved, lgtm, size/L

#1255 feat: upgrade go 1.17 to 1.18
  hack/dockerfiles/build/Dockerfile.node-servant
  hack/dockerfiles/build/Dockerfile.yurt-controller-manager
  hack/dockerfiles/build/Dockerfile.yurt-manager
  hack/dockerfiles/build/Dockerfile.yurt-tunnel-agent
  hack/dockerfiles/build/Dockerfile.yurt-tunnel-server
  hack/dockerfiles/build/Dockerfile.yurthub
  hack/dockerfiles/release/Dockerfile.node-servant
  hack/dockerfiles/release/Dockerfile.yurt-controller-manager
  hack/dockerfiles/release/Dockerfile.yurt-manager
  hack/dockerfiles/release/Dockerfile.yurt-tunnel-agent
  hack/dockerfiles/release/Dockerfile.yurt-tunnel-server
  hack/dockerfiles/release/Dockerfile.yurthub
  hack/make-rules/image_build.sh
Labels: approved, lgtm, size/M

#1260 add security and release docs
  RELEASE-PROCESS.md
  RELEASES.md
  SECURITY.md
Labels: approved, kind/documentation, lgtm, size/L

#1266 add a blank line to follow the rule of golangci-lint
  hack/make-rules/add_controller.sh
Labels: approved, lgtm, size/XS

#1262 revise readme of OpenYurt
  README.md
  README.zh.md
  docs/img/arch.png
  docs/img/ding.jpg
Labels: approved, kind/documentation, lgtm, size/S

#1256 add YTGhost as reviewer of OpenYurt
  OWNERS
Labels: approved, lgtm, size/XS

#1257 add fengshunli as reviewers of OpenYurt
  OWNERS
Labels: approved, size/XS

#1254 Fix: update package dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1265 update README
  README.md
  README.zh.md
Labels: approved, kind/documentation, lgtm, size/L

#1258 clean up yurtctl and template of kcm controller
  cmd/yurt-node-servant/node-servant.go
  pkg/node-servant/constant.go
  pkg/node-servant/job.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/edgenode/edgenode.go
Labels: approved, kind/enhancement, lgtm, size/M

#1268 Bugfix: delete specific iptables while testing kube-proxy
  test/e2e/autonomy/autonomy.go
Labels: approved, kind/bug, lgtm, size/S
