Repository openyurtio/openyurt, pull requests merged in 2023-12, with the labels that each got.

#1835 fix: yurappoverrider e2e test
  test/e2e/yurt/yurtappoverrider.go
Labels: approved, lgtm, size/S

#1834 improve FieldIndexer setting in yurt-manager
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/nodelifecycle/node_lifecycle_controller.go
Labels: lgtm, size/M

#1833 Update deploymentrender_default.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_default.go
Labels: lgtm, size/XS

#1843 fix(yurt-iot-dock): multi-architecture yurt-iot-dock was not pushed
  Makefile
Labels: approved, kind/bug, sig/iot, lgtm, size/XS

#1837 fix: yurtadm join ignorePreflightErrors could not set all
  pkg/yurtadm/cmd/config/config.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/constants/constants.go
Labels: approved, kind/bug, lgtm, size/S

#1839 replace string var by const
  pkg/yurttunnel/constants/constants.go
  pkg/yurttunnel/server/anpserver.go
  pkg/yurttunnel/server/interceptor.go
Labels: approved, lgtm, size/XS

#1826 return Forbidden is appropriate
  pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_validation.go
  pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_validation_test.go
Labels: approved, lgtm, size/S, kind/feature

#1847 upgrade helm charts image version to v1.4.0
  charts/yurt-manager/Chart.yaml
  charts/yurt-manager/values.yaml
  charts/yurthub/Chart.yaml
  charts/yurthub/values.yaml
Labels: approved, kind/bug, lgtm, size/XS

#1816 [Proposal] High Availability of Edge Services Proposal
  docs/img/YurtLB/arch.png
  docs/img/YurtLB/speaker-demo.png
  docs/proposals/20231121-high-availability-of-edge-services.md
Labels: approved, do-not-merge/hold, lgtm, size/L

#1851 Fix: webhook overwrite deployment owned by yad/yas
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller.go
  pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller_test.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_default.go
  pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_webhook_test.go
Labels: kind/bug, lgtm, size/M

#1750 test: added e2e test for iot systems
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
  test/e2e/cmd/init/init.go
  test/e2e/e2e_test.go
  test/e2e/util/nodepool.go
  test/e2e/util/util.go
  test/e2e/yurt/iot.go
Labels: approved, kind/enhancement, sig/iot, lgtm, size/L

#1840 yurt express: openyurt data transmission system proposal
  docs/img/yurt-express-arch.png
  docs/img/yurt-iot-dock.png
  docs/proposals/20231205-yurt-express.md
Labels: size/L

#1864 proposal: add NodeBucket to reduce cloud-edge traffic spike during rapid node additions.
  docs/proposals/20231219-reduce-traffic-spike-during-rapid-node-additions.md
Labels: approved, kind/documentation, size/M

#1873 feat: bookmark and error response should be skipped in yurthub filter (#1868)
  pkg/yurthub/filter/filter.go
Labels: approved, lgtm

#1875 Feature: add name-length of dummy interface too long error
  cmd/yurthub/app/options/options.go
Labels: approved, lgtm

#1884 fix(yurt-manager): add clusterrole for nodes/status subresources
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  pkg/yurtmanager/controller/nodelifecycle/node_lifecycle_controller.go
Labels: approved, lgtm
