Repository openyurtio/openyurt, pull requests merged in 2023-03, with the labels that each got.

#1280 Upgrade openyurt to v1.2.1
  charts/openyurt/Chart.yaml
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/values.yaml
Labels: approved, lgtm, size/M

#1281 Chore: add static check to golangci-lint
  .golangci.yaml
  cmd/yurt-tunnel-server/app/start.go
  pkg/yurthub/certificate/token/token.go
  pkg/yurthub/network/network.go
  pkg/yurthub/poolcoordinator/resources/resources.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/transport/transport.go
  pkg/yurttunnel/server/interceptor_test.go
  pkg/yurttunnel/trafficforward/dns/util_test.go
  pkg/yurttunnel/trafficforward/iptables/iptables.go
Labels: approved, lgtm, size/M

#1291 Add trivy scan
  .github/workflows/trivy-scan.yml
Labels: approved, lgtm, size/M

#1293 add trivy info
  SECURITY.md
Labels: approved, kind/documentation, lgtm, size/XS

#1284 Add OpenSSF Scorecard for README.md
  README.md
  README.zh.md
Labels: approved, size/XS

#1295 ci: bump ubuntu from 20.04 to 22.04
  .github/workflows/back-port.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#1298 feat: optimize make lint
  .github/workflows/ci.yaml
  Makefile
Labels: approved, lgtm, size/S, kind/feature

#1299 Add Scorecard schedule
  .github/workflows/sonarcloud.yaml
Labels: approved, lgtm, size/XS

#1305 docs: update chart readme
  charts/openyurt/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1309 cleanup: io/ioutil
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
  pkg/webhook/util/writer/fs.go
  pkg/yurthub/certificate/token/token_test.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/server/nonresource_test.go
  pkg/yurthub/util/connrotation_test.go
  pkg/yurthub/util/util_test.go
Labels: approved, kind/bug, lgtm, size/M

#1301 yurt-tunnel and yurt-controller-manager component are deprecated
  .github/workflows/trivy-scan.yml
Labels: approved, lgtm, size/XS

#1296 move nodepool controller to yurt-manager, and change yurt-manger framework to support mutiversion
  Makefile
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  charts/openyurt/values.yaml
  cmd/yurt-manager/app/config/config.go
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/generic.go
  cmd/yurt-manager/app/options/nodepoolcontroller.go
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/main.go
  cmd/yurt-manager/yurt-manager.go
  hack/make-rules/add_controller.sh
  pkg/apis/addtoscheme_apps_v1alpha1.go
  pkg/apis/addtoscheme_apps_v1beta1.go
  pkg/apis/apps/v1alpha1/default.go
  pkg/apis/apps/v1alpha1/doc.go
  pkg/apis/apps/v1alpha1/groupversion_info.go
  pkg/apis/apps/v1alpha1/nodepool_conversion.go
  pkg/apis/apps/v1alpha1/nodepool_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1beta1/default.go
  pkg/apis/apps/v1beta1/doc.go
  pkg/apis/apps/v1beta1/groupversion_info.go
  pkg/apis/apps/v1beta1/nodepool_conversion.go
  pkg/apis/apps/v1beta1/nodepool_types.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/apis/apps/well_known_labels_annotations.go
  pkg/controller/add_nodepool.go
  pkg/controller/apis/config/types.go
  pkg/controller/controller.go
  pkg/controller/nodepool/config/types.go
  pkg/controller/nodepool/nodepool_controller.go
  pkg/controller/nodepool/nodepool_enqueue_handlers.go
  pkg/controller/nodepool/util.go
  pkg/projectinfo/projectinfo.go
  pkg/webhook/add_v1alpha1_nodepool.go
  pkg/webhook/add_v1beta1_nodepool.go
  pkg/webhook/nodepool/v1alpha1/nodepool_default.go
  pkg/webhook/nodepool/v1alpha1/nodepool_handler.go
  pkg/webhook/nodepool/v1alpha1/nodepool_validation.go
  pkg/webhook/nodepool/v1beta1/nodepool_default.go
  pkg/webhook/nodepool/v1beta1/nodepool_handler.go
  pkg/webhook/nodepool/v1beta1/nodepool_validation.go
  pkg/webhook/server.go
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/util.go
Labels: approved, lgtm, size/XXL

#1289 Feature: add raven gateway CRD
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  charts/openyurt/templates/yurt-manager.yaml
  cmd/yurt-manager/app/options/gatewaycontroller.go
  cmd/yurt-manager/app/options/options.go
  go.mod
  go.sum
  pkg/apis/addtoscheme_raven_v1alpha1.go
  pkg/apis/raven/v1alpha1/default.go
  pkg/apis/raven/v1alpha1/doc.go
  pkg/apis/raven/v1alpha1/gateway_conversion.go
  pkg/apis/raven/v1alpha1/gateway_types.go
  pkg/apis/raven/v1alpha1/groupversion_info.go
  pkg/apis/raven/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/raven/well_known_labels_annotations.go
  pkg/controller/add_gateway.go
  pkg/controller/apis/config/types.go
  pkg/controller/gateway/common.go
  pkg/controller/gateway/config/types.go
  pkg/controller/gateway/gateway/gateway_controller.go
  pkg/controller/gateway/gateway/gateway_controller_test.go
  pkg/controller/gateway/gateway/gateway_enqueue_handlers.go
  pkg/controller/gateway/service/service_controller.go
  pkg/controller/gateway/utils/utils.go
  pkg/webhook/add_v1alpha1_gateway.go
  pkg/webhook/gateway/v1alpha1/gateway_default.go
  pkg/webhook/gateway/v1alpha1/gateway_handler.go
  pkg/webhook/gateway/v1alpha1/gateway_validation.go
Labels: approved, lgtm, size/XXL

#1315 Update jwt_test.go
  pkg/yurthub/tenant/jwt/jwt_test.go
Labels: approved, lgtm, size/XS

#1317 Fix comment format
  cmd/yurt-manager/app/config/config.go
  cmd/yurt-manager/app/manager.go
  cmd/yurt-manager/app/options/generic.go
  cmd/yurt-manager/app/options/nodepoolcontroller.go
  pkg/apis/addtoscheme_apps_v1beta1.go
  pkg/apis/apps/v1alpha1/nodepool_conversion.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1beta1/default.go
  pkg/apis/apps/v1beta1/nodepool_conversion.go
  pkg/apis/apps/v1beta1/nodepool_types.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/apis/apps/well_known_labels_annotations.go
  pkg/apis/raven/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/nodepool/config/types.go
  pkg/controller/nodepool/nodepool_enqueue_handlers.go
  pkg/controller/nodepool/util.go
  pkg/util/kubernetes/kubeadm/app/apis/bootstraptoken/v1/zz_generated.deepcopy.go
  pkg/webhook/nodepool/v1alpha1/nodepool_default.go
  pkg/webhook/nodepool/v1alpha1/nodepool_handler.go
  pkg/webhook/nodepool/v1alpha1/nodepool_validation.go
  pkg/webhook/nodepool/v1beta1/nodepool_default.go
  pkg/webhook/nodepool/v1beta1/nodepool_handler.go
  pkg/webhook/nodepool/v1beta1/nodepool_validation.go
  pkg/yurtadm/util/initsystem/initsystem_windows.go
Labels: approved, lgtm, size/M

#1316 Fix branch not found
  .github/workflows/trivy-scan.yml
Labels: approved, lgtm, size/XS

#1319 Fix: delete more DOCKER_BUILDX_VERSION env
  .github/workflows/ci.yaml
Labels: approved, lgtm, size/XS

#1313 migrate csr approver into yurt-manager
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  go.mod
  go.sum
  pkg/controller/add_csrapprover.go
  pkg/controller/csrapprover/csrapprover_controller.go
  pkg/controller/csrapprover/csrapprover_controller_test.go
  pkg/controller/kubernetes/controller/controller_utils.go
  pkg/controller/kubernetes/controller/testutil/test_utils.go
  pkg/controller/kubernetes/controller/util/node/controller_utils.go
  pkg/controller/kubernetes/util/node/node.go
  pkg/controller/kubernetes/util/node/node_test.go
  pkg/controller/kubernetes/util/taints/taints.go
  pkg/controller/kubernetes/util/taints/taints_test.go
  pkg/controller/util/node/controller_utils.go
  pkg/yurtadm/util/edgenode/edgenode.go
  test/e2e/cmd/init/constants/constants.go
  test/e2e/cmd/init/converter.go
  test/e2e/cmd/init/converter_test.go
  test/e2e/cmd/init/init.go
  test/e2e/cmd/init/init_test.go
  test/e2e/cmd/init/util/kubernetes/apply_addons.go
Labels: approved, lgtm, kind/feature, size/XXL

#1320 Fix: remove deprecated rand
  Makefile
  cmd/yurt-controller-manager/controller-manager.go
  cmd/yurt-manager/yurt-manager.go
  cmd/yurt-node-servant/node-servant.go
  cmd/yurthub/yurthub.go
Labels: approved, lgtm, size/S

#1323 remove yurt-tunnel from openyurt kind cluster and e2e tests
  Makefile
  go.mod
  go.sum
  hack/dockerfiles/build/Dockerfile.yurt-controller-manager
  hack/dockerfiles/build/Dockerfile.yurt-tunnel-agent
  hack/dockerfiles/build/Dockerfile.yurt-tunnel-server
  hack/dockerfiles/release/Dockerfile.yurt-controller-manager
  hack/dockerfiles/release/Dockerfile.yurt-tunnel-agent
  hack/dockerfiles/release/Dockerfile.yurt-tunnel-server
  hack/make-rules/build.sh
  hack/make-rules/image_build.sh
  hack/make-rules/local-up-openyurt.sh
  test/e2e/cmd/init/constants/constants.go
  test/e2e/cmd/init/constants/yurt-tunnel-agent-tmpl.go
  test/e2e/cmd/init/constants/yurt-tunnel-server-tmpl.go
  test/e2e/cmd/init/converter.go
  test/e2e/cmd/init/converter_test.go
  test/e2e/cmd/init/init.go
  test/e2e/cmd/init/init_test.go
  test/e2e/cmd/init/util/kubernetes/apply_addons.go
  test/e2e/cmd/init/util/kubernetes/apply_addons_test.go
  test/e2e/cmd/init/util/kubernetes/util.go
  test/e2e/cmd/init/util/kubernetes/util_test.go
  test/e2e/constants/constants.go
  test/e2e/e2e_test.go
  test/e2e/yurttunnel/yurttunnel.go
Labels: approved, lgtm, size/XXL

#1324 adjust ports for yurt-manager component to 10270~10279
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/values.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#1326 print logs of yurt-manager component in local-up-openyurt
  test/e2e/cmd/init/converter.go
  test/e2e/cmd/init/util/kubernetes/util.go
Labels: approved, kind/enhancement, lgtm, size/S

#1331 enable to build binary with cn GOPROXY
  Makefile
Labels: approved, kind/enhancement, lgtm, size/XS

#1327 feat: yurthub automatically recognize nftables or iptables (#1135)
  hack/dockerfiles/build/Dockerfile.yurthub
  hack/dockerfiles/release/Dockerfile.yurthub
  hack/iptables-wrapper-installer.sh
Labels: approved, size/L, kind/feature

#1332 improve prefilght into node-servant
  pkg/node-servant/preflight-convert/preflight.go
  pkg/node-servant/preflight/checks.go
  pkg/node-servant/preflight/constants.go
  pkg/node-servant/preflight/interface.go
Labels: approved, kind/enhancement, lgtm, size/XS

#1333 support pass bootstrap-file to yurthub
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  pkg/yurthub/certificate/token/token.go
  pkg/yurthub/server/server.go
Labels: approved, lgtm, size/M, kind/feature

#1335 add system proxy for docker run
  hack/make-rules/image_build.sh
Labels: approved, kind/bug, lgtm, size/XS

#1334 improve csr approver controller with injector
  pkg/controller/csrapprover/csrapprover_controller.go
Labels: approved, kind/enhancement, lgtm, size/M

#1338 【FIX】fix yurt-controller-manager clusterrole missing pod delete
  charts/openyurt/templates/yurt-controller-manager.yaml
Labels: approved, kind/bug, lgtm, size/XS

#1314 feat: add yurtadm renew certificate command
  go.mod
  go.sum
  pkg/node-servant/components/yurthub.go
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/join/phases/postcheck.go
  pkg/yurtadm/cmd/join/phases/prepare.go
  pkg/yurtadm/cmd/renew/certificate/certificate.go
  pkg/yurtadm/cmd/renew/renew.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/error/error.go
  pkg/yurtadm/util/error/error_test.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
  pkg/yurtadm/util/yurthub/yurthub.go
Labels: approved, lgtm, size/XL, kind/feature

#1340 【FIX】fix daemonset pod updater pointer error
  pkg/controller/daemonpodupdater/util.go
Labels: approved, kind/bug, lgtm, size/XS

#1336 migrate controller poolcoordinatorcert
  charts/openyurt/templates/yurt-manager-auto-generated.yaml
  charts/openyurt/templates/yurt-manager.yaml
  charts/openyurt/values.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/apis/raven/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_poolcoordinatorcert.go
  pkg/controller/poolcoordinator/cert/certificate.go
  pkg/controller/poolcoordinator/cert/certificate_test.go
  pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller.go
  pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller_test.go
  pkg/controller/poolcoordinator/cert/secret.go
  pkg/controller/poolcoordinator/cert/secret_test.go
  pkg/controller/poolcoordinator/cert/util.go
  pkg/controller/poolcoordinator/cert/util_test.go
Labels: approved, kind/enhancement, lgtm, size/L

#1312 【FIX】fix pool-coordinator running error when some error happened and abort…
  pkg/yurthub/poolcoordinator/coordinator.go
Labels: approved, kind/bug, lgtm, size/M

#1346 【FIX】fix node not-ready condition when leader disconnect with cloud
  charts/openyurt/templates/yurt-controller-manager.yaml
  pkg/controller/gateway/gateway/gateway_controller.go
  pkg/controller/nodepool/util.go
  pkg/controller/poolcoordinator/delegatelease/poolcoordinator_controller.go
  pkg/controller/util/node/controller_utils.go
  pkg/node-servant/preflight/checks.go
Labels: approved, kind/bug, lgtm, size/L
