Repository openyurtio/openyurt, pull requests merged in 2023-06, with the labels that each got.

#1504 feat: add e2e test case for daemonset pod updater controller
  test/e2e/yurt/daemonpodupdater.go
Labels: approved, lgtm, size/L

#1513 fix typo
  pkg/yurthub/cachemanager/cache_manager.go
Labels: approved, lgtm, size/XS

#1486 improve yurtstaticset template metadata
  charts/yurthub/templates/yurthub-cloud-yurtstaticset.yaml
  charts/yurthub/templates/yurthub-yurtstaticset.yaml
  pkg/apis/apps/v1alpha1/default.go
Labels: approved, lgtm, size/XS, kind/feature

#1517 feat: use real kubernetes server address to yurthub when yurtadm join
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/yurthub/yurthub.go
  pkg/yurtadm/util/yurthub/yurthub_test.go
Labels: approved, lgtm, size/L

#1519 fix typo
  pkg/controller/yurtstaticset/yurtstaticset_controller.go
Labels: approved, lgtm, size/XS

#1522 feat: cleanup "yurt-manager" temporary dir after "local-up-openyurt"
  test/e2e/cmd/init/converter.go
Labels: approved, lgtm, size/S

#1516 improve yurtstaticset upgrade for existing static pod
  pkg/controller/yurtstaticset/upgradeinfo/upgrade_info.go
  pkg/controller/yurtstaticset/upgradeinfo/upgrade_info_test.go
Labels: kind/enhancement, lgtm, size/L

#1501 fix yurthub memory leak
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/storage/etcd/keycache.go
  pkg/yurthub/storage/etcd/storage.go
Labels: approved, kind/bug, lgtm, size/S

#1523 fix: yurtadm support enable kubelet service
  pkg/yurtadm/cmd/join/phases/prepare.go
  pkg/yurtadm/util/initsystem/initsystem.go
  pkg/yurtadm/util/initsystem/initsystem_unix.go
  pkg/yurtadm/util/initsystem/initsystem_windows.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
Labels: approved, kind/bug, lgtm, size/L

#1487 feat: support SIGUSR1 signal for yurthub
  cmd/yurthub/app/start.go
  pkg/yurthub/util/dumpstack.go
  pkg/yurthub/util/dumpstack_test.go
Labels: approved, lgtm, size/L

#1534 fix: ide reconciler convert error and ServiceEnable return value wrong
  pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
  pkg/yurtadm/util/initsystem/initsystem_windows.go
Labels: approved, kind/bug, lgtm, size/XS

#1532 rename pool-coordinator to yurt-coordinator for yurthub
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/options/options_test.go
  cmd/yurthub/app/start.go
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/metrics/metrics.go
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/storage/etcd/keycache.go
  pkg/yurthub/storage/etcd/keycache_test.go
  pkg/yurthub/storage/etcd/storage.go
  pkg/yurthub/util/util.go
  pkg/yurthub/yurtcoordinator/certmanager/certmanager.go
  pkg/yurthub/yurtcoordinator/certmanager/certmanager_test.go
  pkg/yurthub/yurtcoordinator/constants/constants.go
  pkg/yurthub/yurtcoordinator/coordinator.go
  pkg/yurthub/yurtcoordinator/coordinator_test.go
  pkg/yurthub/yurtcoordinator/fake_coordinator.go
  pkg/yurthub/yurtcoordinator/informer_lease.go
  pkg/yurthub/yurtcoordinator/leader_election.go
  pkg/yurthub/yurtcoordinator/resources/resources.go
  pkg/yurthub/yurtcoordinator/resources/verifiable_pool_scope_resource.go
Labels: approved, lgtm, size/L, kind/feature

#1531 rename pool-coordinator to yurt-coordinator for controller
  pkg/controller/controller.go
  pkg/controller/csrapprover/csrapprover_controller.go
  pkg/controller/yurtcoordinator/cert/certificate.go
  pkg/controller/yurtcoordinator/cert/certificate_test.go
  pkg/controller/yurtcoordinator/cert/secret.go
  pkg/controller/yurtcoordinator/cert/secret_test.go
  pkg/controller/yurtcoordinator/cert/util.go
  pkg/controller/yurtcoordinator/cert/util_test.go
  pkg/controller/yurtcoordinator/cert/yurtcoordinatorcert_controller.go
  pkg/controller/yurtcoordinator/cert/yurtcoordinatorcert_controller_test.go
  pkg/controller/yurtcoordinator/constant/constant.go
  pkg/controller/yurtcoordinator/delegatelease/delegatelease_controller.go
  pkg/controller/yurtcoordinator/delegatelease/delegatelease_controller_test.go
  pkg/controller/yurtcoordinator/podbinding/podbinding_controller.go
  pkg/controller/yurtcoordinator/utils/lease.go
  pkg/controller/yurtcoordinator/utils/lease_test.go
  pkg/controller/yurtcoordinator/utils/taints.go
  pkg/controller/yurtcoordinator/utils/taints_test.go
  pkg/webhook/pod/v1/pod_validation.go
Labels: approved, lgtm, size/L, kind/feature

#1533 rename pool-coordinator to yurt-coordinator for other
  CHANGELOG.md
  README.md
  README.zh.md
  charts/README.md
  charts/pool-coordinator/Chart.yaml
  charts/pool-coordinator/templates/_helpers.tpl
  charts/pool-coordinator/templates/pool-coordinator.yaml
  charts/pool-coordinator/values.yaml
  charts/yurthub/templates/yurthub-cfg.yaml
  docs/proposals/20220307-nodepool-governance-capability.md
  docs/proposals/20220414-multiplexing-cloud-edge-traffic.md
  docs/proposals/20220627-yurthub-cache-refactoring.md
  docs/roadmap.md
  hack/lib/sync-charts.sh
Labels: approved, lgtm, size/L, kind/feature

#1537 feat: remove yurtadm init command
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/yurtinit/init.go
  pkg/yurtadm/cmd/yurtinit/options.go
Labels: approved, lgtm, size/L, kind/feature

#1518 feat: add e2e test case for yurtstaticset controller
  test/e2e/yurt/yurtstaticset.go
Labels: approved, lgtm, size/L

#1402 add yurtadm join node in specified nodepool
  charts/yurthub/templates/yurthub-cloud-yurtstaticset.yaml
  charts/yurthub/templates/yurthub-yurtstaticset.yaml
  pkg/util/kubeconfig/kubeconfig.go
  pkg/util/kubeconfig/kubeconfig_test.go
  pkg/util/kubernetes/kubeadm/app/util/apiclient/idempotency.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/yurthub/yurthub.go
  pkg/yurtadm/util/yurthub/yurthub_test.go
Labels: lgtm, size/L, kind/feature

#1538 check nil in podbinding_controller.go and handle some errors
  pkg/controller/yurtcoordinator/podbinding/podbinding_controller.go
Labels: kind/bug, lgtm, size/S

#1551 rename pool-coordinator to yurt-coordinator for charts
  charts/yurt-coordinator/.helmignore
  charts/yurt-coordinator/Chart.yaml
  charts/yurt-coordinator/templates/_helpers.tpl
  charts/yurt-coordinator/templates/yurt-coordinator.yaml
  charts/yurt-coordinator/values.yaml
Labels: approved, lgtm, size/XS, kind/feature

#1554 feat: remove watch nodepool in service topology controller
  pkg/controller/servicetopology/adapter/adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
  pkg/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/controller/servicetopology/endpoints/endpoints_enqueue_handlers.go
  pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
  pkg/controller/servicetopology/endpointslice/endpointslice_enqueue_handlers.go
  pkg/controller/servicetopology/util/util.go
Labels: approved, do-not-merge/hold, lgtm, size/XL

#1555 delete unused functions
  pkg/controller/servicetopology/adapter/adapter.go
Labels: approved, kind/enhancement, lgtm, size/M

#1552 fix conflicts for getting node by local storage in yurthub filters
  cmd/yurthub/app/config/config.go
  pkg/yurthub/filter/filter.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/manager/manager_test.go
  pkg/yurthub/filter/nodeportisolation/filter.go
  pkg/yurthub/filter/nodeportisolation/filter_test.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/filter_test.go
Labels: approved, kind/bug, lgtm, size/XL

#1488 move iot controller to yurt-manager
  charts/yurt-manager/crds/iot.openyurt.io_platformadmins.yaml
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/app/options/platformadmincontroller.go
  go.mod
  pkg/apis/addtoscheme_iot_v1alpha1.go
  pkg/apis/addtoscheme_iot_v1alpha2.go
  pkg/apis/iot/v1alpha1/condition_const.go
  pkg/apis/iot/v1alpha1/default.go
  pkg/apis/iot/v1alpha1/doc.go
  pkg/apis/iot/v1alpha1/groupversion_info.go
  pkg/apis/iot/v1alpha1/platformadmin_conversion.go
  pkg/apis/iot/v1alpha1/platformadmin_types.go
  pkg/apis/iot/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/iot/v1alpha2/condition_const.go
  pkg/apis/iot/v1alpha2/default.go
  pkg/apis/iot/v1alpha2/doc.go
  pkg/apis/iot/v1alpha2/groupversion_info.go
  pkg/apis/iot/v1alpha2/platformadmin_conversion.go
  pkg/apis/iot/v1alpha2/platformadmin_types.go
  pkg/apis/iot/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/apis/config/types.go
  pkg/controller/controller.go
  pkg/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
  pkg/controller/platformadmin/config/EdgeXConfig/config.json
  pkg/controller/platformadmin/config/EdgeXConfig/manifest.yaml
  pkg/controller/platformadmin/config/types.go
  pkg/controller/platformadmin/platformadmin_controller.go
  pkg/controller/platformadmin/utils/fieldindexer.go
  pkg/controller/platformadmin/utils/util.go
  pkg/webhook/platformadmin/v1alpha1/platformadmin_default.go
  pkg/webhook/platformadmin/v1alpha1/platformadmin_handler.go
  pkg/webhook/platformadmin/v1alpha1/platformadmin_validation.go
  pkg/webhook/platformadmin/v1alpha2/platformadmin_default.go
  pkg/webhook/platformadmin/v1alpha2/platformadmin_handler.go
  pkg/webhook/platformadmin/v1alpha2/platformadmin_validation.go
  pkg/webhook/server.go
Labels: approved, lgtm, size/XXL

#1514 improve yurthub get pods for cloud node
  cmd/yurthub/app/config/config.go
  pkg/yurthub/server/server.go
Labels: approved, kind/enhancement, lgtm, size/M

#1547 feat: provide config option for yurtadm
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/cmd/join/phases/joinnode.go
  pkg/yurtadm/cmd/join/phases/prepare.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/yurthub/yurthub_test.go
Labels: approved, lgtm, size/M, kind/feature

#1550 add yurtadm to install/uninstall staticpod
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/cmd/join/phases/prepare.go
  pkg/yurtadm/cmd/staticpods/install/install.go
  pkg/yurtadm/cmd/staticpods/staticpods.go
  pkg/yurtadm/cmd/staticpods/uninstall/uninstall.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/edgenode/edgenode.go
  pkg/yurtadm/util/edgenode/edgenode_test.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
  pkg/yurtadm/util/yurthub/yurthub.go
  pkg/yurtadm/util/yurthub/yurthub_test.go
Labels: approved, lgtm, size/XL, kind/feature

#1563 update chart version from v1.3.0 to v1.3.2
  charts/yurt-coordinator/Chart.yaml
  charts/yurt-manager/Chart.yaml
  charts/yurt-manager/values.yaml
  charts/yurthub/Chart.yaml
  charts/yurthub/values.yaml
Labels: approved, kind/documentation, lgtm, size/S

#1565 feat: improve service topology controller by using client.Client instead of kubernetes.Interface
  pkg/controller/servicetopology/adapter/endpoints_adapter.go
  pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
  pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
  pkg/controller/servicetopology/endpoints/endpoints_controller.go
  pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
Labels: approved, lgtm, size/L, kind/feature

#1485 improve pod binding controller to use client.Client
  pkg/controller/yurtcoordinator/podbinding/podbinding_controller.go
  pkg/controller/yurtcoordinator/podbinding/podbinding_controller_test.go
Labels: approved, lgtm, size/XL, kind/feature

#1570 add unit test cases for yurthub filters
  pkg/yurthub/filter/discardcloudservice/filter.go
  pkg/yurthub/filter/discardcloudservice/filter_test.go
  pkg/yurthub/filter/inclusterconfig/filter.go
  pkg/yurthub/filter/inclusterconfig/filter_test.go
  pkg/yurthub/filter/initializer/initializer.go
  pkg/yurthub/filter/initializer/initializer_test.go
  pkg/yurthub/filter/masterservice/filter.go
  pkg/yurthub/filter/masterservice/filter_test.go
  pkg/yurthub/filter/nodeportisolation/filter.go
  pkg/yurthub/filter/nodeportisolation/filter_test.go
  pkg/yurthub/filter/servicetopology/filter.go
  pkg/yurthub/filter/servicetopology/filter_test.go
Labels: approved, lgtm, size/L

#1569 add unit testcases for controller utils
  pkg/controller/util/controller_utils_test.go
  pkg/controller/util/statefulset_utils.go
  pkg/controller/util/tools.go
Labels: approved, lgtm, size/L, kind/feature
