Repository openyurtio/openyurt, pull requests merged in 2023-01, with the labels that each got.

#1112 bugfix: dynamically switch apiVersion of JoinConfiguration to adapt to different versions of k8s
  go.mod
  go.sum
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
Labels: approved, kind/bug, lgtm, size/S

#1105 add_initializer_test.go
  pkg/yurttunnel/handlerwrapper/initializer/initializer.go
  pkg/yurttunnel/handlerwrapper/initializer/initializer_test.go
Labels: approved, lgtm, size/L

#1111 add selfsigned pool-coordinator cert manager
  charts/openyurt/templates/yurt-controller-manager.yaml
  pkg/controller/poolcoordinator/cert/certificate.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
  pkg/controller/poolcoordinator/cert/secret.go
  pkg/controller/poolcoordinator/cert/util.go
Labels: approved, kind/feature, size/XXL

#1120 Fix: pub key bug
  pkg/controller/poolcoordinator/cert/certificate.go
Labels: size/XS

#1121 fix: update apiserver etcd protocol from http to https
  charts/openyurt/templates/pool-coordinator.yaml
Labels: size/XS

#1119 Fix: sa.key missing position bug.
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
Labels: size/XS

#1117 fix: issue 1116
  charts/openyurt/templates/pool-coordinator.yaml
Labels: size/S

#1115 bugfix: update the dependency yurt-app-manager-api from v0.18.8 to v0.6.0
  go.mod
  go.sum
Labels: approved, kind/bug, lgtm, size/L

#1122 add 127.0.0.1 into etcd server cert
  charts/openyurt/values.yaml
  pkg/controller/poolcoordinator/cert/certificate.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
Labels: size/M

#1114 add tunnelAgentConnectPort to values
  charts/openyurt/templates/yurt-tunnel-server.yaml
  charts/openyurt/values.yaml
Labels: approved, lgtm, size/XS

#1103 generate coordinator client and pass through SubjectAccessReview according to secret
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/node-servant/config/control-plane.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/healthchecker/health_checker_test.go
  pkg/yurthub/poolcoordinator/certmanager/certmanager.go
  pkg/yurthub/poolcoordinator/constants/constants.go
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/poolcoordinator/fake_coordinator.go
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/transport/transport.go
Labels: size/XL, kind/feature

#1123 Fix: add back kubeConfig init logic to fix npe
  cmd/yurthub/app/config/config.go
Labels: size/S

#1108 make yurt-controller-manager take care of webhook configurations and …
  charts/openyurt/templates/_helpers.tpl
  charts/openyurt/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/role.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/openyurt/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/openyurt/templates/admission-webhooks/mutatingwebhookconfiguration.yaml
  charts/openyurt/templates/admission-webhooks/validatingwebhookconfiguration.yaml
  charts/openyurt/templates/admission-webhooks/webhookService.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/values.yaml
  pkg/controller/poolcoordinator/utils/file.go
  pkg/webhook/certs.go
  pkg/webhook/poolcoordinator_webhook.go
  pkg/webhook/webhook.go
Labels: approved, size/XL

#1128 Fix: Controller coordinator add ca.crt to yurthub cert
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
Labels: approved, size/XS

#1130 Ftr: change yurthub cert to admin
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
Labels: size/XS

#1131 bufix: set isPoolCacheSynced as true if lease updated
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/poolcoordinator/coordinator_test.go
Labels: kind/bug, size/L

#1132 improve yurtadm join command
  go.mod
  pkg/util/kubeconfig/kubeconfig.go
  pkg/util/kubeconfig/kubeconfig_test.go
  pkg/util/pubkeypin/pubkeypin.go
  pkg/util/pubkeypin/pubkeypin_test.go
  pkg/util/token/token.go
  pkg/util/token/token_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
Labels: approved, kind/enhancement, lgtm, size/L

#1134 bugfix: do not send pool-scoped resource list/watch request to pool-c…
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
Labels: size/S

#1124 Feature: yurtadm reset/join modification. Do not remove k8s binaries, add flag for using local cni binaries.
  pkg/yurtadm/cmd/join/join.go
  pkg/yurtadm/cmd/join/join_test.go
  pkg/yurtadm/cmd/join/joindata/data.go
  pkg/yurtadm/cmd/join/phases/prepare.go
  pkg/yurtadm/cmd/reset/phases/cleanyurtfile.go
  pkg/yurtadm/constants/constants.go
  pkg/yurtadm/util/kubernetes/kubernetes.go
Labels: approved, lgtm, size/M, kind/feature

#1126 Fix: pool-coordinator
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/start.go
  pkg/yurthub/certificate/hubself/cert_mgr_test.go
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/poolcoordinator/leader_election.go
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/proxy.go
  pkg/yurthub/proxy/remote/loadbalancer.go
  pkg/yurthub/storage/etcd/keycache.go
Labels: approved, size/L

#1137 Bugfix of pool-coordinator and enable unit test to pass
  go.mod
  go.sum
  pkg/profile/profile_test.go
  pkg/yurthub/certificate/hubself/cert_mgr_test.go
  pkg/yurthub/storage/disk/storage.go
  pkg/yurthub/storage/disk/storage_test.go
  pkg/yurthub/storage/etcd/etcd_suite_test.go
  pkg/yurthub/storage/etcd/key_test.go
  pkg/yurthub/storage/etcd/keycache.go
  pkg/yurthub/storage/etcd/keycache_test.go
  pkg/yurthub/storage/etcd/mock/kv.go
  pkg/yurthub/storage/etcd/storage.go
  pkg/yurthub/storage/etcd/storage_test.go
Labels: approved, kind/bug, size/L

#1139 use pointer receiver in mocked clientv3.KV to avoid passing lock by value
  pkg/yurthub/storage/etcd/keycache_test.go
  pkg/yurthub/storage/etcd/mock/kv.go
Labels: approved, size/S

#1140 test: add unit test for poolcoordinator cert manager
  pkg/yurthub/poolcoordinator/certmanager/certmanager.go
  pkg/yurthub/poolcoordinator/certmanager/certmanager_test.go
Labels: approved, size/L

#1141 Fix: pool-coordinator chart format, default service name, max body size .etc
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  cmd/yurthub/app/options/options.go
  pkg/yurthub/storage/etcd/storage.go
  pkg/yurthub/util/util.go
Labels: size/L

#1133 Improve certificate manager
  cmd/yurt-tunnel-server/app/start.go
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/start.go
  pkg/controller/certificates/csrapprover.go
  pkg/controller/certificates/csrapprover_test.go
  pkg/node-servant/components/yurthub.go
  pkg/util/certmanager/factory/factory.go
  pkg/util/certmanager/factory/factory_test.go
  pkg/util/certmanager/pki.go
  pkg/util/certmanager/pki_test.go
  pkg/yurthub/certificate/hubself/cert_mgr.go
  pkg/yurthub/certificate/hubself/cert_mgr_test.go
  pkg/yurthub/certificate/hubself/fake_cert_mgr.go
  pkg/yurthub/certificate/interfaces.go
  pkg/yurthub/certificate/token/testdata/ca.crt
  pkg/yurthub/certificate/token/testdata/ca.key
  pkg/yurthub/certificate/token/testdata/fake_client.go
  pkg/yurthub/certificate/token/token.go
  pkg/yurthub/certificate/token/token_test.go
  pkg/yurthub/healthchecker/fake_checker.go
  pkg/yurthub/healthchecker/health_checker.go
  pkg/yurthub/healthchecker/interfaces.go
  pkg/yurthub/kubernetes/rest/config.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/otaupdate/ota_test.go
  pkg/yurthub/server/certificate.go
  pkg/yurthub/server/certificate_test.go
  pkg/yurthub/server/nonresource_test.go
  pkg/yurthub/server/server.go
  pkg/yurthub/transport/transport.go
  pkg/yurthub/util/util.go
  pkg/yurthub/util/util_test.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#1142 fix coordinator sync problem and update ready condition
  pkg/yurthub/poolcoordinator/coordinator.go
Labels: approved, kind/bug, size/S

#1144 Fix: dns bug for endpointslices v1beta1 version
  pkg/yurthub/server/nonresource.go
Labels: size/XS

#1146 Add unit test for poolcoordinator certmanager controller
  pkg/controller/poolcoordinator/cert/certificate.go
  pkg/controller/poolcoordinator/cert/certificate_test.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager_test.go
  pkg/controller/poolcoordinator/cert/secret.go
  pkg/controller/poolcoordinator/cert/secret_test.go
  pkg/controller/poolcoordinator/cert/util_test.go
Labels: approved, size/XL

#1145 Fix: set inElecting to false when handling follow hub, and add metrics
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  cmd/yurthub/app/start.go
  pkg/yurthub/metrics/metrics.go
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/poolcoordinator/leader_election.go
Labels: size/L

#1149 fix: update package dependencies
  go.mod
  go.sum
  pkg/yurthub/proxy/local/faketoken.go
Labels: approved, lgtm, size/M

#1147 fix coredns cannot get /apis/discovery.k8s.io/v1 if cluster does not contain such resource
  pkg/yurthub/server/nonresource.go
  pkg/yurthub/server/nonresource_test.go
Labels: approved, kind/bug, lgtm, size/M

#1143 bugfix: yurthub can not exit when SIGINT/SIGTERM happened
  cmd/yurthub/app/config/config.go
  cmd/yurthub/app/config/config_test.go
  cmd/yurthub/app/options/options.go
  cmd/yurthub/app/options/options_test.go
  cmd/yurthub/app/start.go
  pkg/yurthub/certificate/token/token.go
  pkg/yurthub/certificate/token/token_test.go
  pkg/yurthub/filter/manager/manager.go
  pkg/yurthub/filter/manager/manager_test.go
  pkg/yurthub/gc/gc.go
  pkg/yurthub/kubernetes/rest/config_test.go
  pkg/yurthub/network/iptables.go
  pkg/yurthub/network/network.go
  pkg/yurthub/proxy/util/util_test.go
  pkg/yurthub/server/certificate_test.go
  pkg/yurthub/server/server.go
  pkg/yurthub/tenant/tenant.go
  pkg/yurthub/util/util.go
Labels: approved, kind/bug, lgtm, size/XL

#1152 fix: add common builder
  Makefile
Labels: approved, lgtm, size/M

#1148 Fix: add PoolScopeResource validation and dynamic configuration support
  charts/openyurt/templates/pool-coordinator.yaml
  pkg/yurthub/kubernetes/meta/restmapper.go
  pkg/yurthub/poolcoordinator/constants/constants.go
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/poolcoordinator/resources/resources.go
  pkg/yurthub/poolcoordinator/resources/verifiable_pool_scope_resource.go
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/util/util.go
  pkg/yurthub/storage/etcd/keycache.go
  pkg/yurthub/storage/etcd/storage.go
  pkg/yurthub/util/util.go
Labels: approved, size/L

#1155 fix: update slack link
  README.md
  README.zh.md
Labels: approved, lgtm, size/XS

#1159 generate yurtadm docs
  go.sum
  pkg/yurtadm/cmd/cmd.go
  pkg/yurtadm/cmd/docs/docs.go
Labels: approved, kind/enhancement, lgtm, size/M

#1158 add inclusterconfig filter for commenting kube-proxy configmap
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
  pkg/yurthub/filter/constant.go
  pkg/yurthub/filter/inclusterconfig/filter.go
  pkg/yurthub/filter/inclusterconfig/handler.go
  pkg/yurthub/filter/inclusterconfig/handler_test.go
  pkg/yurthub/filter/manager/manager.go
Labels: approved, lgtm, size/L, kind/feature

#1157 add poolcoordinator certmanager controller
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  pkg/controller/certificates/csrapprover.go
  pkg/controller/poolcoordinator/cert/certificate.go
  pkg/controller/poolcoordinator/cert/certificate_test.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager_test.go
  pkg/controller/poolcoordinator/cert/secret.go
  pkg/controller/poolcoordinator/cert/secret_test.go
  pkg/controller/poolcoordinator/cert/util.go
  pkg/controller/poolcoordinator/cert/util_test.go
  pkg/util/ip/ip.go
  pkg/util/ip/ip_test.go
  pkg/util/kubeconfig/kubeconfig.go
  pkg/util/kubeconfig/kubeconfig_test.go
Labels: kind/feature, size/XXL

#1151 add poolcoordinator controller and webhooks to replace nodelifecycle …
  charts/openyurt/templates/_helpers.tpl
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/values.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  go.mod
  go.sum
  pkg/controller/nodelifecycle/metrics.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/rate_limited_queue.go
  pkg/controller/nodelifecycle/scheduler/rate_limited_queue_test.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/nodelifecycle/scheduler/timed_workers_test.go
  pkg/controller/poolcoordinator/constant/constant.go
  pkg/controller/poolcoordinator/poolcoordinator_controller.go
  pkg/controller/poolcoordinator/poolcoordinator_controller_test.go
  pkg/controller/poolcoordinator/utils/file.go
  pkg/controller/poolcoordinator/utils/file_test.go
  pkg/controller/poolcoordinator/utils/lease.go
  pkg/controller/poolcoordinator/utils/lease_test.go
  pkg/controller/poolcoordinator/utils/nodepool.go
  pkg/controller/poolcoordinator/utils/nodepool_test.go
  pkg/controller/poolcoordinator/utils/taints.go
  pkg/controller/poolcoordinator/utils/taints_test.go
  pkg/controller/poolcoordinator/utils/tolerations.go
  pkg/controller/poolcoordinator/utils/tolerations_test.go
  pkg/webhook/certs.go
  pkg/webhook/certs_test.go
  pkg/webhook/poolcoordinator_webhook.go
  pkg/webhook/poolcoordinator_webhook_test.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, kind/feature, size/XXL

#1160 feat: add pool-coordinator charts
  charts/openyurt/README.md
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/values.yaml
Labels: approved, lgtm, size/L, kind/feature

#1161 delete yurt tunnel helm charts
  charts/openyurt/templates/yurt-tunnel-agent.yaml
  charts/openyurt/templates/yurt-tunnel-server.yaml
  charts/openyurt/values.yaml
Labels: approved, lgtm, size/L

#1162 Fix: yurthub proxy server addr option
  cmd/yurthub/app/config/config.go
Labels: approved, lgtm, size/XS

#1164 bugfix: yurt-controller-manager cannot restart
  pkg/webhook/poolcoordinator_webhook.go
Labels: approved, kind/bug, size/M

#1167 Fix log
  pkg/yurthub/cachemanager/cache_manager.go
  pkg/yurthub/poolcoordinator/resources/resources.go
Labels: approved, kind/bug, lgtm, size/XS

#1166 fix charts
  charts/openyurt/templates/pool-coordinator.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/templates/yurthub-cfg.yaml
Labels: approved, lgtm, size/S

#1175 bugfix: cannot upload local cache
  pkg/yurthub/poolcoordinator/coordinator.go
  pkg/yurthub/storage/disk/key.go
  pkg/yurthub/storage/disk/key_test.go
Labels: approved, kind/bug, lgtm, size/L

#1173 fix: isRunning state of poolCacheSyncedDetector is not updated
  pkg/yurthub/poolcoordinator/coordinator.go
Labels: approved, kind/bug, lgtm, size/XS

#1174 rbac: add endpoints/endpointslices list/watch to yurt-hub clusterrole
  charts/openyurt/templates/yurthub-cfg.yaml
Labels: approved, kind/bug, lgtm, size/S

#1165 fix: leader yurthub cannot proxy heartbeat
  charts/openyurt/templates/pool-coordinator.yaml
  cmd/yurthub/app/start.go
  pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
  pkg/yurthub/poolcoordinator/certmanager/certmanager.go
  pkg/yurthub/poolcoordinator/certmanager/certmanager_test.go
  pkg/yurthub/poolcoordinator/coordinator.go
Labels: approved, kind/bug, size/XL

#1178 improve proxy log message
  pkg/yurthub/proxy/local/local.go
  pkg/yurthub/proxy/pool/pool.go
  pkg/yurthub/proxy/remote/loadbalancer.go
Labels: kind/bug, size/S

#1179 add leader-yurthub into default cache agents
  pkg/yurthub/util/util.go
Labels: approved, kind/enhancement, lgtm, size/XS

#1163 update readme and changeLog for OpenYurt v1.2.0
  CHANGELOG.md
  README.md
  README.zh.md
  docs/img/arch.png
Labels: approved, kind/documentation, lgtm, size/M

#1177 imporve pool coordinator controller
  charts/openyurt/Chart.yaml
  charts/openyurt/templates/yurt-controller-manager.yaml
  charts/openyurt/values.yaml
  cmd/yurt-controller-manager/app/controllermanager.go
  cmd/yurt-controller-manager/app/core.go
  cmd/yurt-controller-manager/app/options/nodelifecyclecontroller.go
  cmd/yurt-controller-manager/app/options/options.go
  go.mod
  go.sum
  pkg/controller/poolcoordinator/constant/constant.go
  pkg/controller/poolcoordinator/delegatelease/poolcoordinator_controller.go
  pkg/controller/poolcoordinator/delegatelease/poolcoordinator_controller_test.go
  pkg/controller/poolcoordinator/podbinding/pod_binding_controller.go
  pkg/controller/poolcoordinator/utils/file.go
  pkg/controller/poolcoordinator/utils/file_test.go
  pkg/controller/poolcoordinator/utils/nodepool.go
  pkg/controller/poolcoordinator/utils/nodepool_test.go
  pkg/controller/poolcoordinator/utils/tolerations.go
  pkg/controller/poolcoordinator/utils/tolerations_test.go
  pkg/node-servant/config/control-plane.go
  pkg/webhook/certs.go
  pkg/webhook/certs_test.go
  pkg/webhook/poolcoordinator_webhook.go
  pkg/webhook/poolcoordinator_webhook_test.go
  pkg/webhook/webhook.go
  pkg/yurtctl/cmd/yurttest/kindinit/init.go
  pkg/yurtctl/constants/constants.go
  pkg/yurthub/healthchecker/health_checker.go
Labels: approved, kind/enhancement, lgtm, size/XXL

#1180 revise readme
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1181 revise changeLog for v1.2
  CHANGELOG.md
Labels: approved, kind/documentation, lgtm, size/S
