Repository openyurtio/openyurt, pull requests merged in 2024-04, with the labels that each got.

#2001 feat: modify sonar and codecov config
  .codecov.yml
  sonar-project.properties
Labels: approved, lgtm

#1997 feat: add yurtappset validation webhook and default nodepool label
  pkg/apis/apps/well_known_labels_annotations.go
  pkg/yurtmanager/controller/yurtappset/revision.go
  pkg/yurtmanager/controller/yurtappset/workloadmanager/deployment_manager.go
  pkg/yurtmanager/controller/yurtappset/workloadmanager/statefulset_manager.go
  pkg/yurtmanager/controller/yurtappset/workloadmanager/statefulset_manager_test.go
  pkg/yurtmanager/controller/yurtappset/workloadmanager/tweaks.go
  pkg/yurtmanager/controller/yurtappset/workloadmanager/tweaks_test.go
  pkg/yurtmanager/controller/yurtappset/yurtappset_controller.go
  pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_default.go
  pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_default_test.go
  pkg/yurtmanager/webhook/yurtappset/v1beta1/yurtappset_handler.go
  pkg/yurtmanager/webhook/yurtappset/v1beta1/yurtappset_validation.go
  pkg/yurtmanager/webhook/yurtappset/v1beta1/yurtappset_webhook_test.go
  test/e2e/cmd/init/converter_test.go
Labels: approved, lgtm

#2013 fix only openyurt crd conversion should be handled for upgrading cert
  pkg/yurtmanager/webhook/util/controller/webhook_controller.go
Labels: approved, kind/bug, lgtm

#2016 1909
  cmd/yurt-manager/app/options/platformadmincontroller.go
  pkg/yurtmanager/controller/platformadmin/config/config.go
  pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
Labels: approved, lgtm

#2010 add pool service controller.
  charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
  cmd/yurt-manager/app/options/loadbalancersetcontroller.go
  cmd/yurt-manager/app/options/options.go
  cmd/yurt-manager/app/options/poolservicecontroller.go
  cmd/yurt-manager/names/controller_names.go
  pkg/apis/network/v1alpha1/groupversion_info.go
  pkg/apis/network/v1alpha1/poolservice_types.go
  pkg/apis/network/v1alpha1/zz_generated.deepcopy.go
  pkg/yurtmanager/controller/apis/config/types.go
  pkg/yurtmanager/controller/controller.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/annotations.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/config/types.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/event_handler.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/event_handler_test.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/finalizer.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/loadbalancer_status.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/loadbalancerset_controller.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/loadbalancerset_controller_test.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate_test.go
  pkg/yurtmanager/controller/poolservice/config/types.go
  pkg/yurtmanager/controller/poolservice/poolservice_controller.go
  pkg/yurtmanager/webhook/poolservice/v1alpha1/poolservice_handler.go
  pkg/yurtmanager/webhook/poolservice/v1alpha1/poolservice_validation.go
Labels: approved, lgtm

#2019 modify status of poolservice
  charts/yurt-manager/crds/network.openyurt.io_poolservices.yaml
  hack/make-rules/kustomize_to_chart.sh
  pkg/apis/network/v1alpha1/poolservice_types.go
  pkg/apis/network/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm

#2026 change mail address for security disclosure
  SECURITY.md
Labels: approved, lgtm

#2022 fix: update md lint
  .github/workflows/ci.yaml
  README.md
  README.zh.md
Labels: approved, lgtm

#2024 fix service status update.
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/loadbalancerset_controller.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate_test.go
Labels: approved, lgtm

#2025 feat: improve the configuration of concurrent servicetopology-endpoints workers
  cmd/yurt-manager/app/options/endpointscontroller.go
  cmd/yurt-manager/app/options/options.go
  pkg/yurtmanager/controller/apis/config/types.go
  pkg/yurtmanager/controller/servicetopology/endpoints/config/types.go
  pkg/yurtmanager/controller/servicetopology/endpoints/endpoints_controller.go
Labels: approved, lgtm

#2029 fix: edgex component creation cause registration errors and core-command crash
  pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
  pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config.json
Labels: approved, kind/bug, sig/iot, lgtm, backport release-v1.4

#2027 aggregated annotations and labels.
  pkg/apis/network/well_known_labels_annotations.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/aggregatetoannotations.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/aggregatetolabels.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/annotations.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/loadbalancerset_controller.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/loadbalancerset_controller_test.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/map_utils.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate.go
  pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate_test.go
Labels: approved, lgtm

#2030 fix: edgex component creation cause registration errors and core-command crash
  pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
  pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config.json
  test/e2e/yurt/yurtappoverrider.go
Labels: approved, kind/bug, sig/iot, lgtm, backport release-v1.4
